### ISSUE TITLE
Add maven goal for PIT report generation and maven site integration

### ISSUE THREAD

**Issue by hcoles** [hcoles/pitest#10]
_From [stefan.p...@googlemail.com](https://code.google.com/u/115492280750533935957/) on September 18, 2011 13:45:09_

PIT is currently hard coded to produce only a html report (see Issue 9 ). After revising the reporting stuff an enhanced maven plugin would be nice that generates a report integrated into the maven site.

_Original issue: http://code.google.com/p/pitestrunner/issues/detail?id=10_

**Comment by dustinbarnes** [comment]
Is there any plan to get this in there? I'm currently trying to hack around it, but this would be the thing that really cleanly integrates into the code quality lifecycle.

**Comment by hcoles** [comment]
@dustinbarnes Although I agree this would be good to have, I'm afraid it is unlikely to happen unless some-one jumps in and contributes a fix.

**Comment by dustinbarnes** [comment]
That sounds fair enough. It's not so much a fix as a new feature request, really. 

If I have some time, I might take a whack at it. I've created some maven mojo plugins, but never a reporting plugin. People can always go modify a site.xml and dump the PIT stuff into the ${basedir}/target/site directory, but it's kind of a pain.

**Comment by hcoles** [comment]
Pull requests gratefully received.

**Comment by jasonmfehr** [comment]
I'm working on writing a reporting mojo.  I'm not very far along, and given my current schedule, it will be a few weeks.  If you need it quicker and are going to work on it, please let me know so I can stop working on mine.

**Comment by lkwg82** [comment]
I'm curious about the status.

**Comment by jasonmfehr** [comment]
The initial development is done (other than fixing the long running integration tests).  In its current state, the reporting mojo simply copies the contents of the target/pit-reports directory.

I really want to add the ability to use the xml or csv files along with the doxia sink to generate a report that is fully integrated into the maven site, but that is not something I will have time to work on for a couple months.  If anyone else wants to work on it, I would be more than willing to help out where I can.

**Comment by lkwg82** [comment]
Maybe this issue can be split into `done` and `to do`? An issue with commits and status `unfinished` for long time looks like some blocker. 

This makes the status and progress much more clearer.

**Comment by jasonmfehr** [comment]
Yeah, definitely.  Want me to take care of closing down this issue an opening a new one?

**Comment by lkwg82** [comment]
Would be the best. You are on the topic and you know what have done and what is open. This also supports the maintainer to make releases and release notes. Thx.

**Comment by jasonmfehr** [comment]
A basic report mojo has been implemented and will be available with pitest-maven 1.1.6.  Issue #209 was created to further the work on the report mojo.  Please close this issue as done.

**Comment by lkwg82** [comment]
this can be closed
