### ISSUE TITLE
[1.7.4] Coverage generation minion exited abnormally!

### ISSUE THREAD

**Issue by cmarchand** [hcoles/pitest#1000]
Using 1.7.4 from Maven with Java 17, I get an exception saying I should open an issue. So...

Here is the stack trace :

```
[ERROR] Please copy and paste the information and the complete stacktrace below when reporting an issue
[ERROR] VM : OpenJDK 64-Bit Server VM
[ERROR] Vendor : Oracle Corporation
[ERROR] Version : 17.0.2+8-86
[ERROR] Uptime : 7070
[ERROR] Input -> 
[ERROR]  1 : -Dclassworlds.conf=/Users/cmarchand/applications/apache-maven-3.8.4/bin/m2.conf
[ERROR]  2 : -Dmaven.home=/Users/cmarchand/applications/apache-maven-3.8.4
[ERROR]  3 : -Dlibrary.jansi.path=/Users/cmarchand/applications/apache-maven-3.8.4/lib/jansi-native
[ERROR]  4 : -Dmaven.multiModuleProjectDirectory=/Users/cmarchand/devel/gitlab_oxiane/formation/cours/craft/vistamboire
[ERROR] BootClassPathSupported : false
[ERROR] 
[ERROR] 
[ERROR] Please copy and paste the information and the complete stacktrace below when reporting an issue
[ERROR] VM : OpenJDK 64-Bit Server VM
[ERROR] Vendor : Oracle Corporation
[ERROR] Version : 17.0.2+8-86
[ERROR] Uptime : 7070
[ERROR] Input -> 
[ERROR]  1 : -Dclassworlds.conf=/Users/cmarchand/applications/apache-maven-3.8.4/bin/m2.conf
[ERROR]  2 : -Dmaven.home=/Users/cmarchand/applications/apache-maven-3.8.4
[ERROR]  3 : -Dlibrary.jansi.path=/Users/cmarchand/applications/apache-maven-3.8.4/lib/jansi-native
[ERROR]  4 : -Dmaven.multiModuleProjectDirectory=/Users/cmarchand/devel/gitlab_oxiane/formation/cours/craft/vistamboire
[ERROR] BootClassPathSupported : false
```

I can provide code if required, it's opensource-able

Best regards,
Christophe

**Comment by hcoles** [comment]
Hi @cmarchand,

Yes, if you could provide a minimal example that reproduces the issue that would help.

Thanks

Henry

**Comment by cmarchand** [comment]
Ooops...

**Comment by cmarchand** [comment]
Solved : removed test that starts Spring, and added a simple UT on a simple calculation.

Just `git pull origin master`

**Comment by hcoles** [comment]
Issue looks to be that the tests use junit jupiter, but the pitest junit 5 plugin is not installed. The error message used to be a lot better when this happened, looks to have regressed when support for multiple concurrent test frameworks was added.

To fix the problem configure the junit 5 plugin as per

https://github.com/pitest/pitest-junit5-plugin

**Comment by cmarchand** [comment]
Thanks a lot, applying this to my pom solved the problem.

Seems that I've missed this in documentation...

Thanks a lot for your help,
Christophe
