### ISSUE TITLE
Test classes are being mutated

### ISSUE THREAD

**Issue by valentinacupac** [hcoles/pitest#1012]
I expected that classes ending with Test should be ignored (i..e only source code should be mutated, not the tests themselves).

Is this expected or unexpected behavior?

**Comment by hcoles** [comment]
If you are using maven or gradle, pitest should not mutate classes in the test tree. This not determined by which code root they are in, not by their name.

**Comment by hcoles** [comment]
@valentinacupac This sounds like a problem with the Intellij plugin you are using. I suggest you raise an issue there.
