### ISSUE TITLE
Kotlin emptyList() or listOf() ignored when mutating Kotlin class

### ISSUE THREAD

**Issue by mikesmithson** [hcoles/pitest#1013]
Not sure if this is a lack of understanding on my part or this is an issue. I have a Kotlin function in a class that does something like this:

`if (string.isEmpty()) {
    return emptyList()
}`

the pitest reports out this on the line that returns the empty list:

`replaced return value with Collections.emptyList for ..... -> SURVIVED`

I was originally using the kotlin.collections.KotlinCollectionsKt class for the emptyList() call. However, when I change the emptyList() to reference java.util.Collections.emptyList, then the mutation test passes. Any ideas? I personally prefer to use Kotlin as much as possible.

**Comment by hcoles** [comment]
Pitest understands Java and its libraries, out of the box it doesn't undestand kotlin.

It's smart enough to know that it shouldn't create a mutation that returns an empty list if the function already returns Collections.emptyList. As it doesn't understand kotlin, it does not recognise a call to KotlinCollections as equivalent.

If you're interested in mutating kotlin you should take a look at https://www.arcmutate.com/.
