### ISSUE TITLE
Coverage calculation failure with reflection unit test

### ISSUE THREAD

**Issue by HrFlorianHoffmann** [hcoles/pitest#1019]
Our unit test suite includes a unit test that uses reflection to inspect the String constants in a production class. This test class breaks PIT's coverage minion. When PIT runs the test suite (without mutations), it experiences the following error:

```
cannot access a member of class {some-package}.BacklogItem with modifiers "private static transient"
```

Please find below the complete code of the involved production class and its test. This should enable easy reproduction of this issue. Note that the involved classes do not involve any elements with "private static transient" modifiers. We assume that the coverage analyzer's modification of the classes leads to this error.

```
public final class BacklogItem {

    public static final String ABC = "DEF-123";

    private BacklogItem() {
    }

}
```

```
import org.junit.jupiter.api.Test;

import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

class BacklogItemTest {

    @Test
    void constantsDifferFromEachOther() throws IllegalAccessException {

        var constants = getConstants();
        var uniqueValues = getUniqueConstantValues();

        assertThat(constants).hasSize(uniqueValues.size());
    }

    @Test
    void constantsReferToGrcfincompBacklog() throws IllegalAccessException {

        var values = getUniqueConstantValues();

        for (var value : values) {
            assertThat(value).startsWith("DEF-");
        }
    }

    public Map<String, String> getConstants() throws IllegalAccessException {
        var result = new HashMap<String, String>();
        var fields = BacklogItem.class.getDeclaredFields();
        for (var field : fields) {
            var name = field.getName();
            var value = (String) field.get(null);
            result.put(name, value);
        }
        return result;
    }

    public Set<String> getUniqueConstantValues() throws IllegalAccessException {
        var constants = getConstants();
        return new HashSet<>(constants.values());
    }

}
```

For now, our workaround is to exclude this test class from the mutation suite. However, from our point of view, this test is not really special, or complicated. Note also that other testing tools, such as JUnit 5 that runs the tests, or JaCoCo that calculates the code coverage, do not experience this kind of problem.

We use `pitest-maven` `1.7.6` with the `pitest-junit5-plugin` `0.14` to run the tests.

**Comment by hcoles** [comment]
Hi @HrFlorianHoffmann sorry for the slow response.

On the one hand this is expected behaviour - pitest adds a synthetic field to the class to hold a coverage probe. It is generally accepted that any relection based code (particularly within tests) should filter out synthetic fields to avoid this problem.

What I don't understand is why you are not seeing the same issue with jacoco. Having just checked their git repo, they also add a synthetic, private, transient boolean array field.

Could you package this into an executable project that reproduces the issue (and works with jacoco)?

Thanks

**Comment by HrFlorianHoffmann** [comment]
Hey @hcoles, sorry for the delay. Yes, you're completely right on both accounts. It was the synthetic field. I was not aware of the convention to ignore them. In fact, I was not aware of synthetic fields at all... 😳 Added a filter condition to make the test ignore anything synthetic and this made PIT work for the test class. There is also something funny going on with JaCoCo for this class. The tested class is listed in the reports with zero coverage. Looks like JaCoCo doesn't run this test class at all. This is surprising because we don't have any exclusion filters there. I'm trying to find out what's happening.

**Comment by hcoles** [comment]
@HrFlorianHoffmann Thanks for getting back. I'll close this as everything is working as expected. Unfortunately the only way to avoid the synthetic fields on the class is to make the coverage calculation a lot less efficient.
