### ISSUE TITLE
🐛 PIT Excludes Classes With a Repository Dependency 🐞 

### ISSUE THREAD

**Issue by AlexandruGG** [hcoles/pitest#1023]
## Issue

The Pitest report seems to exclude any classes which have as dependency injections interfaces extending any of these:

- `org.springframework.data.jpa.repository.JpaRepository`
- `org.springframework.data.repository.CrudRepository`

The odd aspect is that PIT sees the classes during its run:

`10:04:10 PIT >> INFO : MINION : 10:04:10 PIT >> FINE : Gathering coverage for test Description [testClass=com.pitest.repo.MyServiceTest, name=[engine:junit-jupiter]/[class:com.pitest.repo.MyServiceTest]/[method:createSavesEntity()]]`

## Example

See a minimal example here, using Spring Boot 2.7.0, Java 17, and Maven: https://github.com/AlexandruGG/pitest-repo-issue-example.

`./mvnw clean test-compile org.pitest:pitest-maven:mutationCoverage`

I have also committed an example report [here](https://github.com/AlexandruGG/pitest-repo-issue-example/tree/main/pit-reports/202205251002), and see screenshot below which is **missing the MyService class**:
(as well as MyEntityRepository, should that one be included too?)

![Screenshot 2022-05-25 at 09 48 16](https://user-images.githubusercontent.com/34811569/170228319-548f2479-6d51-4709-944d-e43b414b0826.png)

```
================================================================================
- Statistics
================================================================================
>> Line Coverage: 6/11 (55%)
>> Generated 2 mutations Killed 0 (0%)
>> Mutations with no coverage 2. Test strength 0%
>> Ran 0 tests (0 tests per mutation)  <- note no tests are run even though there is a test - MyServiceTest !
```

## Expectation

These classes should appear in the final report and the tests covering them should be ran.

What I already tried:
- removing the `org.springframework.stereotype.Repository` annotation

Am I doing something wrong here, or is this a genuine issue?

**Comment by hcoles** [comment]
Hi @AlexandruGG, thanks for the report and the reproducing repo (makes life so much easier).

The issue is that MyService has no code in it which the active mutators can detect. Pitest doesn't produce a report for classes that have no mutants, which is admittedly a bit confusing in cases such as this, and should perhaps be examined.

If you activate the non void method calls mutator, it will be able to seed faults into this code and the classes will appear.

          <mutators><value>NON_VOID_METHOD_CALLS</value><value>DEFAULTS</value></mutators>

Although it might seem like a good idea to activate it based on this small example, I would not usually recomend it. It creates a lot of mutants, most of which are of low quality.

We will be looking at adding some spring specific operators to the arcmutate extended set in the near future. These will be able to create useful mutations in this sort of code without the noise.

https://docs.arcmutate.com/docs/extended-operators.html

**Comment by AlexandruGG** [comment]
> Hi @AlexandruGG, thanks for the report and the reproducing repo (makes life so much easier).
> 
> The issue is that MyService has no code in it which the active mutators can detect. Pitest doesn't produce a report for classes that have no mutants, which is admittedly a bit confusing in cases such as this, and should perhaps be examined.
> 
> If you activate the non void method calls mutator, it will be able to seed faults into this code and the classes will appear.
> 
> ```
>       <mutators><value>NON_VOID_METHOD_CALLS</value><value>DEFAULTS</value></mutators>
> ```
> 
> Although it might seem like a good idea to activate it based on this small example, I would not usually recomend it. It creates a lot of mutants, most of which are of low quality.
> 
> We will be looking at adding some spring specific operators to the arcmutate extended set in the near future. These will be able to create useful mutations in this sort of code without the noise.
> 
> https://docs.arcmutate.com/docs/extended-operators.html

Hey @hcoles, thank you for the quick reply!

I should've thought about that one 😅. It makes perfect sense, but indeed might be less confusing to still show those classes in the report.

I get the idea behind `NON_VOID_METHOD_CALLS` -> in this case it can be valuable because the main reason the method is called is for the _side effect_, even though its returned value is ignored.

One last question I couldn't answer myself so far. Is it possible to say that PIT should use a given [mutator group](https://pitest.org/quickstart/mutators/) with Maven? Or the only way to include them is to define each of them individually, as such?

```xml
<configuration>
    <mutators>
        <mutator>NON_VOID_METHOD_CALLS</mutator>
        ... all others ...
    </mutators>
</configuration>
```

**Comment by hcoles** [comment]
You can activate a group using its name in the same manor as an individual mutator

```xml
<configuration>
    <mutators>
        <mutator>DEFAULTS</mutator>
        <mutator>NON_VOID_METHOD_CALLS</mutator>
    </mutators>
</configuration>
```

And deactivate mutators or groups using a leading '-'

```xml
<configuration>
    <mutators>
        <mutator>STRONGER</mutator>
        <mutator>-MATH</mutator>
    </mutators>
</configuration>
```

**Comment by AlexandruGG** [comment]
Thank you!
