### ISSUE TITLE
test case for mutants failing at @BeforeAll or @AfterAll method reported "pass" in Pitest

### ISSUE THREAD

**Issue by qinfendeheichi** [hcoles/pitest#1026]
When I tried making test cases fail at BeforeAll and AfterAll methods, I found that mutants are reported survived while the test case actually failed.
The problem could be reproduced by the following code. 

```
class Person{

    public int computeAge1(){
        int age = 4;
        age = age*2;
        return age;
    }

}
```

```
public class PersonTest {

    @BeforeAll
    public static void doBeforeAll(){
        System.out.println("BeforeAll enter");
        Person p = new Person();
        int result = p.computeAge1();
        if(result==2){
            fail();
        }
        System.out.println("BeforeAll exit");
    }

    @Test
    public void test1(){
        System.out.println("test1 enter");
        assertTrue(true);
        System.out.println("test1 exit");
    }
}
```

Pit configuration is below for maven project

            <plugin>
                <groupId>org.pitest</groupId>
                <artifactId>pitest-maven</artifactId>
                <version>1.8.0</version>
                <dependencies>
                    <dependency>
                        <groupId>org.pitest</groupId>
                        <artifactId>pitest-junit5-plugin</artifactId>
                        <version>0.15</version>
                    </dependency>
                </dependencies>
                <configuration>
                    <fullMutationMatrix>true</fullMutationMatrix>
                    <outputFormats>
                        <outputFormat>XML</outputFormat>
                        <outputFormat>HTML</outputFormat>
                    </outputFormats>
                    <exportLineCoverage>true</exportLineCoverage>
                    
                    <timestampedReports>false</timestampedReports>
                    <verbose>true</verbose>
                    <detail>true</detail>
                </configuration>
            </plugin>

The math mutator mutates multiplication to division, thus trigger "fail()" executed in BeforeAll method
In pit, beforeAll is executed for each test case method while I do not understand why such failure is not reported as failure. It seems that test dependency is not encouraged and such statements should've been put into beforeeach method.

I would really appreciate it if you could help solve my confusion

**Comment by hcoles** [comment]
@qinfendeheichi If you package this up as a complete executable project I'll take a look.

**Comment by hcoles** [comment]
@qinfendeheichi thanks for reporting this, and for the minimal project.

It looks to be a bug in the JUnit5 plugin. Tests with failing BeforeAlls look to be identified as "containers" rather than tests by jupiter, and seem to fail without registering as starting.

I've opened an issue against the plugin to track the problem.

https://github.com/pitest/pitest-junit5-plugin/issues/64

I should have a fix shortly.
