### ISSUE TITLE
HeadlessException when running tests that open frames

### ISSUE THREAD

**Issue by jzy3d** [hcoles/pitest#1033]
Due to https://github.com/hcoles/pitest/pull/601, PIT starts child process in headless mode. This prevent from running unit tests that use Swing/AWT, which I do a lot for building integration tests in a [2D/3D charting framework for Java](https://github.com/jzy3d/jzy3d-api).

The flag to allow opening UIs is 

`mvn test-compile org.pitest:pitest-maven:mutationCoverage -DjvmArgs=-Djava.awt.headless=false`

**Comment by hcoles** [comment]
This will work differently in pitest 1.9.3. once #1054 is merged.

headless=true will only be added when running on osx. Auto adding of the jvm arg can be disabled with -Dfeatures="-macos_focus"
