### ISSUE TITLE
[Question] Test execution is taking considerably longer than expected

### ISSUE THREAD

**Issue by ThomGeG** [hcoles/pitest#1039]
Hey all,

I'm trying to add pitest to an application for work so we can use mutation testing to help ensure test quality, but I'm hitting some snags on the performance front. There's about some 300 'unit' tests currently in the project that usually take ~3 minutes to run, but when pitest is using them to calculate code coverage they take some 15 minutes (and then roughly an hour to do the mutation analysis itself, with quite a few timeouts).

I'm wondering if there's anyone more experienced with pitest able to offer me anything to help find why there's such a vast time discrepancy between running the tests normally vs. running them as a part of pitest, as based on a previous (simpler) project of mine it only took 2x as long to calculate coverage.

It's a Spring application, so the majority of the tests themselves are starting up the full Spring application context which includes an embedded MongoDB test server. I've tried doing some debugging of my own, but I haven't found anything to actually suggest why pitest takes 5x as long to execute them compared to normal JUnit 4; the memory limits are the same and the hotspots are in all the same places. Everything simply just seems to be slower.

Unfortunately I won't be able to share the project, but I'm currently running on a Windows machine, using OpenJDK 11, & pitest 1.7.4 via the gradle plugin (although I've also tried 1.8.0 directly from the command line and it's the same result).

Any tidbits provided would be appreciated, as I'm looking to avoid incremental analysis since the major motivation right now is finding gaps in our existing test suite and plugging them. Cheers

**Comment by hcoles** [comment]
Hi @ThomGeG.

There is a performance bug in the coverage system at the moment which will be fixed soon

https://github.com/hcoles/pitest/pull/1035

This is mainly around memory consumption however, and the fix is not likely to greatly improve time performance unless GC has become excessive for your project.

Unfortunately, without access to a project that reproduces the issue, it's impossible to say what cause might be. There are lots of seperate factors that determine performance. However, the fact that your tests are heavyweight (spring and mongo) is almost certainly a factor. If you can pull out a minimal executable example of what these tests look like, I can take a look and see if the way pitest breaks tests up can be improved for them.

**Comment by ThomGeG** [comment]
Cheers @hcoles 

GC activity seems fine for the project, as I've previously hooked the CoverageMinion up to JProfiler and can see only small blips every so often. I've also given it 7GB to play with to be sure, but nothing changed.

Today I've had a go at trying to isolate the problem to something I'd be able to share, but haven't had any luck in reproducing it. I specifically took a random Spring project from GitHub ([AlexMotaOliveira/pokedex](https://github.com/AlexMotaOliveira/pokedex)) that uses Spring, Lombok, and an embedded MongoDB server and applied pitest to it to see if I could get any similar results, but alas.

My only instinct is there must be an overhead somewhere when calculating the code coverage unique to pitest and its need to know specifically _which_ tests executed something for the heuristic that simpler tools like JaCoCo presumably don't share. Then due to the moderate size of the project I'm trying to add pitest to, this is the first time I'm noticing it.

I might close this issue off and wait for that performance issue fix in the hopes there was some expensive operation with a lot of invocations hidden away somewhere within, then invariably return to scratching my head when there wasn't. 

Thanks for the help
