### ISSUE TITLE
Maven plugin: skip module

### ISSUE THREAD

**Issue by alexec** [hcoles/pitest#106]
It'd be good to be able to skip a single module when doing a multi-module build. E.g. if it has no tests.

**Comment by twillouer** [comment]
Hi, thanks for this work.

Can you add the 'skip' flag on your documentation (http://pitest.org/quickstart/maven/) (or give me the right link where I can submit a PR).

**Comment by hcoles** [comment]
@twillouer 

You can create a PR against

https://github.com/hcoles/pitest-site

thanks.
