### ISSUE TITLE
Mutating non-existing lines in Kotlin?

### ISSUE THREAD

**Issue by caay2000** [hcoles/pitest#1060]
As you can see in the following image, seems that PiTest is mutating lots of lines that are not really in my Kotlin file... from 29 to 54...

![image](https://user-images.githubusercontent.com/16318775/180329237-408c50f9-268e-4799-b50d-0d2112adfdf5.png)

This is my pitest configuration in gradle

```
pitest {
    pitestVersion.set("1.9.3")
    junit5PluginVersion.set("1.0.0")
    targetClasses.add("com.github.caay2000.ttk.*")
    excludedMethods.addAll("toString")
    excludedTestClasses.add("**.*IntegrationTest")
    outputFormats.addAll("XML", "HTML")
    avoidCallsTo.add("kotlin.jvm.internal")
    mutators.addAll("STRONGER", "EXTENDED")
    detectInlinedCode.set(true)
    threads.set(4)
    failWhenNoMutations.set(false)
    dependencies {
        pitest("com.groupcdg.pitest:pitest-accelerator-junit5:1.0.0")
        pitest("com.groupcdg.pitest:extended-mutators:0.1.2")
        pitest("com.groupcdg.pitest:pitest-kotlin-plugin:0.1.1")
    }
}
```

You can check the code repository at https://github.com/caay2000/transport-madness-kata/tree/exercise-1
(_Note this is the exercise-1 branch, not the master one_)

**Comment by hcoles** [comment]
Hi @caay2000 

Thanks for the report. The non existant lines are a result of calls to inlined functions in arrow.core.Either. The body of these functions are copied into the bytecode of the class by the kotlin compiler.

We're working on a soloution for this.

**Comment by hcoles** [comment]
@caay2000 

Just tried the inlined code filtering we've been working on out against this file, and pleased to say it works as expected. We'll release it early next week.

**Comment by hcoles** [comment]
@caay2000 Since its passed all out internal tests, we've released 0.1.2 of the kotlin plugin today. It will filter out mutants in code from most inlined functions. There are some cases where the inlined code doesn't seem to come with SMAP data which we are still trying to understand/find a soloution for.

**Comment by caay2000** [comment]
Amazing, thanks @hcoles 🎉

**Comment by caay2000** [comment]
It is working perfectly!

<img width="701" alt="image" src="https://user-images.githubusercontent.com/16318775/180463510-81845c05-9e6e-49e8-89e0-ab03bf966ec4.png">

Is it possible to have some change on the timestampedReports property? 🤔  with the same configuration I posted above (_just changing the kotlin-plugin to 1.2_) my report was published in a timestamped directory

**Comment by hcoles** [comment]
@caay2000 timeStampedReports has always defaulted to true (it probably shouldn't, but that's the way it's always been). If you don't explicitly set it to false reports will be timestamped. That was the behaviour of the exercise-1 branch when I checked it out.

I'm not clear on why you weren't seeing timestamped reports before, but that is not a change introduced by the kotlin plugin.

**Comment by caay2000** [comment]
ok, my fault then 🤦🏼‍♂️

From my side, this issue could be closed! Thanks!
