### ISSUE TITLE
[Feature request] coverageThreshold  and mutationThreshold for report report-aggregate

### ISSUE THREAD

**Issue by knysh** [hcoles/pitest#1068]
**Prerequisites**: 
I have a multi module maven project and I aggregate the report using report-aggregate.
mutationThreshold and coverageThreshold are different for all modules.
e.g. 
mod0 coverage: 10%
mod1 coverage: 50%
mod2 coverage: 100%
general coverage: 53%

**Steps**:  
1. Common mutation report is okay and contains general percentages of coverage
2. I would like to pass mutationThreshold and coverageThreshold 

**actual result**: For now, I need to add threshold to each module to build project correctly
**expected result**: I would like to check only general coverage by passing thresholds to general or  report-aggregate pom.xml

**Comment by Pfoerd** [comment]
I have a similar issue. I'm currently over a PR to let `ReportAggregator` return a result object with aggregated coverage metrics and add thresholds form them in the pitest-maven aggregator mojo. Then one can configure thresholds in the parent pom.xml for the aggregated coverages. I plan to raise the PR in the upcoming 2 weeks so stay tuned :)
