### ISSUE TITLE
Add org.jboss.logging to default excluded logging classes for use in Quarkus applications

### ISSUE THREAD

**Issue by mdlcosine** [hcoles/pitest#1074]
As Quarkus applications use the org.jboss.logging classes, these should be included in the default excluded classes.

I tried to create a branch with a PR for it, but I didn't have the rights to do so. 

I suppose this snippet can be put in org.pitest.mutationtest.config.ReportOptions which will fix this issue.
```java
public static final Collection<String> LOGGING_CLASSES                = Arrays
      .asList(
          "java.util.logging",
          "org.apache.log4j",
          "org.apache.logging.log4j",
          "org.slf4j",
          "org.apache.commons.logging",
          "org.jboss.logging");
```

**Comment by hcoles** [comment]
Thanks @mdlcosine, it will be in the next release.
