### ISSUE TITLE
[New mutant request]: Mutant to nullify a function's parameters

### ISSUE THREAD

**Issue by kamesh95** [hcoles/pitest#1076]
I have checked the "ALL" group for mutators available for pitest but was unable to find a mutator that actually detects any potential null pointer exceptions. For example, in the below code if the method is called with null arguments `welcome(18, null)`, it throws NPE, however my mutation score still shows up 100% even though I don't write any test cases for the null scenarios.

```
public class Test {
    enum Gender {
        MALE, FEMALE;
    }

    public boolean welcome(int age, Gender gender) {
       out.print(gender.toString()); // this line can throw null pointer exception if gender is null
       if (gender == Gender.FEMALE) {
           return age >= 18;
       }
       return age >=21;
    }
}
```

I think if we can add a mutant to mutate function parameters to null values, it can help detect NPEs in many such scenarios. Maybe this can also be extended to any local variables inside the function that are dependent on values from other functions. Thanks.

**Comment by rnveach** [comment]
Not a maintainer of this repo, but...
> if the method is called with null arguments welcome(18, null), it throws NPE, however my mutation score still shows up 100% even though I don't write any test cases for the null scenarios.
> we can add a mutant to mutate function parameters to null values, it can help detect NPEs in many such scenarios

As I understand, exceptions are seen a test failure and all pitest is doing is looking for a test to not pass with the mutant to say the mutant was killed.

I don't think forcing an exception here will do what you want in this case which is to decrease the mutation percentage.

I think this type of mutation will only show if the parameter has a test for it's usage, or if the parameter is not used at all.
