### ISSUE TITLE
Whether multiple mutants will affect each other when using H2 database memory mode

### ISSUE THREAD

**Issue by wlopper** [hcoles/pitest#1089]
The project I am developing uses the memory mode of the H2 database. 
For historical reasons, some tests fail to return the database to its previous state after execution. For example, an order data is left in the order table after a use case is executed. I want to know whether pitests affect each other when executing variants.
look forward to your reply.

**Comment by rnveach** [comment]
Not a maintainer and just my opinion. I use an in-memory database for my project and don't have any issues with the database itself, but really it depends more on your exact test suite and how things are specifically handled. I would say it comes more down to test dependability than the database.

Unless you are completely rebuilding the database from scratch for each test, your tests don't feel repeatable (no matter how many times or what order they run, they will always produce the same results) if you are leaving data in your tables and never doing any cleanup.

Imagine you have a test that verifies inserting 1 order and a test that verifies selecting an empty table of orders, very basic tests. Each one may run fine alone, running selecting first and then inserting will probably run fine too, but running insert first and then select may produce unpredictable results. The select is expecting an empty table, but the insert ran first and left data in the table to be seen by the select test. Also if your 1 order insert verifies 1 order is in the table, multiple runs of it alone will fail the verification as each run keeps increasing the number of orders in the table and your size verification will fail. Pitest basically requires all tests to be be completely isolated and mostly run in any order, any number of times. You must be able to start the test from scratch while the same JVM and memory is used from the prior run. I foresee pitest needing the table being cleaned up each test run, and this is exactly what my project does. I have to even go and clear out cache and result any variables that the test could change. If you don't do this, then you will never get stable pitest results.

Your suite of tests must always be green for each run even without pitest.
If you have random test failures, where a suite of tests pass one time, and then on a completely separate run without any code changes, fail another, then you will have unstable results with pitest.
If you have a single database instance throughout the entire suite run, you will probably not be able to do any multi-threading with pitest, especially if your database needs to be in a specific state before a test run.
I mentioned your tests needs to be repeatable with any number of runs and test ordering. If you use something that ensure tests and test classes are run in true random order, than it is probably better for pitest as this should show over time there is no order dependency between tests. You won't get a sense of this with just 1 run, but after thousands, it will show more reliability.

**Comment by wlopper** [comment]
Thank you for your reply!

It is also my hope to return the environment to the same situation before executing any mutation test. Unfortunately, there are many missing data in the project I am responsible for due to historical reasons, and there are more than 6000 test cases in the whole project, so it is very difficult to modify them all.

In addition, if using the same database makes it impossible to use multiple threads to execute the mutation test, this will lead to some huge feature mutation test problems. After my test, 15000 new lines are added to a feature, and it takes a total of 3 hours to execute the mutation test with two threads. Although it is recommended to use withHistory to improve the efficiency, it still takes too long, This is why I hope to execute in parallel through multiple threads.

The test case is indeed green and it can pass Jacoco tests, but there is legacy data when the database rolled back, and these legacy data will not affect the test results of other use cases, which is also the reason for this embarrassing situation

Recently, I have also been investigating how to return the H2 database to a fixed state. Maybe the situation will improve at that time.

it's my project reasons，Not related to mutation test，i will close the issue . thank you!
