### ISSUE TITLE
Source for classes in default package not located

### ISSUE THREAD

**Issue by hcoles** [hcoles/pitest#11]
_From [henry.co...@googlemail.com](https://code.google.com/u/110593770751416093310/) on September 25, 2011 22:15:43_

The source for classes in default package is never located, resulting in an html report without annotated lines for these classes.

_Original issue: http://code.google.com/p/pitestrunner/issues/detail?id=11_

**Comment by mrTsjolder** [comment]
I recently used the intellij plugin on a school-example where the project consisted only of a class and an exception in my "sources root" and a junit-test in the "test sources root" and I was unable to get pitest to work with it until I put them in a package.

It might have been that the documentation was not clear enough or that I missed some part, but I did not find anything on how the target classes should exactly be specified (i.e. is it possible to use path to class-files, class-names, ...). I supposed it needs the syntax that is also used for import statements (mainly derived from the few examples I could find), but that is not really applicable for default packages. On the other hand when I tried `*` as a filter, I got this nice little error message...

![screen shot 2016-04-12 at 11 49 36](https://cloud.githubusercontent.com/assets/3738082/14462453/6cf06452-00c7-11e6-8411-dd9d20612e6e.png)

In my opinion this could be easily solved by improving the documentation (maybe also with extra examples).
