### ISSUE TITLE
How can I get the extended version of PIT offers an additional option the generation of test matrix?

### ISSUE THREAD

**Issue by pzzpl** [hcoles/pitest#1101]

**Comment by pzzpl** [comment]
Recently I have been doing experiments related to mutation testing and need to use the extended version of PIT to obtain the mutation matrix. However, there is no extended version of PIT, which is mentioned in the PIT paper. How do I get this extended version?

**Comment by hcoles** [comment]
Full matrix mode was introduced in pitest 1.5.2, enabled with the `fullMutationMatrix` parameter. It is an only partially supported feature, other pitest features are not guaranteed to work if it is enabled.

If the paper you are refering to is the one from UCD, the `pit-rv` mutation operator extensions are available as a plugin 

https://github.com/pitest/pitest-rv-plugin

If it is a different paper, you would need to contact the authors to request their modified version.
