### ISSUE TITLE
Some Class Skipped Mutation Test

### ISSUE THREAD

**Issue by wlopper** [hcoles/pitest#1102]
I encountered a puzzling problem，I use pitest with maven and configure as follows：

`            
<plugin>
                <groupId>org.pitest</groupId>
                <artifactId>pitest-maven</artifactId>
                <version>1.9.8</version>
                <dependencies>
                    <dependency>
                        <groupId>org.pitest</groupId>
                        <artifactId>pitest-testng-plugin</artifactId>
                        <version>1.0.0</version>
                    </dependency>
                </dependencies>
                <configuration>
                    <threads>1</threads>

                    <verbose>true</verbose>

                    <timeoutConstant>60000</timeoutConstant>

                    <include>MODIFIED,ADDED,UNKNOWN</include>
                    <connectionType>connection</connectionType>
                    <originBranch>HEAD</originBranch>
                    <destinationBranch>origin/master</destinationBranch>

                    <excludedClasses>
                        <excludedClass>com.xxx.m2m.cmp.global.xxx.*.entity.*</excludedClass>
                        <excludedClass>com.xxx.m2m.cmp.global.xxx.*.dto.*</excludedClass>
                        <excludedClass>com.xxx.m2m.cmp.global.xxx.*.vo.*</excludedClass>
                        <excludedClass>com.xxx.m2m.cmp.global.xxx.constant.*</excludedClass>
                        <excludedClass>com.xxx.m2m.cmp.global.xxx.config.*</excludedClass>
                    </excludedClasses>

                    <withHistory>false</withHistory>

                    <mutators>
                        <mutator>CONDITIONALS_BOUNDARY</mutator>
                        <mutator>INCREMENTS</mutator>
                        <mutator>INVERT_NEGS</mutator>
                        <mutator>MATH</mutator>
                        <mutator>NEGATE_CONDITIONALS</mutator>
                        <mutator>VOID_METHOD_CALLS</mutator>
                        <mutator>FALSE_RETURNS</mutator>
                        <mutator>TRUE_RETURNS</mutator>
                        <mutator>NULL_RETURNS</mutator>
                        <mutator>PRIMITIVE_RETURNS</mutator>
                    </mutators>

                    <avoidCallsTo>
                        <avoidCallsTo>java.util.logging</avoidCallsTo>
                        <avoidCallsTo>org.apache.log4j</avoidCallsTo>
                        <avoidCallsTo>org.slf4j</avoidCallsTo>
                        <avoidCallsTo>org.apache.commons.logging</avoidCallsTo>
                        <avoidCallsTo>com.xxx.m2m.xxx.base.utils</avoidCallsTo>
                    </avoidCallsTo>

                    <failWhenNoMutations>false</failWhenNoMutations>
                </configuration>
            </plugin>
`
and the result as follows:
![image](https://user-images.githubusercontent.com/54232090/198532296-69c81942-c130-4eb3-9614-3af7bec5ab50.png)
we can see the package facade and workorder.impl nearly no line coverage. 
But there is no difference between the test classes and others.
So, I wondered how did this happen

**Comment by wlopper** [comment]
I found the log has some Test Skipped:
![image](https://user-images.githubusercontent.com/54232090/198535146-7077296d-3ded-4b30-88dd-6bfae82d028a.png)

**Comment by hcoles** [comment]
If you create a minimal project that recreates the issue I can take a look.

**Comment by wlopper** [comment]
@hcoles I found that spring was started many times in the log, and I found that spring failed to start because of port occupation. Why is it designed this way? Is there any solution? looking forward for your answer

**Comment by hcoles** [comment]
It is not possible to debug without access to your code and tests.

If you create a minimal project the recreates the issue I can take a look.

**Comment by hcoles** [comment]
@wlopper Are you able to supply a minimal project that reproduces the problem, or should I close the issue?

**Comment by wlopper** [comment]
sorry. i have no time to prepare a minimal project. during this time， i found it skipped many tests because there are some problem. like mock port resource not released；some LLT cases became failure (this confuzed me , because when I run  cases from testng , it's green, so i wondered what's the difference between these two ways . sorry for too busy to reply recently. i will close this issue and try to fix cases

**Comment by wlopper** [comment]
![image](https://user-images.githubusercontent.com/54232090/200556599-b4334d35-6612-4db9-9f93-02619cfc1b24.png)
one of the errors，and the behind test are skipped。
![image](https://user-images.githubusercontent.com/54232090/200556884-a20a7f43-f6a6-4d5d-8c2a-208f799e5133.png)
