### ISSUE TITLE
Ignore private constructors?

### ISSUE THREAD

**Issue by Manfred73** [hcoles/pitest#1104]
I came accros this [posting](https://stackoverflow.com/questions/72317134/is-it-possible-to-exclude-methods-from-pit-coverage-calculation)  which suggests to add tests for private constructors using reflection.

I'm using Lombok and @UtilityClass which generates the private constructors.

One could argue if you should test these or not (I'd rather not test these). Is there a way to indicate PITest should ignore private constructors?

**Comment by hcoles** [comment]
If the constructor contains no functionality, pitest will not mutate it. Currently pitest does not support filtering out code from coverage, so the constructor will be reported as having no line coverage, but no mutants will be seeded.

If the constructor contains functionality which is autogenerated by Lombok, pitest will not mutate it, so long as Lombok is configured to add a @Generated annotation.

**Comment by Manfred73** [comment]
If I understand correctly, when using lombok's @UtilityClass, lombok will add a private constructor which throws an UnsupportedOperationException.

I have lombok configured to add `@Generated`:
```
lombok.addLombokGeneratedAnnotation = true
```

I can see that the compile class has the annotation `@Generated`:
```
public final class UUIDUtil {
    public static String randomUUID() {
        return UUID.randomUUID().toString();
    }

    @Generated
    private UUIDUtil() {
        throw new UnsupportedOperationException("This is a utility class and cannot be instantiated");
    }
}
```
But when I remove the constructor test, PItest reports coverage < 80%. When I add the constructor test, coverage is 80%.

**Comment by hcoles** [comment]
The @Generated annotation prevents pitest from mutating the code, it does not stop it from recording its coverage.

**Comment by hcoles** [comment]
There is no mechanism at the moment. Pitest is a mutation testing system, coverage is only collected as a means of optimising the mutation analysis.

**Comment by Manfred73** [comment]
OK, another thing I notice: PITest fails because line coverage is 79% and the maven plugin is set to cover 80%.
The HTML report shows 100% line coverage (11/11):
![image](https://user-images.githubusercontent.com/13829887/200362277-74027495-7308-4e6e-ac75-6f144bbd3d90.png)

But the maven command fails and shows different output 79% line coverage (11/14).
![image](https://user-images.githubusercontent.com/13829887/200362577-de3167ec-e1a7-47d0-b782-a605d578c923.png)

So I'm not sure what is being missed.

**Comment by Manfred73** [comment]
Found what was causing the difference: I've excluded *Application (the spring boot application) in the maven plugin. Now CLI and HTML report show the same output. Not sure why the HTML report was ignoring this in the first place and the CLI didn't.
