### ISSUE TITLE
Aggregator resolves wrong files when they have the same filename (Kotlin)

### ISSUE THREAD

**Issue by Pfoerd** [hcoles/pitest#1105]
**Describe the bug**
The Aggregator doesn’t resolve filenames correctly when there are Kotlin files with the same filename in multiple subprojects. In the pitest reports of the submodules everything is correct and the filenames are resolved correctly but in the aggregated report the files are not assigned correctly. It displays the wrong file from another submodule.

**To Reproduce**
1. Multi-Module Kotlin Setup
2. Run Pitest for all Submodules
3. Run ReportAggregator

**Expected behavior**
All files are resolved correctly in the aggregated report

**used version:**
1.9.8

**Comment by hcoles** [comment]
I've merged a change that will ensure the correct file is used when two modules have files with the same name that define classes in different packages, but the files are not within directories matching those packages. 

If the same package is used in both modules, it is not clear what a "correct" behaviour would be so this scenario is not supported.
