### ISSUE TITLE
Do not replace Map.of() by Collections.emptyMap()

### ISSUE THREAD

**Issue by C-Otto** [hcoles/pitest#1106]
My code always returns an empty map, implemented using `Map.of()`. When running pitest, this is mutated to return `Collections.emptyMap()` instead. As I don't have any test that would be able to see the difference, this mutation survived.

Please treat `Map.of()` the same as `Collections.emptySet()`, i.e. do not try to mutate one into the other.

Version 1.9.9.

**Comment by hcoles** [comment]
The EquivalentReturns filter already catches List.of and Set.of, not sure why Map.of was missed. Will be fixed in the next release.

**Comment by C-Otto** [comment]
You added the "Collections.emptyMap()" return value in 89b0c2c68d89b6fe7fe7dd12858d68fef15d4694, after `Set.of()` and `List.of()` were already known as "empty" equivalent.

**Comment by hcoles** [comment]
Released in 1.9.10
