### ISSUE TITLE
[QUESTION] Are these AssertJ mutations expected?

### ISSUE THREAD

**Issue by igorwojda** [hcoles/pitest#1117]
I am trying to understand what is the expected behavior of the PIT. 

1. Is it ok that both classes (class under test and class containing tests) are detected by PIT?
![image](https://user-images.githubusercontent.com/530122/203090117-3bd8bd4a-8e8b-449c-8157-b659fc95d237.png)

2. Is it ok that the assertion call was removed during mutation generation? 
![image](https://user-images.githubusercontent.com/530122/203090375-fded7d61-a6d0-420d-a12d-c372ae4af0b0.png)

Looking at the above
1. Don't we want only to mutate tested classes?
2. What is the point of mutating test classes? What is the point of removing test assertions? (this will always make the test pass, so some mutations will always survive)

**Comment by hcoles** [comment]
Pitest should not be mutating tests. How are you running it (maven/gradle/other)? How is your project structured?
