### ISSUE TITLE
Missing AOR mutators

### ISSUE THREAD

**Issue by claudeyj** [hcoles/pitest#1119]
Hi,
I'm a student researcher working on mutation testing and program repair. I find that there seems to be some inconsistency between your defined mutators and their implementation. For example, in the home page of Pitest, there's a group of **AOR** mutators, claiming that Pitest can transform operators like "+" to "-", "*", "/" and "%". However in the process of mutation testing I found that Pitest only support "+" -> "-" mutations. I checked the source code and found only a subset of the claimed mutators have been implemented, see https://github.com/hcoles/pitest/blob/70982dbc46000825308cdd4d299839e9655cac61/pitest/src/main/java/org/pitest/mutationtest/engine/gregor/mutators/MathMutator.java#L123 and 
https://github.com/hcoles/pitest/blob/70982dbc46000825308cdd4d299839e9655cac61/pitest/src/main/java/org/pitest/mutationtest/engine/gregor/mutators/MathMutator.java#L62
This could affect mutation testing (and program repair based on that) research so I wonder whether you can confirm that. Plus, I can put a pull request to fix this inconsistency if you agree with that.
Thank you very much for your time!

**Comment by LaurentTho3** [comment]
Hello,

Since version 1.7.5 some mutators, including AOR, have been moved out of pitest and into a plugin as they were causing some confusion. Using this plugin https://github.com/pitest/pitest-rv-plugin you can access these mutation operators.

Hope that helps.

**Comment by claudeyj** [comment]
Thanks a lot! You've been very helpful.

**Comment by d-led** [comment]
what about gradle of those mutators?

**Comment by hcoles** [comment]
@d-led The plugin can be added to gradle builds.

See "Generic plugin support" in

https://gradle-pitest-plugin.solidsoft.info/

**Comment by d-led** [comment]
@hcoles sorry, I still couldn't find how the `AOR` mutator group could be added with the new pitest-rv-plugin. I'm using the 1.15.0 gradle plugin but still no `AOR`: https://github.com/d-led/java-testing-the-tests/blob/speculative-pitest-upgrade/app/build.gradle#L9-L48

**Comment by hcoles** [comment]
Where in the linked build file do you install the pitest-rv-plugin?

**Comment by d-led** [comment]
> Where in the linked build file do you install the pitest-rv-plugin?

I tried it in the testImplementation section but that had no effect. Where should it be installed to? I presume, it can't simply work with gradle as it's a maven plugin. Correct?

**Comment by hcoles** [comment]
Have you read the "Generic plugin support" section of the page I linked to earlier?

**Comment by d-led** [comment]
Oh, sorry, I've missed one line. 

```groovy
dependencies {
    pitest 'org.example.pit.plugins:pitest-custom-plugin:0.42'
}
````
this?
