### ISSUE TITLE
No mutations are created when the project path has spaces

### ISSUE THREAD

**Issue by theangrydev** [hcoles/pitest#112]
When there are spaces in the path to the Maven project, no mutations are created, however the test coverage is computed correctly.

**Comment by GrzesiekP** [comment]
I've had the same error, when my jenkins job name contained braces ():

```
Execution mutation-coverage-goal of goal org.pitest:pitest-maven:1.1.4:mutationCoverage failed: No mutations found. This probably means there is an issue with either the supplied classpath or filters.
```

**Comment by hcoles** [comment]
@GrzesiekP Can you confirm if you can reproduce the issue by following these steps -> https://github.com/hcoles/pitest/issues/112#issuecomment-64928889

If this does not reproduce, could you provide a set of steps that does?

Thanks

Henry

**Comment by GrzesiekP** [comment]
The issue started appearing when I changed my Jenkins job name to contain braces. This caused the workspace where the project is sored to contain braces. 

But I followed the steps similiar to what you listed and it appears on my local machine:
1. Clone to dir with braces ().
2. cd
2. mvn clean package (mutationCoverage is tied to test phase)

**Comment by maxgabut** [comment]
This issue has been inactive for a while.
@theangrydev, do you (or anyone else) think this is still an issue with the current version ?
If not, or if no one speak up in a month, this issue will be closed.

**Comment by maxgabut** [comment]
I'm closing this issue because it has been inactive for a long time.
