### ISSUE TITLE
pitest incorrectly included unmodified classes 

### ISSUE THREAD

**Issue by wlopper** [hcoles/pitest#1120]
I use pitest to perform incremental tests on the code, and perform incremental file mutation tests by comparing the master branch with the development branch.

Now I come across a case where pit incorrectly generates variants of my unmodified files through regular matching.

The situation is as follows：

test report：
![image](https://user-images.githubusercontent.com/54232090/203939488-2dc9f6fb-6ca6-4580-bd32-7d0b4be82d09.png)

logs:

I only modified the SupplierSettlement class, but pitest also mutated the SupplierSettlementCsv file.
Is this the design?

besides, I found that as long as one method in the file is changed, the entire file will be subject to mutation testing. This is a little different from the way that jacoco only covers the modified lines. Is there a solution?

**Comment by wlopper** [comment]
the logs as follows:
`Will mutate changed class com.xxx.xxx.xxx.xxx.xxx.xxx.xxx.SupplierSettlement*`

**Comment by hcoles** [comment]
Without more details of the code it is impossible to say what is happening here, but the decision as whether to treat a class as having potentially changed behaviour is not straightforward.

From the documentation

https://pitest.org/quickstart/incremental_analysis

> The main issue is that class behaviour is defined not only by its bytecode, but also by its dependencies (i.e the classes it interacts with and the graph of classes that they interact with). PIT will only consider the strongest of these dependencies - changes to super classes and outer classes, when deciding if a class’s behaviour might have changed.

**Comment by wlopper** [comment]
Thank you for your reply!

It is really difficult to determine whether a class has changed, but I doubt that the SupplierSettlementCsv class is reported due to this log:`Will mutate changed class com.xxx.xxx.xxx.xxx.xxx.xxx.xxx.SupplierSettlement*`

Pitest not only matches the methods in the class SupplierSettlement, but also matches the class SupplierSettlementCsv。

This reminds me of the targetClasses tag，If you configure`com.demo.*.entity.*`,  then pitest will mutate all matches Classes,  even package `com.demo.job.module.entity.TestClasses` . In other words, `*` matches multiple directories.

**Comment by hcoles** [comment]
Appologies, I had assumed you were using pitest's incremental analysis feature, but rereading the issue it looks like you are using the maven `scmMutationCoverage` goal.

This is rather basic and may indeed be overmatching. I'd recomend you consider using the Arcmutate git integration instead

https://docs.arcmutate.com/docs/git-integration.html

**Comment by wlopper** [comment]
sorry. It must be my poor English that made you misunderstand.
thank you. I will try Arcmutate！
