### ISSUE TITLE
First line of nested class declared as not covered

### ISSUE THREAD

**Issue by Stephan202** [hcoles/pitest#1123]
Pull request PicnicSupermarket/error-prone-support#378 upgrades Pitest from version 1.9.11 to version 1.10.0. When comparing the coverage report before and after the upgrade, we see one _tiny_ difference, visible in the screenshots [shown here](https://github.com/PicnicSupermarket/error-prone-support/pull/378#pullrequestreview-1198857024).

To reproduce:
```sh
git clone git@github.com:PicnicSupermarket/error-prone-support.git
cd error-prone-support
./run-mutation-tests.sh
firefox error-prone-contrib/target/pit-reports/tech.picnic.errorprone.bugpatterns/FormatStringConcatenation.java.html
git checkout origin/renovate/org.pitest-pitest-maven-1.x
./run-mutation-tests.sh
firefox error-prone-contrib/target/pit-reports/tech.picnic.errorprone.bugpatterns/FormatStringConcatenation.java.html
# Now, compare the results.
```

Since highlighting the line in red doesn't seem actionable, I assume this is a minor regression; thought I'd share :)

Thanks for the great software!

**Comment by hcoles** [comment]
@Stephan202 Thanks for reporting this. The release didn't contain any changes to the coverage system, but it did rework how lines of code are recognised. I'll take a look as soon as possible to see what's changed.

**Comment by hcoles** [comment]
From a scan through, I think pitest might be incorrectly including a line from a synthetic bridge method.

**Comment by hcoles** [comment]
1.10.1 has just been released and should be available from maven central shortly. Thanks again for reporting.

**Comment by Stephan202** [comment]
@hcoles thanks for the quick turnaround!

I just found some time to try the new upgrade, and it appears that this change comes with some unintended side-effects: some lines that are covered, are now no longer reported as such. As a side-effect some files have >100% line coverage. I summarized the observations in https://github.com/PicnicSupermarket/error-prone-support/pull/378#issuecomment-1336363217. (Let me know if I should file a separate issue instead.)

**Comment by hcoles** [comment]
I have a feeling this will be because I excluded synthetic methods along with bridge methods. There are some corners where they are created by the compiler for use code that I had forgotten about. Will take a proper look tomorrow.

**Comment by hcoles** [comment]
1.10.2 is now released. The behaviour is still different from 1.9.x in that synthetic mehods that are not lambas are excluded as code lines. I am hoping I don't regret that, but I believe it is the correct behaviour as I'm not aware of any other corner cases.

**Comment by hcoles** [comment]
Additional issue identified in the 1.10.x releases where lines that have more than one debug entry in the bytecode were being double counted. 1.10.3 will be the first (hopefully) usable release in the 1.10 series.

**Comment by Stephan202** [comment]
I can confirm that with 1.10.3 the report is strictly more accurate :tada:. I summarized the observed changes in https://github.com/PicnicSupermarket/error-prone-support/pull/378#pullrequestreview-1205912844.

Thanks again for the quick turnaround :)
