### ISSUE TITLE
Maven PIT plugin does not support Maven's late property evaluation in `argLine`

### ISSUE THREAD

**Issue by uhafner** [hcoles/pitest#1131]
In Jenkins plugins we are using [Maven's late property evaluation](https://maven.apache.org/surefire/maven-surefire-plugin/faq.html#late-property-evaluation) to update the `argLine` in our builds. This new Maven feature seems to be not yet supported by PIT's maven plugin: it does not resolve those variables and breaks the build, because the extracted `argLine` is illegal now. 

Created `argLine` from PIT (pitest-maven:1.9.11:mutationCoverage):
```
argLine=-Xms768M -Xmx768M -XX:+HeapDumpOnOutOfMemoryError -XX:+TieredCompilation -XX:TieredStopAtLevel=1 @{jenkins.addOpens} @{jenkins.insaneHook}
```

Error message of PIT:
```
10:05:12 PM PIT >> INFO : MINION : Error: could not open `{jenkins.addOpens}'
```

You can see the full log of the build at https://github.com/jenkinsci/plugin-util-api-plugin/actions/runs/3708263309/jobs/6285636460

**Comment by hcoles** [comment]
@uhafner Thanks, wasn't aware of late property evaluation. Will take a look at what's involved.

**Comment by uhafner** [comment]
Thanks for fixing this so fast!

🎉 🎉 🎉

**Comment by hcoles** [comment]
@uhafner I skimped a little on the integration testing for this one. Let me know if you hit any problems.
