### ISSUE TITLE
false positive on orElseThrow() method.

### ISSUE THREAD

**Issue by GerardSimon77** [hcoles/pitest#1145]
I'm facing a positive false when I use the methode `orElseThrow()` from `java.util.Optional `object.

Pitest replaces the returned value with a null but the `orElseThrow()` method can't return a null value.

![image](https://user-images.githubusercontent.com/120655075/212349586-97f175f3-a4ee-4588-a5dc-1dca42867ec4.png)

I'm currently using version 1.8.1 of Pitest

**Comment by hcoles** [comment]
Pitest has replaced the return value of the lambda defined on 26 with null. The equivalent code would be

```java
opt.orElseThrow(() -> null);
```

While this is not the most useful mutation, it is valid. To detect it you would need to include a test case where `findByHumanResource` returned an empty Optional.

You might be interested in the [arcmutate base plugin](https://www.arcmutate.com/) which improves the descriptions of mutations to lambdas so they are easier to understand.

**Comment by GerardSimon77** [comment]
Thanks you for your quik reply, but I have another question.

In the following example I don't inderstand why Pitest doesn't try some mutation on line 34. For example why it doesn't try to remove this call like it is done for lines 32 and 33 ?

![image](https://user-images.githubusercontent.com/120655075/212380616-c4ab3ea7-763e-4a3b-b868-d8238adf2bf2.png)

**Comment by hcoles** [comment]
Assuming you are using the default operators, the [VOID_METHOD_CALLS](https://pitest.org/quickstart/mutators/#VOID_METHOD_CALLS) mutator will be active, but the [NON_VOID_METHOD_CALLS](https://pitest.org/quickstart/mutators/#NON_VOID_METHOD_CALLS) mutator will not be activated. The call to the save method is therefore not mutated as it returns a value.

You can activate the NON_VOID_METHOD_CALLS mutator, but be aware there is a trade off to be made here. It will generate a relatively large number of mutants and they will often not add much value as they are less stable than the non void ones.
