### ISSUE TITLE
'numberOfTestsRun' is always 0 in the XML output

### ISSUE THREAD

**Issue by JckJhns** [hcoles/pitest#1153]
When executing pitest using the XML output, the 'numberOfTestsRun' for every mutation has been 0.

I am running it with incremental analysis, if that is relevant.

**Comment by hcoles** [comment]
If incremental analysis has detected that no changes have been made for a class, we would expect no tests to be run against it.

If you are seeing no tests being recorded for classes with modifications since the last run, please create a minimal project that recereates the issue.

**Comment by JckJhns** [comment]
Thanks Henry, I retried this with changes and there do seem to be values other than 0. There seems to be no issue here. Appreciate your help.
