### ISSUE TITLE
Unable to run pitest because of command line limit

### ISSUE THREAD

**Issue by vikhil1999** [hcoles/pitest#1154]
We are trying to run mutation scan using pitest for our java repo but pitest fails to run because of command line exceeds operation system limit. We are trying to run pitest on windows machine. 
Can someone please help us on resolving this issue, so that we can run pitest using our windows machine

**Comment by rnveach** [comment]
I am not a maintainer, but I am a Windows user and have not had issues running pitest.

Can you provide your CLI line and a simplified overview of its groups?
Also, you cannot run pitest through maven, or even ant, instead?

For example, I run pitest for my project through Java since I split mine out into simple runs with a lot of the same parameters.Below is all my custom code from different classes. `testMyCustomEmailTimer` is my main test running with the class to run and the simple results to expect. The other method builds the actual pitest command line to run.
````
	@Test
	public void testMyCustomEmailTimer() throws IOException {
		Pitest.main(Pitest.getTimerArguments("MyCustomEmailTimer", 88, 22, 100));
	}

	public static String[] getTimerArguments(String className, int mutationThreshold,
			int survivingMutants, int coverageThreshold) throws IOException {
		final String baseLocation = FileUtil.getWorkingDirectory();

		return new String[] { "--reportDir", baseLocation + "\\caches\\pitest\\" + className, //
				"--mutators", MUTATORS, "--targetClasses",
				"gov.ssa.projectejb.timers." + className + "*", //
				"--targetTests",
				"gov.ssa.projecttest.server.tests.threads." + className + "Test", //
				"--sourceDirs", baseLocation + "\\projectEJB\\ejbModule", //
				"--mutationThreshold", String.valueOf(mutationThreshold), //
				"--maxSurviving", String.valueOf(survivingMutants), //
				"--coverageThreshold", String.valueOf(coverageThreshold), //
				"--threads", String.valueOf(Runtime.getRuntime().availableProcessors()), //
				"--timeoutConst", "60000", //
				"--timestampedReports=false", //
				"--failWhenNoMutations",//
		};
	}
````

**Comment by hcoles** [comment]
@vikhil1999 Pitest provides the `useClasspathJar`. When this is set to true, the classpath string is embedded within a jar manifest, reducing the size of the launch command.

**Comment by vikhil1999** [comment]
@hcoles 
1. Where can i find useClasspathJar
2. How to reducing the size of the launch command.

We configure the pitest in build.gradle and just run "./gradlew pitest". Do you need us to do something else?

**Comment by vikhil1999** [comment]
We tied adding useClasspathJar = true in our pitest config but still it throws the same error
![IMG_20230221_172938](https://user-images.githubusercontent.com/84655743/220339373-f71b4f48-b477-4d7f-a2bc-f4c5ecee4f83.jpg)

**Comment by szpak** [comment]
You can also try `useClasspathFile = true`

**Comment by vikhil1999** [comment]
I tried running pitest with useClasspathFile = true, now build is failing

**Comment by vikhil1999** [comment]
@hcoles @szpak 
Any updates on this issue.

**Comment by hcoles** [comment]
@vikhil1999 Please enable verbose logging and post the output.

**Comment by szpak** [comment]
> Can you please share the command which pitest internally executes when we run ./gradlew pitest.

@vikhil1999 Just add `--info` to see the command.

**Comment by vikhil1999** [comment]
@szpak do you mean something like this "./gradlew pitest --info" . Thanks in advance

**Comment by szpak** [comment]
> @szpak do you mean something like this "./gradlew pitest --info" . Thanks in advance

Yes, in general. However, you seem to use Windows, so rather `gradlew.bat pitest --info`.

**Comment by vikhil1999** [comment]
@hcoles have enabled verbose logging while running the pitest. Whole logs can be found in the pitestlogs.txt file. Sorry for the delayed response
[pitestlogs.txt](https://github.com/hcoles/pitest/files/11025684/pitestlogs.txt)

**Comment by vikhil1999** [comment]
@hcoles any update on this issue

**Comment by hcoles** [comment]
@vikhil1999 The logs do not include any output from pitest, which suggests it has not been succesfully launched from gradle.

Did the configuration have both `useClasspathFile` and `useClasspathJar` set to true?

**Comment by szpak** [comment]
> > Can you please share the command which pitest internally executes when we run ./gradlew pitest.
> 
> @vikhil1999 Just add `--info` to see the command.

@vikhil1999 Have you tried that? It should display both the PIT command line parameters (which seems to be too long) and the output from PIT.

**Comment by hcoles** [comment]
closing as no response since March.
