### ISSUE TITLE
Cannot assign a value to final field 'excludedMethods'  Access to 'excludedMethods' exceeds its access 

### ISSUE THREAD

**Issue by nagkumar** [hcoles/pitest#1183]
![image](https://user-images.githubusercontent.com/332234/228419350-15eeda2e-7665-410b-b9fa-e0698e0dd370.png)

![image](https://user-images.githubusercontent.com/332234/228419393-571424d4-d1b6-41d0-8f80-df12a4a86078.png)

Not sure how to overcome this warning, though assigning this way, pittest works as expected.. may be making these fields non-final in the plugin would help.

**Comment by hcoles** [comment]
This looks to be an issue with the gradle plugin. I suggest you raise this at  https://github.com/szpak/gradle-pitest-plugin

**Comment by szpak** [comment]
@nagkumar To avoid warnings, you can use:

>    excludedClasses.set(["Class1", "Class2"])

It seems to be problem in Idea, as Gradle internally has some logic to keep the old syntax (also for modern `*Property<>` types).

In general, it's better to Gradle-only related issues in the plugin project: https://github.com/szpak/gradle-pitest-plugin/issues
