### ISSUE TITLE
pitest failing when gradle group name is changed

### ISSUE THREAD

**Issue by nagkumar** [hcoles/pitest#1185]
```
pitest {
    junit5PluginVersion = '1.1.2'
    threads = 14
    timestampedReports = true
    mainSourceSets = [sourceSets.main]
    mutators = ['ALL']
    outputFormats = ['HTML']
}
```

Despite mainSourceSets being defined properly, 

when gradle group name changed

![image](https://user-images.githubusercontent.com/332234/229287750-afae655d-d505-413f-b538-03995ca3f366.png)

i.e. changed the name from `com.tejasoft.dsa.bbraces  ` to `com.tejasoft.dsa1.bbraces`

![image](https://user-images.githubusercontent.com/332234/229287796-e9abaf1f-5891-40ba-b3c7-0f68314e038d.png)

It is unable to find.. does pitest has any dependency with gradle group name and I hope group name can be different than actual package name in general though not recommended.

**Comment by hcoles** [comment]
For gradle, when no `targetClasses` parameter is defined, it defaults to the group name.

This covered in the plugin documentation

https://gradle-pitest-plugin.solidsoft.info/

An example configuration is provided there, with supporting comments.

```
pitest {
    targetClasses = ['our.base.package.*']  //by default "${project.group}.*"
    pitestVersion = '1.9.0' //not needed when a default PIT version should be used
    threads = 4
    outputFormats = ['XML', 'HTML']
    timestampedReports = false
}
```

**Comment by nagkumar** [comment]
Curious to know further..

I would have expected a relationship with mainSourceSets or sourceSets.main etc, any reason for taking default as ${project.group}, such a relationship when I filed this bug looked too strange to me.. not easy to think of..
