### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by hcoles** [hcoles/pitest#122]
The documentation for pitest is starting to get out of sync with the code. Part of the problem is that the existing site is not easy to update.

I'd therefore like to move most of the documentation off of the site to somewhere where it is easier to update, leaving the site for more promotional purposes (incidentally if anyone knows of someone that could do a better job of making the site look nice please let me know).

Possible solutions include 

1) Github wiki - easy to update but does not support pull requests
2) Gihub pages - supports pull requests but feel like this would overlap with the purpose of the main site + would involve messing about with jekyll or using default styling
3) An asciidoc/markdown file/files in the main repo that can be rendered to pdf

I'm minded towards 1 or 3. 

1 provides the lowest barrier to participating but does not offer any review system for changes beyond asking people to create an issue to discuss before editing.

3 allows for pull requests etc and versioned releases of the documentation. Getting (nice) pdf rendering into the build without introducing environmental dependencies might not be straightforward though. Not everyone wants to read a PDF doc + plenty of people come to the existing doc pages while googling for a solution to problems. 

Anyone got any thoughts?

Thanks

Henry

**Comment by lkwg82** [comment]
can this be closed?

**Comment by hcoles** [comment]
@lkwg82 Can't see why not.
