### ISSUE TITLE
Does pitest support incremental file testing for multi module Maven projects？

### ISSUE THREAD

**Issue by wlopper** [hcoles/pitest#1234]
I have a multi module Maven project and would like to use pitest for mutation testing. I have done incremental line coverage for single module Maven projects before, so I naturally believe that multiple modules can also achieve it. But the fact seems to be different. When I tested with multiple module incremental files, the files that were modified in the submodules were not detected. I found an article online that said it doesn't support it. 
![image](https://github.com/hcoles/pitest/assets/54232090/9907f6f9-0199-47bb-ad69-a1b748189931)
I wonder if there are any other ways

**Comment by wlopper** [comment]
My configuration is as follows:
`
    <scm>
        <url>scm:git:https://xxx.git</url>
        <connection>scm:git:https://xxx.git</connection>
        <developerConnection>scm:git:https://xxx.git</developerConnection>
        <tag>HEAD</tag>
    </scm>

 <profiles>
        <profile>
            <id>demo-pitest</id>

            <activation>
                <property>
                    <name>demo-pitest</name>
                    <value>true</value>
                </property>
            </activation>

            <properties>
                <adc.pitest.timeoutFactor>1.25</adc.pitest.timeoutFactor>
                <adc.pitest.timeoutConstant>4000</adc.pitest.timeoutConstant>
            </properties>

            <modules>
                <module>report</module>
            </modules>

            <build>
                <pluginManagement>
                    <plugins>
                        <plugin>
                            <groupId>org.pitest</groupId>
                            <artifactId>pitest-maven</artifactId>
                            <version>1.10.4</version>
                            <dependencies>
                                <dependency>
                                    <groupId>org.pitest</groupId>
                                    <artifactId>pitest-junit5-plugin</artifactId>
                                    <version>1.1.2</version>
                                </dependency>
                            </dependencies>
                            <configuration>
                                <threads>1</threads>
                                <verbose>true</verbose>
                                <failWhenNoMutations>false</failWhenNoMutations>
                                <exportLineCoverage>true</exportLineCoverage>
                                <outputFormats>
                                    <outputFormat>XML</outputFormat>
                                    <outputFormat>HTML</outputFormat>
                                </outputFormats>
                                <timestampedReports>false</timestampedReports>
                                <include>ADDED,MODIFIED</include>
                                <connectionType>connection</connectionType>
                                <originBranch>HEAD</originBranch>
                                <destinationBranch>origin/master</destinationBranch>
                                <withHistory>false</withHistory>
                                <timeoutFactor>${adc.pitest.timeoutFactor}</timeoutFactor>
                                <timeoutConstant>${adc.pitest.timeoutConstant}</timeoutConstant>
                            </configuration>
                        </plugin>
                    </plugins>
                </pluginManagement>

                <plugins>
                    <plugin>
                        <groupId>org.pitest</groupId>
                        <artifactId>pitest-maven</artifactId>
                        <executions>
                            <execution>
                                <id>run-mutation-tests</id>
                                <goals>
                                    <goal>scmMutationCoverage</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
`
and the report sub module configure as follows:
`
<profiles>
        <profile>
            <id>demo-pitest</id>

            <activation>
                <property>
                    <name>demo-pitest</name>
                    <value>true</value>
                </property>
            </activation>

            <properties>
            </properties>

            <build>
                <plugins>
                    <plugin>
                        <groupId>org.pitest</groupId>
                        <artifactId>pitest-maven</artifactId>
                        <executions>
                            <execution>
                                <id>report</id>
                                <phase>prepare-package</phase>
                                <goals>
                                    <goal>report-aggregate</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
`

**Comment by wlopper** [comment]
Thank you for your reply. I will try to use it

**Comment by wlopper** [comment]
After multiple attempts, I found that pitest supports multi module Maven mutation testing. The previous failure was due to the fact that during the execution of the pitest, the default value of scmRootDir was in the parent module path of the current module. This results in the inability to detect modified files in multi-level submodules. The parent module needs to add the following configuration：`<scmRootDir>${user.dir}</scmRootDir>`

I suggest that the default value of scmRootDir is the root module path instead of the parent module path of the current module. What's your suggestion @hcoles .

In addition, the arcmute plugin seems to also use the scm plugin.

**Comment by hcoles** [comment]
Thanks for reporting back @wlopper. If you can suggests some edits to the docs at 

https://github.com/hcoles/pitest-site

That would be helpful.

The arcmutate plugin does not use the scm plugin (it works in completely different manner, with no dependency on maven). Can you explain how you got that impression?

**Comment by wlopper** [comment]
Thank you for your reply @hcoles .

My native language is not English, which is not good, so it is not convenient to edit documents. In fact, I can only communicate with you through translation software。

As for the arcmute plugin, it does not rely on the scm plugin. I removed the scm plugin configuration before, but forgot to change the startup command to mutionCoverage, which resulted in the pitest running prompt requiring scm configuration. It is worth mentioning that if I configure the scm plugin and start it using the scmMutationCoverage command, I can also perform incremental line testing on git.

Finally, thank you again for your reply  : )
