### ISSUE TITLE
How to run pitest on Maven projects with separate business code and test code

### ISSUE THREAD

**Issue by wlopper** [hcoles/pitest#1237]
Hello @hcoles , may I ask if the business code and test code of the Maven project are written separately in two modules, and the directory interface is similar to:
```
pitest-demo
├─apollo-impl
├─apollo-impl-test
```
Is there any way to display the test results?
I found a relevant issue: https://github.com/hcoles/pitest/issues/376 Using the pitmp plugin can achieve cross module testing. 

But Pitmp has not been updated for a long time. After testing, I found that the current Pitmp plugin does not support versions of pitest maven after 1.4.7. Moreover, if I want to use the arc mate plugin for git incremental code testing in the future, it seems to be very difficult.
Looking forward to your reply @hcoles .

**Comment by hcoles** [comment]
The pitest maven plugin does not currently support projects where the tests and code under test are in seperate modules.

**Comment by wlopper** [comment]
Thank you for your reply. Perhaps dividing the testing and business code into two modules in the Maven project is not a good architectural design. I will try to change this architectural design.
