### ISSUE TITLE
Reproduce test failures in the event that a mutant is killed.

### ISSUE THREAD

**Issue by natasha-jeppu** [hcoles/pitest#1244]
Is there a way to reproduce the test failure that caused a mutant to be detected/killed? How do you verify the result/report produced by Pitest?
Also, when using Pitest with random input generators (such as Kotest) is the seed used to produce a test failure for a KILLED mutant observable?

**Comment by hcoles** [comment]
If you want to "verify" the report produced by pitest, you would need to do this independtly of the tool by recreating the mutants manually.

I'm not familiar with kotest, but if you are using property testing tool with mutation testing I would recomend setting a fixed seed and disabling shrinking (which is usually computationally expensive). Randomness is not compatible with mutation testing.

**Comment by hcoles** [comment]
Introducing randomness means there is no guarantee that the test suite will kill the same mutants across multiple runs. It doesn't make sense to do this when mutation testing - use a fixed seed so you know that the test suite behaves the same each time. Use randomness when you are not mutation testing to hunt for unknown bugs in the unmodified code.

**Comment by natasha-jeppu** [comment]
Thank you @hcoles. This is useful.
