### ISSUE TITLE
Misleading message when project has no code to mutate

### ISSUE THREAD

**Issue by punkratz312** [hcoles/pitest#1254]
I'm currently facing a perplexing issue with pitest:1.15.0:mutationCoverage within my software development pipeline. 

The problem manifests as pitest skipping the project, citing a lack of tests and an empty state, despite the presence of tests. 

Does anyone have insight into what might be causing this issue, or any clues on how to resolve it?

![image](https://github.com/hcoles/pitest/assets/8830888/4c840aa8-996e-4ac6-97f6-7fc6276f3025)

Log:

```


[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.027 s - in de.company.tech.ddd.e2e_acceptance_tests.warehouse.restock.TestRestock
Hibernate: drop table if exists cart cascade 
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 28, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- jar:3.3.0:jar (default-jar) @ e2e-acceptance-tests ---




[INFO] --- pitest:1.15.0:mutationCoverage (mutation-coverage) @ e2e-acceptance-tests ---
[INFO] Skipping project because:
[INFO]   - Project has no tests, it is empty.



```

**Comment by Stephan202** [comment]
Hey @punkratz312! If I'm reading the screenshots right, you're using JUnit 5, but without the [pitest-junit5-plugin](https://github.com/pitest/pitest-junit5-plugin). Can you try adding it?

**Comment by punkratz312** [comment]
Thanks @Stephan202

I have already tried that before without success.

pitest-junit5-plugin:

![image](https://github.com/hcoles/pitest/assets/8830888/ce70d135-f338-497b-a627-5a8d8636bab9)

Project has no tests, it is empty:
![image](https://github.com/hcoles/pitest/assets/8830888/e970ed2d-1dd4-4c37-892f-2624b5a6f2e1)

test-classes:
![image](https://github.com/hcoles/pitest/assets/8830888/3c9b45dd-c5f4-4b7b-90ba-6c6633d7eac7)

**Comment by hcoles** [comment]
The error message is misleading/wrong. 

The problem is that the 'e2e-acceptance-tests' project has no production code to mutate, only test code.

**Comment by punkratz312** [comment]
Thank you for the hint @hcoles. That is kind of true, as the target code (to mutate) lives in another module and not directly included. It is referred as a dependency.

Is therefore the byte code mutation not possible? 

![image](https://github.com/hcoles/pitest/assets/8830888/f9e96fdd-584f-429e-81d4-fbfc5f3c4b5a)

**Comment by hcoles** [comment]
Pitest doesn't support tests in a seperate module than the code under tests. From the name of the module, it sounds like these tests would not be suitable for mutation testing anyway. For practical reasons, mutation testing requires fast running unit tests. As a fundamental implementation detail, pitest requires tests that run in the same JVM as the code under test. This is often not the case for "end to end" tests that communicate with the code under test via http.

**Comment by punkratz312** [comment]
Thank you for the update; appreciate it. Perhaps a more precise error message would be helpful in making things clearer.

**Comment by punkratz312** [comment]
Seems to work fine with the end-to-end (E2E) stack. Yes, indeed, the tests actually only test the app black box over the web interface, just like the real client would do.

Still, achieving 100% line coverage with this method on a normal check:

![image](https://github.com/hcoles/pitest/assets/8830888/8a5b09b3-cf81-4cea-aaed-95dfb20a5c5d)

This tremendous tool, Pitest, is capable of testing with this high-level approach as well as with normal unit tests, which is maybe what it was designed for in the first place.

Now it's actually the same code, all within one project. Thanks a lot!

![image](https://github.com/hcoles/pitest/assets/8830888/40a74d98-67c2-4e2e-b768-6f305ae54959)
