### ISSUE TITLE
PitHelpError : tests did not pass without mutation when calculating the line coverage, Mutation testing requires a green suite.

### ISSUE THREAD

**Issue by AjithGowda** [hcoles/pitest#1272]
we are building the plugin using pitest framework,  test is passing with Junit but when mutation scan is executed pitest is failing  . we are using intellij 2023 IDE which is compatible with JDK 17.  ( Note : This issue is observed after we upgraded our intellij to 2023 , earlier with JDK 11 with intellij2022 this was working as expected)

Description : Test cases are passed when test executed via gradle task , but pitest is failing to execute the test.

Error : Exception in thread "main" org.pitest.help.PitHelpError: 7 tests did not pass without mutation when calculating line coverage. Mutation testing requires a green suite

Sample Code for which pitest is giving the above error : 

public class XYZMutationTreeCellRenderer extends **NodeRenderer** {

    @Override
public void customizeCellRenderer(JTree tree, Object value, boolean selected, boolean expanded, boolean leaf, int row, boolean hasFocus) {

        super.customizeCellRenderer(tree, value, selected, expanded, leaf, row, hasFocus);
        CustomMutableTreeNode node = (CustomMutableTreeNode ) value;
        var userObj = node.getUserObject();

        if (userObj instanceof Mutation && ((Mutation) userObj).isHovered()) {
            this.setForeground(JBColor.GRAY);
        } else if (userObj instanceof String) {

            String nodeVal = (String) userObj;

            if (nodeVal.contains(Constants.STATUS_KILLED)) {
                this.setToolTipText(Messages.STATUS_KILLED_TOOLTIP);
            } else if (nodeVal.contains(Constants.STATUS_SURVIVED)) {
                this.setToolTipText(Messages.STATUS_SURVIVED_TOOLTIP);
            } else if (nodeVal.contains(Constants.STATUS_NO_COVERAGE)) {
                this.setToolTipText(Messages.STATUS_NO_COVERAGE_TOOLTIP);
            } else if (nodeVal.contains(Constants.MUTATION_REPORT_TITLE)) {
                this.setToolTipText(Messages.MUTATION_REPORT_TITLE_TOOLTIP);
            }
        }
    }
    
we are not sure if we need any additional configuration in pitest for JDK 17 compatibility.

PiTest version : 1.15.3
Junit5 :1.2.1

  Could you help us to resolve this issue please.

**Comment by hcoles** [comment]
If you put together a minimal executable project that reproduces the issue, I can take a look.

**Comment by AjithGowda** [comment]
> If you put together a minimal executable project that reproduces the issue, I can take a look.

Hi @hcoles 

Here's is the project : https://github.com/AjithGowda/pitSample

Branch : master

steps : 
1) Clean build the project 
2) Run the test from gradle task ( Executes successfully )
3) Run pitest task ( failed to execute)

Looking forward for your response ,

Thank you

**Comment by AjithGowda** [comment]
> Thanks for the minimal project.
> 
> The problem is that this project is using the module path, while pitest is still using the old style classpath. This is a known issue which need resolving.
> 
> If you update the project to use the latest version of pitest and the junit plugin, the problem becomes clearly visible in the log
> 
> ```groovy
> pitest{
>     pitestVersion = '1.15.3'
>     targetClasses=["com.*"]
>     junit5PluginVersion = '1.2.1'
>     verbose=true
> }
> ```
> 
> ```
> 13:59:45 PIT >> INFO : MINION :         at com.org.sample.Renderer.<init>(Renderer.java:10)
> 13:59:45 PIT >> INFO : MINION :         at com.org.sample.RendererTest.CustomizeCellRenderer(RendererTest.groovy:19)
> 13:59:45 PIT >> INFO : MINION : Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make static java.awt.Graphics javax.swing.JComponent.safelyGetGraphics(java.awt.Component) accessible: module java.desktop does not "opens javax.swing" to unnamed module @15994b0b
> ```
> 
> You can work round it for now by opening any necessary modules in the pitest config.
> 
> ```groovy
> pitest{
>     pitestVersion = '1.15.3'
>     targetClasses=["com.*"]
>     junit5PluginVersion = '1.2.1'
>     verbose=true
>     jvmArgs.add("--add-opens=java.base/java.lang=ALL-UNNAMED")
>     jvmArgs.add("--add-opens=java.desktop/javax.swing=ALL-UNNAMED")
> }
> ```

@hcoles 

Thanks for the prompt response.

 Is there a workaround to fix this issue via command line as well ?

**Comment by hcoles** [comment]
@AjithGowda I'm not sure what you mean. If you update the build file as suggested, it will work when running gradle from the commandline.

**Comment by AjithGowda** [comment]
> @AjithGowda I'm not sure what you mean. If you update the build file as suggested, it will work when running gradle from the commandline.

Sorry if i had not conveyed it right , What i mean is 

Can we add the jvm params ( jvmArgs.add("--add-opens=java.base/java.lang=ALL-UNNAMED"), when we run using `org.pitest.mutationtest.commandline.MutationCoverageReport`  ?

If yes , could you help us with that ?

**Comment by hcoles** [comment]
If you are doing something custom calling MutationCoverageReport programatically, I'm afraid I'm not able to offer free consultancy. Paid consultancy is available via [arcmuate.com](https://www.arcmutate.com/)

**Comment by AjithGowda** [comment]
> If you are doing something custom calling MutationCoverageReport programatically, I'm afraid I'm not able to offer free consultancy. Paid consultancy is available via [arcmuate.com](https://www.arcmutate.com/)

@hcoles  Thanks for the input will try it out via configuration ,Have one more question. 

I see there are difference in report when we run pitest using old and new pitest versions. when we run pitest with old pit version ( 1.11.6) with junit plugin (1.1.2) then most of the mutants are reported under killed or survived and only less under no coverage. where as if i run the same code and test with pitest version (1.15.3) and junit plugin (1.2.1), then most of the mutants are under **no coverage** section. May i know why there is difference ?

**Comment by AjithGowda** [comment]
> Hi @AjithGowda
> 
> The sample project has only one mutant marked as no coverage, this is in an else branch that is never executed by a test.
> 
> If you are seeing mutants marked as no coverage which you believe are covered by a test, I can take a look if you upload a minimal executable project that reproduces the issue.

Hi @hcoles ,

will work on the minimal executable project. 

Also the workaround you suggested above  `--jvmArgs.add("--add-opens=java.base/java.lang=ALL-UNNAMED")
   --jvmArgs.add("--add-opens=java.desktop/javax.swing=ALL-UNNAMED")`  , is it specific to the project we sent or this will fix for all the issues of this type error ?

**Comment by AjithGowda** [comment]
> > Hi @AjithGowda
> > The sample project has only one mutant marked as no coverage, this is in an else branch that is never executed by a test.
> > If you are seeing mutants marked as no coverage which you believe are covered by a test, I can take a look if you upload a minimal executable project that reproduces the issue.
> 
> Hi @hcoles ,
> 
> will work on the minimal executable project.
> 
> Also the workaround you suggested above `--jvmArgs.add("--add-opens=java.base/java.lang=ALL-UNNAMED") --jvmArgs.add("--add-opens=java.desktop/javax.swing=ALL-UNNAMED")` , is it specific to the project we sent or this will fix for all the issues of this type error ?

@hcoles  Could you help us with the above query please ?

**Comment by hcoles** [comment]
Can you provide a little more detail about your project? It appears to be a mutation testing plugin for Intelij. Is it open source?

**Comment by AjithGowda** [comment]
> Can you provide a little more detail about your project? It appears to be a mutation testing plugin for Intelij. Is it open source?

Hi @hcoles 

Its not open source . Its a light project building for small set of people to run via command line. 

We would like to know , the workaround you suggested to add the jvmargs is it specific to the `minimal executable project` i sent to you or will it fix all similar kind of issues.

Also could this be resolved in latest releases to piTest ?

**Comment by hcoles** [comment]
You can read about add-opens and the module path in the oracle java 9 migration guide

https://docs.oracle.com/en/java/javase/17/migrate/migrating-jdk-8-later-jdk-releases.html

As for whether this will be fixed for you in a future release of pitest. If you are calling MutationCoverReport programatically it's not possible to say as it will depend on what your code does. Future releases of pitest will however look at module path support when run via maven or gradle.
