### ISSUE TITLE
When exporting linecoverage.xml, I hope to be able to customize and expand the export content

### ISSUE THREAD

**Issue by pflei** [hcoles/pitest#1278]
When I use Pitest, the exported linecoverage.xml file cannot meet my current requirements. I hope to customize the file content. Custom extensions are not currently supported. Could you please add the modification function? Thank you very much.

Currently there is only DefaultCoverageExporter.java

**Comment by hcoles** [comment]
Appologies for the slow response. This has now been implemented in #1288
