### ISSUE TITLE
PIT  cannot detect tests and classes when package starts with "com"

### ISSUE THREAD

**Issue by kulasangeles** [hcoles/pitest#1303]
I was trying to run PIT on my project where the package starts with com (ie com.project.test) and I cannot get any test and classes detected. When I changed it to ca or org for example - test and classes starts being detected and mutation testing runs as is. 

Let me know if you need more info. 

I am using Gradle
plugin version 1.15.0
junit5. 5.8

**Comment by hcoles** [comment]
If you are using gradle, you must explicitly set the target classes parameter (this is automatically populated for maven). Pitest will only mutate classes that match this glob.

**Comment by kulasangeles** [comment]
Hi @hcoles thanks for responding promptly. I am using target class and what's weird is that there are certain combinations that seems to not detect classes and tests. I did a few tests. for com.sun.* - it does not detect the tests and classes but for ca.sun.* it was detected. Not sure what's wrong with the com.sun package name that makes PITest not detect the tests and classes. 
Here are a few screenshots. 

<img width="1426" alt="image" src="https://github.com/hcoles/pitest/assets/69646975/4b85330b-4fe1-4c0a-ad63-5cc0ec9f08c9">
<img width="1293" alt="image" src="https://github.com/hcoles/pitest/assets/69646975/18b16183-2ce3-4a8e-9744-40ce30f2fdb7">
<img width="1352" alt="image" src="https://github.com/hcoles/pitest/assets/69646975/1dfdffe2-2407-41de-ba6b-033096a834f1">

**Comment by hcoles** [comment]
'com.sun' is a package used in legacy parts of the JDK (from Java's roots at sun microsystems). Pitest will not mutate it as it could cause all sorts of problems.

**Comment by kulasangeles** [comment]
I see. Thank you. One last question before I close the issue. What if there are packages that starts with com.sundance for example - do we have a way to still run pitest on them?

**Comment by hcoles** [comment]
If your target is set to `com.sundance.*` that should work without issue.

**Comment by kulasangeles** [comment]
> If your target is set to `com.sundance.*` that should work without issue.

![image](https://github.com/hcoles/pitest/assets/69646975/e94926f3-222d-46c8-87a8-16c0f1bb5716)
It does not as per my tests

**Comment by hcoles** [comment]
If you share a minimum project that reproduces the issues I can take a look and see what is going on.

**Comment by kulasangeles** [comment]
[test-learner.zip](https://github.com/hcoles/pitest/files/14146431/test-learner.zip)
Here's a very small gradle project I am working on.

**Comment by hcoles** [comment]
Thanks for the project, this is indeed a (very old) and stupid bug in pitest.

The bit of the code that stops pitest from instrumenting jdk classes is missing a '.', so it is filtering "com.sun*" rather than "com.sun.*".

Should be fixed shortly.

**Comment by hcoles** [comment]
Fixed in 1.15.7.

Thanks again for reporting.

**Comment by kulasangeles** [comment]
Thank you for fixing @hcoles!
