### ISSUE TITLE
Mutating non-existing lines in Kotlin

### ISSUE THREAD

**Issue by jkromski** [hcoles/pitest#1306]
my `gradle pitest` reports that there is an issue on line which does not exist, see below:

![image](https://github.com/hcoles/pitest/assets/6883078/309e3f9f-6c4a-4105-ad8d-09a30646e9ce)

pitestVersion = '1.15.7'

**Comment by hcoles** [comment]
Do you have the kotlin plugin installed?

https://docs.arcmutate.com/docs/kotlin.html

**Comment by jkromski** [comment]
no

**Comment by hcoles** [comment]
That is likely the issue then. It's hard to say which language feature has produced these lines without seeing the full code, but a likely candidate is an inline function. These are support by the kotlin plugin.
