### ISSUE TITLE
PIT Help Error : Couldn't exclude classes / test classes - error - tests did not pass without mutation when calculating line coverage. Mutation testing requires a green suite.

### ISSUE THREAD

**Issue by KBALCHANDRAN** [hcoles/pitest#1320]
Issue: Even though I give 'excludedClasses' and 'excludedTestClasses' PIT includes these tests in the run and is not excluding. How it should be changed. These are .java classes. Please help.

-------------------------------------------------------------------
Here is my POM.xml:
<pitest-maven-plugin.version>1.4.9</pitest-maven-plugin.version>
        <pitest.skip>true</pitest.skip>
        <pitest.targetClasses.pattern>com.intuit.*</pitest.targetClasses.pattern>
        <pitest.mutation.coverage.threshold>0</pitest.mutation.coverage.threshold>
.
.
.

            <dependency>
                <groupId>org.pitest</groupId>
                <artifactId>pitest-maven</artifactId>
                <version>${pitest-maven-plugin.version}</version>
                <scope>compile</scope>
            </dependency>
.
.
.
<img width="909" alt="image" src="https://github.com/hcoles/pitest/assets/165348277/a7392844-d3c4-4edb-bbe4-195d0122c6ec">
.
.
.

**Comment by hcoles** [comment]
If you create a minimal project that reproduces the issue I can take a look.

**Comment by KBALCHANDRAN** [comment]
Could you please give me a sample POM.xml file that has the tags to be used for including and excluding files from mutation testing?
