### ISSUE TITLE
Formula for mutation score calculation

### ISSUE THREAD

**Issue by adarshnd14** [hcoles/pitest#1330]
I needed to understand the formula for the mutation score calculation. 

Is it 
(Killed+Timeout+NonViable+MemoryError+RunError) / Total mutants

I couldn't find the formula mentioned in the documentation. Let me know if I have missed it.

**Comment by hcoles** [comment]
The boolean passed into DetectionStatus indicates if it is treated as surviving or killed. 

https://github.com/hcoles/pitest/blob/dd84e8bad21e410b91c83674243079832935bc03/pitest/src/main/java/org/pitest/mutationtest/DetectionStatus.java#L22

So it's all the ones with true passed in / Total mutants

**Comment by adarshnd14** [comment]
Thank you for the response.
