### ISSUE TITLE
Failed Custom Mutator Creation

### ISSUE THREAD

**Issue by halcyonsoul3** [hcoles/pitest#1332]
Hi @hcoles ,
As suggested here https://pitest.org/quickstart/advanced, we tried implementing **custom-mutator** for our java-maven project by adding below plugin and dependencies.
Yet i am facing below error, can you please add proper documentation on creating custom-mutator.

**ERROR:
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal org.pitest:pitest-maven:1.16.1:mutationCoverage failed: Mutator or group MyCustomMutator is unknown. Check PIT configuration and try again.**

**Dependencies and Plugins**
org.pitest pitest-maven 1.16.1 org.pitest pitest-maven 1.16.1 org.pitest pitest-junit5-plugin 1.2.1

**Comment by hcoles** [comment]
A working example of a custom mutator plugin is provided in the pitest organisation

https://github.com/pitest/pitest-rv-plugin

**Comment by halcyonsoul3** [comment]
Thanks for the revert @hcoles ,
I have gone through the pitest-rv-plugin, looks like the mutators are implemented in pitest repository itself.
can you please share any link where pitest-rv-plugin is being used, apart from pitest repository ?
or can you help with the steps to follow on how to implement custom-mutators in our repository by importing pitest-rv-plugin ?

**Comment by hcoles** [comment]
> looks like the mutators are implemented in pitest repository itself.

I'm not sure how you got this impression. The pitest-rv contains the full implementation of the "research" operators as a stand alone plugin. 

If this working example does not provide sufficient information on how to implement a plugin, I can answer specific questions if you post a link to your source.
