### ISSUE TITLE
Missing Values of MutationCoverage & Test Strength in XML , CSV PITest Report

### ISSUE THREAD

**Issue by halcyonsoul3** [hcoles/pitest#1337]
Hi @hcoles,

I couldn't find the values of mutationCoverage and Test Strength in PITest Report of XML and CSV Format.
Can we have these values in both XML and CSV Formats as it is in HTML format ?

Thank you,
G Sai Nithin

**Comment by halcyonsoul3** [comment]
Hi @hcoles ,

Requesting you to please help us here.

Thank you,
G Sai Nithin

**Comment by hcoles** [comment]
These values are not included in the csv or xml. They are only calculated in the html report.
