### ISSUE TITLE
Project has either no tests or no production code.

### ISSUE THREAD

**Issue by nithishbattina** [hcoles/pitest#1346]
Hi  Henry Coles i have created an sample project where my mutations showing
--- pitest:1.15.3:mutationCoverage (default-cli) @ kotlin-project ---
[INFO] Skipping project because:
[INFO]   - Project has either no tests or no production code. i am
attaching project,can you please help as i have added more dependencies as
my original project consists
 kotlin-project.zip
<https://drive.google.com/file/d/1LW2mX-JraHWmxteue7NUs6xPh9waz3QK/view?usp=drive_web>

**Comment by hcoles** [comment]
There are multiple problems with this project.

The first one is that the test source directory is pointing to the maven default (src/test/java), but the tests are in src/test/kotlin.

You can fix this with

```xml
   <testSourceDirectory>src/test/kotlin</testSourceDirectory>
```

The kotlin plugin will be adding this in at runtime, but as you're calling a maven goal directly this won't be triggered for pitest. I'll make a change here so this isn't necessary in the future, and pitest will automatically consider src/test/kotlin in the future.

The target classes you have configured is also incorrect. Your code is actually in the rather strange package of "org.example.com.mutation".

You can omit this section of the pitest config as the pitest maven plugin will automatically set the target classes etc.

The version of junit platform you are using, does not match the requirements for the pitest-junit-5 plugin, so will fail at runtime.

If you fix the above issues pitest will run and report that you do not have a licence for the pitest-kotlin plugin. You will need to either acquire a licence or remove the plugin from the build.

**Comment by nithishbattina** [comment]
adding this  <testSourceDirectory>src/test/kotlin</testSourceDirectory>
fixed the issue, Thanks mate.
