### ISSUE TITLE
Read source files using the correct file encoding

### ISSUE THREAD

**Issue by hcoles** [hcoles/pitest#14]
_From [esko.luo...@gmail.com](https://code.google.com/u/102883237794451111459/) on December 10, 2011 21:40:28_

What steps will reproduce the problem? 1. Create a maven project which is configured to use UTF-8 for all files:
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    </properties>
2. Create a .java file with some non-ASCII characters, for example add a header "// Copyright © 2011"
3. Run pitest-maven What is the expected output? What do you see instead? Expected the "©" sign to show up correctly in the reports, but now it shows up as "Â©" and in the source code it is "&#194;&#169;" What version of the product are you using? On what operating system? pitest-maven 0.24 Please provide any additional information below. The solution is documented at http://maven.apache.org/plugin-developers/common-bugs.html#Reading_and_Writing_Text_Files

_Original issue: http://code.google.com/p/pitestrunner/issues/detail?id=14_

**Comment by maxgabut** [comment]
I tested it in 1.4.2 and it works fine. I think this bug can be closed.

**Comment by hcoles** [comment]
@maxgabut If you wait long enough they fix themselves. Seven years seems to be the magic time period.
