### ISSUE TITLE
Analysis of large multi-module projects only reports mutants for last module.

### ISSUE THREAD

**Issue by msjconscius** [hcoles/pitest#143]
I have a project with a total LOC of 130K lines and 5 sub-modules.

When trying to run PITest on the code with a total number of 2109 tests and the option "-DhistoryOutputFile", the file seems to grow becoming rather big, but in the end when the execution run ends, the file is reduced to only a few kb.

The reactor summary is as follows (building with maven 3 and pitest 1.1.0):

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Main ............................................. SUCCESS [0.946s]
[INFO] Main Core ........................................ SUCCESS [1:01:13.430s]
[INFO] Main Controller .................................. SUCCESS [1:26.581s]
[INFO] Main Client ...................................... SUCCESS [3.165s]
[INFO] Main Reporting ................................... SUCCESS [35.568s]
[INFO] Main Webservices ................................. SUCCESS [59.796s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1:04:19.757s
[INFO] Finished at: Mon Oct 20 16:25:20 CEST 2014
[INFO] Final Memory: 23M/441M
[INFO] ------------------------------------------------------------------------

As mentioned, only the 'Main webservices' results (or part of this) is shown in the analysis.

Is there anyway to fix this ? - on smaller projects it seems to be allright (~10K LOC)

**Comment by jakub-bochenski** [comment]
We are not seeing it yet but we soon might.

What is the status here? Will pitest maven plugin work with multiple modules or do you have to run it per each module? Is it dependent on modules size?

**Comment by hcoles** [comment]
@jakub-bochenski Based on the information in the original report I think this was most likely an issue with how multiple modules was setup rather than the size of the codebase. This is just a guess though.

Pitest doesn't currently aggregate data together, so if you run it on a multi module project it should run for each sub module and report at that level.

**Comment by jakub-bochenski** [comment]
Thanks for the clarification
Can you elaborate more: what in the module setup caused this failure? What rules do I need to observe to ensure the reports for each module are correct?

**Comment by maxgabut** [comment]
This issue has been inactive for a while.
@msjconscius, do you (or anyone else) think this is still an issue with the current version ?
If not, or if no one speak up in a month, this issue will be closed.

**Comment by maxgabut** [comment]
I'm closing this issue because it has been inactive for a long time.
