### ISSUE TITLE
Ambiguous mutation description in HTML report

### ISSUE THREAD

**Issue by UrsMetz** [hcoles/pitest#145]
The descriptions of some mutations are ambiguous in the HTML report. This can make it hard to find out what kind of mutations are not covered by tests.

Here you can find a minimal example of what I mean: https://github.com/UrsMetz/pitest-ambiguous-mutation-description-in-html-report.
The mutator "removed conditional" is listed twice but it is not clear from the report what kind of mutation survived. One can (try to) guess that from the list of mutators used but that's not too easy.

`RemoveConditionalMutator` has a descriptive implemention of `MethodMutatorFactory#getName()` but it seems like it's not used for the report.

**Comment by maxgabut** [comment]
Closing it because it was fixed.
