### ISSUE TITLE
Add ability to ignore classes based on type annotation

### ISSUE THREAD

**Issue by alexec** [hcoles/pitest#159]
We have some auto-generated class we don't really need coverage for. They are annotated using Lombok's @Data annotation. Can we please have the ability to ignore them?

http://projectlombok.org/features/Data.html

**Comment by Kidlike** [comment]
I am experiencing a difficulty, and I think it could be related to this.

I get the following:
```
removed call to org/springframework/transaction/aspectj/AbstractTransactionAspect::ajc$afterThrowing$org_springframework_transaction_aspectj_AbstractTransactionAspect$2$2a73e96c → SURVIVED
```

I don't use that spring class directly. I guess it's being used by some annotation.
I have tried this, but nothing changed:
```
<configuration>
    <avoidCallsTo>
        <avoidCallsTo>org.springframework.transaction.aspectj</avoidCallsTo>
    </avoidCallsTo>
...
</configuration>
```

Shouldn't the avoidCallsTo parameter ommit the mutations for this call ?

**Comment by gehel** [comment]
Ideally, this should be implemented with more granularity than class level. Lomboks annotate generated code with `@javax.annotation.Generated`. It would be great to be able to ignore those methods and not the full class.

**Comment by hcoles** [comment]
Unfortunately both lombok.data and javax.annotation.Generated have source retention so won't be visible in the bytecode.

Filtering methods or classes based on class or runtime retained annotations should be fairly straight forward - but you would need to double annotate lombok classes.

**Comment by gehel** [comment]
Lombok also provides the ability to annotate generated code with `@SuppressFBWarnings`, which has `CLASS` retention (see [documentation](http://projectlombok.org/features/configuration.html)). I don't know much about the internals of PIT, but I expect that this is sufficient.

**Comment by alexec** [comment]
I've tried to do this change myself, but I'm not really experienced enough
with the code base. I think you need to change both the coverage analysis
AND the mutation coverage?

**Comment by gehel** [comment]
I have not even looked at PIT code, so don't listen to me too much ... That being said, my main concern is to make sure that we don't mutate and test generated code. It is expensive and I'd love to make my builds faster ... Excluding generated code from reports / metrics would be good, but not as important (to me) as not mutating code.

**Comment by hcoles** [comment]
Currently classes that are excluded by package/name will have neither line or mutation coverage calculated.

Code filtered on a more fine grained level (e.g logging calls) will have line coverage calculated but no mutations seeded.

An annotation based filter would be easiest to implement as a org.pitest.mutationtest.filter.MutationFilter - this would mean line coverage would be calculated - even if the whole class was excluded from mutation analysis by an annotation. 

That would be a little inconsistent, but I'm not sure it would be worth the effort of trying to also exclude the classes from line coverage.

**Comment by AFulgens** [comment]
I am pro-annotation, so a generic solution with class/method annotations, with an optional parameter as to *which* mutators should be excluded would be really awesome. Something like
`@MutationFilter` for exclude every mutator and
`@MutationFilter(exclude={"VOID_METHOD_CALLS", "NON_VOID_METHOD_CALLS"})` for fine-tuning.

**Comment by sarahBuisson** [comment]
+1

**Comment by hcoles** [comment]
A very simple annotation based filter has just been added as part of #347

**Comment by esovan** [comment]
A specific annotation for excluding a test class or method from pitest would be much better. The  `javax.annotation.Generated` suggested in #347 is used for generated code and therefore is also excluded in other tools like jacoco, checkstyle and others.

 The format suggested by @AFulgens would make a lot of sense:
> I am pro-annotation, so a generic solution with class/method annotations, with an optional parameter as to _which_ mutators should be excluded would be really awesome. Something like `@MutationFilter` for exclude every mutator and `@MutationFilter(exclude={"VOID_METHOD_CALLS", "NON_VOID_METHOD_CALLS"})` for fine-tuning.

.. and if annotated class or function by default is excluded for all mutations, that would be perfect I think.
