### ISSUE TITLE
have a sonarqube analysis to check code quality

### ISSUE THREAD

**Issue by lkwg82** [hcoles/pitest#161]
Sonarqube offers free analysis for open source projects. To support the code quality and see the worst mistakes.

I will make a request on the mailing list.

Cheers Lars

P.S. see for example: http://nemo.sonarqube.org/dashboard/index/48209

**Comment by hcoles** [comment]
Pitest did use to be on sonar nemo, not sure how it got on there but I suspect the reason it was taken off is that the test suite is fairly expensive to run and doesn't play nicely with coverage tools.

While it was on there the feedback wasn't too useful as it was unclear what (if anything) triggered an analysis. If there's a github hook or something similar now that would be great.

**Comment by lkwg82** [comment]
I already requested it on the mailinglist: http://sonar.markmail.org/search/?q=list%3Aorg.codehaus.sonar.user+pitest#query:list%3Aorg.codehaus.sonar.user%20pitest+page:1+mid:r44tdosw5unnli7a+state:results

**Comment by ehartmann** [comment]
Hi,

The analysis has been set up and the result is available here : http://nemo.sonarqube.org/dashboard/index/org.pitest:pitest-parent

Cheers,

Eric

**Comment by hcoles** [comment]
Thanks - from the mail trail it sounds like it runs weekly, which is certainly more regular than when it was on there before.

Do you know if oss developers can get logins to nemo so they can mark false positives etc?

**Comment by ehartmann** [comment]
Exact the analysis are running every week-end.

For the time being, it's not possible to add account on Nemo. But it's a feature that we may offer in the future.

**Comment by lkwg82** [comment]
I think this can be closed as complete.

**Comment by lkwg82** [comment]
I forgot to add a link to the Readme.md
