### ISSUE TITLE
Allow classpath exclusions when running plugin

### ISSUE THREAD

**Issue by TomRK1089** [hcoles/pitest#166]
It would be helpful if PIT provided a way to exclude certain dependencies from the classpath when running, similar to both Surefire and Failsafe.

Alternatively, if there was a way for PIT to simply reuse any existing exclusions from Surefire, that would be nifty -- though probably more brittle.

This problem arose for me when I went to do mutation testing on an Android project -- the Android JAR bundles JUnit 3.x classes, which causes an issue when loaded. I was able to work around this issue by moving Android dependencies into a profile which was active by default, and specifying a different profile when running PIT. Changing the order of declared dependencies may also help as a workaround.

c.f. http://stackoverflow.com/questions/28074787/exclude-provided-dependency-from-classpath-when-running-pit

If the code doesn't look too intimidating, I'll try and put together a PR for this.

**Comment by TomRK1089** [comment]
I submitted a pull request at https://github.com/hcoles/pitest/pull/167 with my changes -- locally, at least, it does exactly what I want, allowing me to exclude Android JARs when running mutation analysis.

**Comment by hcoles** [comment]
Fixed in 1.1.4 release - thanks!
