### ISSUE TITLE
Surefire integration

### ISSUE THREAD

**Issue by hcoles** [hcoles/pitest#173]
Configuration currently needs to be duplicated between surefire and pitest (e.g excluded tests, jvm arguments).

It should be possible to read the surefire config and determine equivalent pitest configuration.

**Comment by hcoles** [comment]
Initial integration added.

* Excluded tests will be converted to filters (no support for surefire regex syntax yet)
* Included / excluded groups will be converted.

Excluded tests will be added to any defined in the pitest config.

Included / excluded groups will only be read if none are defined in pitest config.

Rationale is that mutation testing might be limited to different groups, but additional exclusions of individual tests might be made when mutation testing.

**Comment by lkwg82** [comment]
Plz can you reference the commits to watch the integration?

**Comment by hcoles** [comment]
@lkwg82 

https://github.com/hcoles/pitest/commit/9cb20a94d28d9e0635e7c23643c836dcca65788c
https://github.com/hcoles/pitest/commit/5471e705968360c06b2568a6b465d4e848be3de8

**Comment by maxgabut** [comment]
Closing it because it's done.
