### ISSUE TITLE
Remove project file functionality

### ISSUE THREAD

**Issue by hcoles** [hcoles/pitest#184]
Pitest contains an largely undocumented feature that allows project configuration to be read from a file when using the command line tool.

It is likely that this feature is not used by anyone, in which case it should be removed in the interests of having less code to maintain.

**Comment by UrsMetz** [comment]
@hcoles I'm just browsing throw the PIT code and noticed the file `pitest/pitest/src/main/resources/project-files/sample-project.xml`. Is this an example project file for the feature talked about in this issue? In case it is the file should also be removed as the commit 77f27b9 removed the project file feature?

**Comment by hcoles** [comment]
@UrsMetz Yes, that needs to go.  Thanks.

**Comment by lkwg82** [comment]
Is this complete?

**Comment by hcoles** [comment]
Yes - and now released. Thanks
