### ISSUE TITLE
Smarter defaults for threads

### ISSUE THREAD

**Issue by hcoles** [hcoles/pitest#185]
The number of threads must currently be explicitly specified. While this makes sense in terms of ensuring builds are repeatable, it means that configuration must be added to a project to get sensible defaults.

A more sensible approach would be to use the number of cores on the machine as the thread count unless an explicit number of threads has been set in the config.

**Comment by KyleRogers** [comment]
Not sure how that might effect users using pitest with integration tests and limited resources (database, file system etc.).

Maven, surefire etc. run single threaded by default, too. If you want to speed up things and you know your build or your tests support parallelism you can configure them to run multi-threaded.

**Comment by lkwg82** [comment]
Writing tests for parallel run is a discipline itself. I agree to @KyleRogers go the defensive but less error prone way and leave it this way.

Threading means more cpu usage and more memory. This affects timeouts of tests eventually.

Maybe it can be 
```
  <configuration>
     <threads>default | <NUMBER> | auto</threads>
  </configuration>
```

default = 1
<NUMBER> (self explaining)
auto = a profile of thread computation (e.g. numbers of cores / 2)

What about that?

**Comment by hcoles** [comment]
Now provided by the "auto_threads" feature.
