### ISSUE TITLE
raise minimum maven to 3.1.1

### ISSUE THREAD

**Issue by lkwg82** [hcoles/pitest#198]
I'd like to raise the maven version to the latest maven version supporting java5. According to [release notes](http://maven.apache.org/docs/history.html) it is 3.1.1.

Any objections?

It think it should be the first step to maven (currently) 3.3.3 (which requires jdk7).

**Comment by lkwg82** [comment]
It makes sense to wait for merged #202

**Comment by lkwg82** [comment]
We can proceed with raising the maven version.

**Comment by maxgabut** [comment]
Done for a while now. Minimum version is currently maven 3.2.5.

https://github.com/hcoles/pitest/blob/0ed9eab471727d46b3e7c4e8a064be981b8d6bdc/pom.xml#L74
