### ISSUE TITLE
New mutator: remove assignment to field/variable

### ISSUE THREAD

**Issue by hcoles** [hcoles/pitest#20]
_From [esko.luo...@gmail.com](https://code.google.com/u/102883237794451111459/) on December 16, 2011 20:25:45_

It would be nice to have a mutator which removes assignments to local variables and to fields. (In the case of assignments to final fields, for example in constructors, assignment removal might not be possible, so it could assign a null/zero value.)

_Original issue: http://code.google.com/p/pitestrunner/issues/detail?id=20_

**Comment by maxgabut** [comment]
If I understand correctly this thread is about the mutator `EXPERIMENTAL_MEMBER_VARIABLE` which has been merged. @hcoles I think we can close this one.

**Comment by ayaankazerouni** [comment]
Is there a similar mutator that removes local variable assignments? If not, I am open to trying to implement it.

cc: @hcoles
