### ISSUE TITLE
NON_VOID_METHOD_CALLS Mutator is buggy

### ISSUE THREAD

**Issue by lkwg82** [hcoles/pitest#205]
I think the `NON_VOID_METHOD_CALLS`-mutator is kind of buggy.

For this class 

```java
package de.lgohlke.pitxest;

import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public class RemovedCallBug {
    private final ExecutorService executorService = Executors.newFixedThreadPool(1);

    boolean doSomething() throws InterruptedException {
        return executorService != null;
    }
}
```

I expect the mutation:

```java
package de.lgohlke.pitxest;

import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public class RemovedCallBug {
    private final ExecutorService executorService = null;

    boolean doSomething() throws InterruptedException {
        return executorService != null;
    }
}
```

with this test

```java
package de.lgohlke.pitxest;

import org.junit.Test;

import static org.assertj.core.api.Assertions.assertThat;

public class RemovedCallBugTest {

    @Test
    public void test() throws InterruptedException {
        assertThat(new RemovedCallBug().doSomething()).isTrue();
    }
}
```

the reports looks this way

1. removed call to java/util/concurrent/Executors::newFixedThreadPool → NO_COVERAGE

an I dont agree ;)

Did I oversee someting?

**Comment by hcoles** [comment]
A NO_COVERAGE result would suggest a worrying issue with the coverage implementation rather than the mutator.

I just tried to reproduce this, but the mutation was killed as expected. See -> https://github.com/hcoles/pitest-issue-starter

**Comment by lkwg82** [comment]
I reduced it an published here: https://github.com/lkwg82/pitest_issue_205/tree/master

**Comment by hcoles** [comment]
@lkwg82 The issue looks to be a typo in this

```
<param>de.lgohlke.pixtest.**Test</param>
```

No tests are picked up as the package is called `pitxest`

**Comment by lkwg82** [comment]
I see, I see. Damn. ;)
