### ISSUE TITLE
Automatic selection of targetClasses in Maven plugin

### ISSUE THREAD

**Issue by jafarre-viewnext** [hcoles/pitest#215]
Hi,

I was thinking about a way to configure Pittest for all projects, without specific configurations, and came up with an idea I think could be of interest.

The thing is you can infer from the POM the source code location, and from it, all target classes, instead of specifying packages, which are specific for every project and may not have a common root across projects.

This way configuration of maven plugin is simplified and it is possible to define a global profile for Pitest analysis.

Thanks,

Juan

**Comment by jafarre-insags** [comment]
Cannot find a way to add a label.
Creating issue again.

**Comment by jafarre-insags** [comment]
Well, in fact you can also get the compiled-classes directory form the POM (by default target/classes) and infer by recursive search of .class files.

**Comment by hcoles** [comment]
@jafarre-insags The maven plugin does in fact do this already - only code from target/classes is mutated.

You raise a very good question as to why the targetClasses filter is still there. It certainly ought to be possible to make it optional when running via maven - I think the tricky bit is the instrumentation phase.

Checking where each class has been loaded from before instrumenting would be impractical, but some mechanism to avoid instrumenting everything is required or the coverage stage will take a measurable performance hit.

Perhaps a list of packages could be built up by scanning the target dir?

**Comment by hcoles** [comment]
Thinking this through properly, if a scan of the mutableCodePaths was made to collect package names it should be possible to omit the targetClasses filter whenever this was supplied (i.e not just for maven).

Any targetClasses filter that was supplied to the user could be logically anded to the auto generated one.

**Comment by jafarre-insags** [comment]
Thanks so much for the quick response and detailed comments.
In fact you've raised a doubt I had: mutableCodePaths is documented in command-line version, but not in Maven version and I thought it wasn't available.
Is it?

**Comment by hcoles** [comment]
Releases in 1.2.0
