### ISSUE TITLE
Support for in-container testing with arquillian

### ISSUE THREAD

**Issue by marcinMarcin** [hcoles/pitest#217]
Is it possible to add support for in-container testing with [arquillian](https://github.com/arquillian)?

**Comment by hcoles** [comment]
@marcinMarcin I don't know much about arquillian. If it spawns new jvms/processes then supporting it will be hard. If everything runs within the same jvm as the tests then it may be possible.

**Comment by marcinMarcin** [comment]
@hcoles thanks for answer.

From http://arquillian.org/blog/tags/roadmap/:

>Arquillian defines two styles of container, remote and embedded.<b> A remote container resides in a separate JVM from the test runner</b>. Its lifecycle may be managed by Arquillian, or Arquillian may bind to a container that is already started. <b>An embedded container resides in the same JVM</b> and is mostly likely managed by Arquillian.

I am interested in support for remote container, so I know it will be hard to add this functionality.
