### ISSUE TITLE
Cannot release using java 8

### ISSUE THREAD

**Issue by hcoles** [hcoles/pitest#220]
Appears to be a conflict between the maven javadoc annotations and the javadoc plugin.

Note - an explicit version was set for the Javadoc plugin to enable release in java 7. Not clear how/when that regression occurred, but the "fix" could be the cause of the issue for java 8.

**Comment by hcoles** [comment]
Checkstyle goal also fails when releasing with java 7. Why? Should be run on normal verification.

**Comment by hcoles** [comment]
Checkstyle issue fixed for 1.1.8 release. The checkstyle plugin was picking up the generated sources folder - not clear why this did not happen during normal builds, but is now explicitly excluded.

**Comment by hcoles** [comment]
Java 8 release now fixed. In fact only seems to be possible to release with Java 8 due to issue with javadoc flags.

For some reason the java8 verification project is not being updated by the release plugin.

**Comment by KyleRogers** [comment]
everything fixed? :)

**Comment by hcoles** [comment]
Release is now via java 8 only.
