### ISSUE TITLE
Mutation testing requires a green suite (again, but different)

### ISSUE THREAD

**Issue by thomas-mc-work** [hcoles/pitest#226]
I have tests that don't end with either `Test` or `IT` for integration test but with something else (`ST` for system Tests in my case as an individual convention). When I run TestNG it only picks up the first two cases, even if then `ST`-classes are annotated with `@Test`. Result is a green result. When running `mvn org.pitest:pitest-maven:mutationCoverage` then I get this error:

    Execution default-cli of goal org.pitest:pitest-maven:1.1.6:mutationCoverage failed: All tests did not pass without mutation when calculating line coverage. Mutation testing requires a green suite.

pitest is picking up the `ST` file which fails (due to a self produced missing connection). I would expect pitest to omit this test as TestNG does.

(no matter of the result it would be great to see the FQ name of the classes/filses that fail)

**Comment by KyleRogers** [comment]
Your last note might be worth another git issue - feel free to open one.

Do you use surefire to launch your TestNG tests?

There are two workarounds:
Pitest supports surefire excludes beeing "reused". You could add excludes für Tests ending with ```ST```. Or you could specify <targetTests> in pitests own configuration including only tests ending with ```Test``` or ```IT```.

BUT:
The real issue is the asymmetry between supporting surefire excludes but not supporting surefire includes. Never the less that would be a backward incompatible change if the pitest maven plugin would reuse both, surefire includes and excludes. I don't know how other users configure their tests.
I can understand your wish and I've been in the same situation. I didn't want to have system and integration tests being mutated and went down the ```<excludes>```-path combined with using failsafe to kick-off integration and systems tests.

**Comment by f9lz** [comment]
Individual test runs but maven build fails with mutation testing

[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building simulation-orchestration-scala 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ simulation-orchestration-scala ---
[INFO] Deleting /Users/f9lz/Local/src/simulation-data-management-f9lz/target
[INFO] 
[INFO] --- scala-maven-plugin:3.2.0:add-source (default) @ simulation-orchestration-scala ---
[INFO] Add Source directory: /Users/f9lz/Local/src/simulation-data-management-f9lz/src/main/scala
[INFO] Add Test Source directory: /Users/f9lz/Local/src/simulation-data-management-f9lz/src/test/scala
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ simulation-orchestration-scala ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ simulation-orchestration-scala ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- scala-maven-plugin:3.2.0:compile (default) @ simulation-orchestration-scala ---
[INFO] /Users/f9lz/Local/src/simulation-data-management-f9lz/src/main/java:-1: info: compiling
[INFO] /Users/f9lz/Local/src/simulation-data-management-f9lz/src/main/scala:-1: info: compiling
[INFO] Compiling 2 source files to /Users/f9lz/Local/src/simulation-data-management-f9lz/target/classes at 1474573306849
[INFO] prepare-compile in 0 s
[INFO] compile in 5 s
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ simulation-orchestration-scala ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 0 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ simulation-orchestration-scala ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- scala-maven-plugin:3.2.0:testCompile (default) @ simulation-orchestration-scala ---
[INFO] /Users/f9lz/Local/src/simulation-data-management-f9lz/src/test/java:-1: info: compiling
[INFO] /Users/f9lz/Local/src/simulation-data-management-f9lz/src/test/scala:-1: info: compiling
[INFO] Compiling 1 source files to /Users/f9lz/Local/src/simulation-data-management-f9lz/target/test-classes at 1474573312009
[INFO] prepare-compile in 0 s
[INFO] compile in 5 s
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ simulation-orchestration-scala ---
[INFO] Surefire report directory: /Users/f9lz/Local/src/simulation-data-management-f9lz/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running sf.simulation.fabricate.FabricateTest
14:41:58,449 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
14:41:58,450 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
14:41:58,450 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/Users/f9lz/.m2/repository/sf/core/code/core-utils/1.0.83/core-utils-1.0.83.jar!/logback.xml]
14:41:58,452 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
14:41:58,452 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/Users/f9lz/.m2/repository/sf/core/code/core-utils/1.0.83/core-utils-1.0.83.jar!/logback.xml]
14:41:58,452 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/Users/f9lz/.m2/repository/sf/api/api-doc/1.1.4/api-doc-1.1.4.jar!/logback.xml]
14:41:58,474 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@53c8bb96 - URL [jar:file:/Users/f9lz/.m2/repository/sf/core/code/core-utils/1.0.83/core-utils-1.0.83.jar!/logback.xml] is not of type file
14:41:58,619 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
14:41:58,628 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
14:41:58,636 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [stdout]
14:41:58,662 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
14:41:58,731 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
14:41:58,731 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [metricsOut]
14:41:58,731 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
14:41:58,732 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting additivity of logger [sf.icptp.springextensions.metrics] to false
14:41:58,732 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [metricsOut] to Logger[sf.icptp.springextensions.metrics]
14:41:58,733 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.apache] to ERROR
14:41:58,733 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.apache.http] to WARN
14:41:58,733 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.apache.http.client.protocol.ResponseProcessCookies] to ERROR
14:41:58,733 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.apache.http.impl.client.DefaultTargetAuthenticationHandler] to ERROR
14:41:58,734 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.springframework.core.type.classreading] to ERROR
14:41:58,734 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.springframework] to INFO
14:41:58,734 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.springframework.ldap.core.LdapTemplate] to ERROR
14:41:58,734 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [sf.icptp.springextensions.ui.SessionDestroyedFilter] to ERROR
14:41:58,734 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [sf.icptp.springextensions.conversation] to ERROR
14:41:58,734 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [SECURITY_EVENT] to ERROR
14:41:58,734 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [AUDIT] to INFO
14:41:58,734 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
14:41:58,734 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [stdout] to Logger[ROOT]
14:41:58,734 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
14:41:58,735 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@1f939fd3 - Registering current configuration as safe fallback point

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/f9lz/.m2/repository/ch/qos/logback/logback-classic/1.0.13/logback-classic-1.0.13.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/f9lz/.m2/repository/org/slf4j/slf4j-log4j12/1.7.10/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
2016-09-22 14:42:00,471 logger="akka.event.slf4j.Slf4jLogger" logLevel="INFO" marker="BUSINESS_EVENT" Slf4jLogger started
2016-09-22 14:42:00,526 logger="Remoting" logLevel="INFO" marker="BUSINESS_EVENT" Starting remoting
2016-09-22 14:42:00,755 logger="Remoting" logLevel="INFO" marker="BUSINESS_EVENT" Remoting started; listening on addresses :[akka.tcp://sparkDriverActorSystem@10.104.166.236:62814]
2016-09-22 14:42:01,164 logger="org.spark-project.jetty.server.Server" logLevel="INFO" marker="BUSINESS_EVENT" jetty-8.y.z-SNAPSHOT
2016-09-22 14:42:01,204 logger="org.spark-project.jetty.server.AbstractConnector" logLevel="INFO" marker="BUSINESS_EVENT" Started SelectChannelConnector@dropbox.com:4040

[Stage 0:>                                                          (0 + 0) / 2]
[Stage 0:>                                                          (0 + 2) / 2]
                                                                                Testing number of lines fabricated
Checking if the destination is created
Checking if the file is created and _SUCCESS exists
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 11.958 sec
2016-09-22 14:42:09,807 logger="org.spark-project.jetty.server.handler.ContextHandler" logLevel="INFO" marker="BUSINESS_EVENT" stopped o.s.j.s.ServletContextHandler{/metrics/json,null}
2016-09-22 14:42:09,808 logger="org.spark-project.jetty.server.handler.ContextHandler" logLevel="INFO" marker="BUSINESS_EVENT" stopped o.s.j.s.ServletContextHandler{/stages/stage/kill,null}
2016-09-22 14:42:09,808 logger="org.spark-project.jetty.server.handler.ContextHandler" logLevel="INFO" marker="BUSINESS_EVENT" stopped o.s.j.s.ServletContextHandler{/api,null}
2016-09-22 14:42:09,808 logger="org.spark-project.jetty.server.handler.ContextHandler" logLevel="INFO" marker="BUSINESS_EVENT" stopped o.s.j.s.ServletContextHandler{/,null}
2016-09-22 14:42:09,809 logger="org.spark-project.jetty.server.handler.ContextHandler" logLevel="INFO" marker="BUSINESS_EVENT" stopped o.s.j.s.ServletContextHandler{/static,null}
2016-09-22 14:42:09,809 logger="org.spark-project.jetty.server.handler.ContextHandler" logLevel="INFO" marker="BUSINESS_EVENT" stopped o.s.j.s.ServletContextHandler{/executors/threadDump/json,null}
2016-09-22 14:42:09,809 logger="org.spark-project.jetty.server.handler.ContextHandler" logLevel="INFO" marker="BUSINESS_EVENT" stopped o.s.j.s.ServletContextHandler{/executors/threadDump,null}
2016-09-22 14:42:09,809 logger="org.spark-project.jetty.server.handler.ContextHandler" logLevel="INFO" marker="BUSINESS_EVENT" stopped o.s.j.s.ServletContextHandler{/executors/json,null}
2016-09-22 14:42:09,810 logger="org.spark-project.jetty.server.handler.ContextHandler" logLevel="INFO" marker="BUSINESS_EVENT" stopped o.s.j.s.ServletContextHandler{/executors,null}
2016-09-22 14:42:09,810 logger="org.spark-project.jetty.server.handler.ContextHandler" logLevel="INFO" marker="BUSINESS_EVENT" stopped o.s.j.s.ServletContextHandler{/environment/json,null}
2016-09-22 14:42:09,810 logger="org.spark-project.jetty.server.handler.ContextHandler" logLevel="INFO" marker="BUSINESS_EVENT" stopped o.s.j.s.ServletContextHandler{/environment,null}
2016-09-22 14:42:09,810 logger="org.spark-project.jetty.server.handler.ContextHandler" logLevel="INFO" marker="BUSINESS_EVENT" stopped o.s.j.s.ServletContextHandler{/storage/rdd/json,null}
2016-09-22 14:42:09,811 logger="org.spark-project.jetty.server.handler.ContextHandler" logLevel="INFO" marker="BUSINESS_EVENT" stopped o.s.j.s.ServletContextHandler{/storage/rdd,null}
2016-09-22 14:42:09,811 logger="org.spark-project.jetty.server.handler.ContextHandler" logLevel="INFO" marker="BUSINESS_EVENT" stopped o.s.j.s.ServletContextHandler{/storage/json,null}
2016-09-22 14:42:09,811 logger="org.spark-project.jetty.server.handler.ContextHandler" logLevel="INFO" marker="BUSINESS_EVENT" stopped o.s.j.s.ServletContextHandler{/storage,null}
2016-09-22 14:42:09,811 logger="org.spark-project.jetty.server.handler.ContextHandler" logLevel="INFO" marker="BUSINESS_EVENT" stopped o.s.j.s.ServletContextHandler{/stages/pool/json,null}
2016-09-22 14:42:09,811 logger="org.spark-project.jetty.server.handler.ContextHandler" logLevel="INFO" marker="BUSINESS_EVENT" stopped o.s.j.s.ServletContextHandler{/stages/pool,null}
2016-09-22 14:42:09,812 logger="org.spark-project.jetty.server.handler.ContextHandler" logLevel="INFO" marker="BUSINESS_EVENT" stopped o.s.j.s.ServletContextHandler{/stages/stage/json,null}
2016-09-22 14:42:09,812 logger="org.spark-project.jetty.server.handler.ContextHandler" logLevel="INFO" marker="BUSINESS_EVENT" stopped o.s.j.s.ServletContextHandler{/stages/stage,null}
2016-09-22 14:42:09,812 logger="org.spark-project.jetty.server.handler.ContextHandler" logLevel="INFO" marker="BUSINESS_EVENT" stopped o.s.j.s.ServletContextHandler{/stages/json,null}
2016-09-22 14:42:09,813 logger="org.spark-project.jetty.server.handler.ContextHandler" logLevel="INFO" marker="BUSINESS_EVENT" stopped o.s.j.s.ServletContextHandler{/stages,null}
2016-09-22 14:42:09,813 logger="org.spark-project.jetty.server.handler.ContextHandler" logLevel="INFO" marker="BUSINESS_EVENT" stopped o.s.j.s.ServletContextHandler{/jobs/job/json,null}
2016-09-22 14:42:09,813 logger="org.spark-project.jetty.server.handler.ContextHandler" logLevel="INFO" marker="BUSINESS_EVENT" stopped o.s.j.s.ServletContextHandler{/jobs/job,null}
2016-09-22 14:42:09,814 logger="org.spark-project.jetty.server.handler.ContextHandler" logLevel="INFO" marker="BUSINESS_EVENT" stopped o.s.j.s.ServletContextHandler{/jobs/json,null}
2016-09-22 14:42:09,815 logger="org.spark-project.jetty.server.handler.ContextHandler" logLevel="INFO" marker="BUSINESS_EVENT" stopped o.s.j.s.ServletContextHandler{/jobs,null}

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- scalatest-maven-plugin:1.0:test (test) @ simulation-orchestration-scala ---
[36mDiscovery starting.[0m
[36mDiscovery completed in 106 milliseconds.[0m
[36mRun starting. Expected test count is: 0[0m
[32mDiscoverySuite:[0m
[36mRun completed in 240 milliseconds.[0m
[36mTotal number of tests run: 0[0m
[36mSuites: completed 1, aborted 0[0m
[36mTests: succeeded 0, failed 0, canceled 0, ignored 0, pending 0[0m
[33mNo tests were executed.[0m
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ simulation-orchestration-scala ---
[INFO] Building jar: /Users/f9lz/Local/src/simulation-data-management-f9lz/target/simulation-orchestration-scala-0.0.1-SNAPSHOT.jar
[INFO] 
[INFO] --- pitest-maven:1.1.4:mutationCoverage (check) @ simulation-orchestration-scala ---
[INFO] Found plugin : Default csv report plugin
[INFO] Found plugin : Default xml report plugin
[INFO] Found plugin : Default html report plugin
[INFO] Found plugin : Default limit mutations plugin
[INFO] Found shared classpath plugin : Default mutation engine

2:42:12 PM PIT >> INFO : Mutating from /Users/f9lz/Local/src/simulation-data-management-f9lz/target/classes
2:42:12 PM PIT >> INFO : Verbose logging is disabled. If you encounter an problem please enable it before reporting an issue.
2:42:12 PM PIT >> INFO : SLAVE : objc[26557]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.7.0_99.jdk/Contents/Home/jre/bin/java and /Library/Java/JavaVirtualMachines/jdk1.7.0_99.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be 
2:42:12 PM PIT >> INFO : SLAVE : used. Which one is undefined.

2:42:13 PM PIT >> INFO : Sending 2 test classes to slave
2:42:13 PM PIT >> INFO : Sent tests to slave
2:42:13 PM PIT >> INFO : SLAVE : 2:42:13 PM PIT >> INFO : Found  1 tests

2:42:13 PM PIT >> INFO : SLAVE : 2:42:13 PM PIT >> INFO : Dependency analysis reduced number of potential tests by 0

2:42:13 PM PIT >> INFO : SLAVE : 2:42:13 PM PIT >> INFO : 1 tests received

2:42:14 PM PIT >> INFO : SLAVE : SLF4J: Class path contains multiple SLF4J bindings.

2:42:14 PM PIT >> INFO : SLAVE : SLF4J: Found binding in [jar:file:/Users/f9lz/.m2/repository/ch/qos/logback/logback-classic/1.0.13/logback-classic-1.0.13.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/f9lz/.m2/repository/org/slf4j/slf4j-log4j12/1.7
2:42:14 PM PIT >> INFO : SLAVE : .10/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]

2:42:17 PM PIT >> INFO : SLAVE : 2:42:17 PM PIT >> WARNING : More threads at end of test (43) quantityFabricated(sf.simulation.fabricate.FabricateTest) than start. (4)

2:42:17 PM PIT >> WARNING : Description [testClass=sf.simulation.fabricate.FabricateTest, name=quantityFabricated(sf.simulation.fabricate.FabricateTest)] did not pass without mutation.
/2:42:18 PM PIT >> INFO : Calculated coverage in 5 seconds.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 35.508 s
[INFO] Finished at: 2016-09-22T14:42:18-05:00
[INFO] Final Memory: 31M/362M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.pitest:pitest-maven:1.1.4:mutationCoverage (check) on project simulation-orchestration-scala: Execution check of goal org.pitest:pitest-maven:1.1.4:mutationCoverage failed: All tests did not pass without mutation when calculating line coverage. Mutation testing requires a green suite.
[ERROR] See http://pitest.org for more details.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

**Comment by thomas-mc-work** [comment]
Phew, that's an old issue. I think I solved the situation by excluding all tests except for unit tests:

    <plugin>
        <groupId>org.pitest</groupId>
        <artifactId>pitest-maven</artifactId>
        <version>1.1.9</version>
        <configuration>
            <targetTests>
                
                <param>*Test</param>
            </targetTests>
        </configuration>
    </plugin>

**Comment by f9lz** [comment]
I have a single test on my suite! I cannot exclude it.
I'm a newbie trying to learn scala.

**Comment by nespera** [comment]
You do realise that pitest does not mutate Scala? See #267 for more.

**Comment by f9lz** [comment]
But I wonder if it has anything to do with Scala! This is a common problem which could be faced in Java as well.

**Comment by f9lz** [comment]
So it works now!

--I was creating a folder in my code. Every time i run a test, first coverage runs and next pit runs. 
--so coverage runs and creates a folder. (the code throws an error on an existing directory. )
--next when pit runs, it runs the code again to create a directory. it sees that the folder already exists.(Instead of yelling out that the folder already exists, it silently fails the build).
Solution -- I delete the folder at the beginning of my test. (Pit is happy to see no existing directory and runs the mutation and yayyyy the build is now a success)

**Comment by alexec** [comment]
You can mutate Scala, but there are a number of challenges and limitations around it. I'll put them into the other ticket.
