### ISSUE TITLE
pit homepage typo

### ISSUE THREAD

**Issue by i-make-robots** [hcoles/pitest#227]
Why?  "It is therefore only able to identify code the is definitely not tested."

**Comment by lkwg82** [comment]
what about a PR for the homepage project. See https://github.com/hcoles/pitest-site

**Comment by hansjoachim** [comment]
Looks like this was fixed in https://github.com/hcoles/pitest-site/commit/fafc8d0b4fbca819dbe09b049ab7b826ab53436f.

**Comment by lkwg82** [comment]
agree, can be closed
