### ISSUE TITLE
Is pitest supports testing multithreaded applications?

### ISSUE THREAD

**Issue by Sergey63** [hcoles/pitest#233]
Hi.
I'm try use pitest for testing my multithreaded application. I use Timer and TimerTask for perform subtasks. 
When i run test i have warning:
 "PIT >> INFO : SLAVE : 15:23:50 PIT >> WARNING : More threads at end of  test (18) _ than start. (7)"

And report wasn't generated. Is pitest supports testing multithreaded applications?

**Comment by hcoles** [comment]
Pitest does support testing multi-threaded applications.

The warning about threads is just a warning - if a test launches threads but doesn't ensure they terminate before the tests ends this may mean the suite is non deterministic (what are those threads doing, could they cause another test to fail?).

Are any errors displayed in the log? Which version of pitest are you using?

**Comment by Sergey63** [comment]
Main thread starts two TimerTask and then wait release semaphore. 
Second thread acquire semaphore, make a request to service, processes the request and then release semaphore. 
Third thread wait 10 seconds and сancel the second thread if it isn't finished, after that release semaphore. 

I haven't [error] in log. But build is failure with message:

"Execution default-cli of goal org.pitest:pitest-maven:1.1.4:mutationCoverage failed: No mutations found. This probably means there is an issue with either the supplied classpath or filters."

I use class from other maven module in the second thread. Is this may be cause?

**Comment by hcoles** [comment]
The problem is most likely an issue with the filters as the error message suggests.

Check what they are set to and that they will include the packages in your codebase (see the FAQ).

You also look to be using and older version of pitest (latest is 1.1.7). This is not the cause if your problem but you may wish to upgrade.

**Comment by Sergey63** [comment]
Henry, thank you for your answers! The root cause was some characters in path.
