### ISSUE TITLE
Could jopt-simple version be updated to 4.9?

### ISSUE THREAD

**Issue by jgodard-expedia** [hcoles/pitest#237]
Hi,

I'm running into an issue between pitest and wiremock when running pit thought the intelij plug-in, it seems if pitest were to use version 4.9 of jopt-simple it would address the conflict. 

The plug-in seem to pass all the classpath with all the jar in the project (incl. all dependencies, such as jopt-simple 4.9) as well as the jar it needs to run the plug-in (such as InteliJ plug-in stuff plus pitest-1.1.4.jar the plug-in rely on) to invoke pitest in the following way:

```/Library/Java/JavaVirtualMachines/jdk1.7.0_60.jdk/Contents/Home/bin/java -Didea.launcher.port=7532 "-Didea.launcher.bin.path=/Applications/IntelliJ IDEA 14.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath "<all the jars>" com.intellij.rt.execution.application.AppMain org.pitest.mutationtest.commandline.MutationCoverageReport --reportDir <report dir> --sourceDirs <source dir> --targetClasses <target classes> --outputFormats XML,HTML```

**Comment by hcoles** [comment]
This looks to be a bug in the intelij plugin. Pitest relocates all its dependencies using the maven shade plugin so conflicts should not occur.

Although it ought to be straightforward to upgrade the jopt-simple version pitest uses, a better fix would be for the intelij plugin not to pollute the classpath.

**Comment by hcoles** [comment]
I think the underlying issue needs to be fixed, but as there is no harm in doing so I've bumped the jopt-simple version to 4.9 for the next release.

**Comment by jgodard-expedia** [comment]
Thanks a lot. I reached out to the IntelliJ pitest plug-in developer, we will see what happens.

**Comment by hcoles** [comment]
Closing after release of 1.1.8
