### ISSUE TITLE
Issues with HTML reports

### ISSUE THREAD

**Issue by sebi-hgdata** [hcoles/pitest#242]
Hey,
   There are some inconsistent line numbers between the overall package report and the actual class report. The index file reports 355 lines but the actual MainRest class has 415.

See following images:
![index](https://cloud.githubusercontent.com/assets/11443582/11980069/a84e5a00-a9a0-11e5-8a53-5700897b58eb.png)
![class](https://cloud.githubusercontent.com/assets/11443582/11980078/c01cc996-a9a0-11e5-961b-e8369ce793b6.png)

I would like to help fixing this, if needed.

**Comment by sebi-hgdata** [comment]
Any thoughts in this ?

**Comment by szpak** [comment]
Line coverage in PIT (and in general) is calculated as a ratio of covered lines to a total number of lines which can be possibly covered (simplifying lines with effective code). For example the is no way to cover empty lines, so it would be misleading to count them to calculate line coverage (no way to get 100%).

To make a verification please manually calculate green and red lines in your class. There should be 255 those lines in total.

**Comment by sebi-hgdata** [comment]
I was not implying that it's something wrong with the coverage ratio.
There were definitely more that 255 lines in that class.. even without empty ones. But even if they were, showing 255 in one place and 455 in another can indicate that something is off/wrong. 
Also, line numbers should reflect the ones from compiler debug information and empty lines are counted there.

**Comment by KyleRogers** [comment]
I think your understanding of the numbers is wrong as @szpak tried to point out.

Your Class has 455 lines in total. Those lines include
a) lines with statements, e.g. `Object o = new Object();`
b) lines with declarations (only), e.g. `public void myMethod() {`
c) empty lines and lines with comments only

The 255 lines reported in the summary are the lines of type a) that means those lines that contain code with statements that could be executed. Coverage tools will give you the same results. For example look at the [Jacoco](http://eclemma.org/jacoco/trunk/coverage/jacoco-maven-plugin/org.jacoco.maven/AbstractAgentMojo.java.html) report. The AbstractAgentMojo class has 250 lines at the time of writing this. The coverage report reports 53 lines with 1 missed line.

Lines of types b) and c) are not counted because they do not contain executable code thus cannot contain any mutation. You cannot write any test that covers the line.

**Comment by sebi-hgdata** [comment]
Just one thing , look at the second mutant that was killed.

**Comment by KyleRogers** [comment]
Sorry @sebi-hgdata I cannot follow you?!?!

**Comment by sebi-hgdata** [comment]
There is a mutant at line 296.  The html reports only 255 lines. 
I'm a little bit disappointed, as I didn’t expect such input around this.

**Comment by hcoles** [comment]
@sebi-hgdata 

The mutant is on the 296th source code line. The source file contains 415 lines, of which 255 contain instructions. The remaining 160 lines are white space, comments and declarations.

The only alternative behaviour I can think of to the current one would be to report the line coverage as 253/415. (ie covered lines / source lines) in the summary report.

If the shown percentage was recalculated to match this then it could never be 100% (and would always be very low). Alternatively the percentage calculation could remain the same in which case it would not match the 253/415 ratio which would be confusing.

I think the current behaviour is far preferable and matches other coverage systems.

If you can suggest an alternate behaviour that improves on the current one I'd be happy to consider it.

**Comment by sebi-hgdata** [comment]
When I read 'line', my first taught is about source lines, not instructions, and this was the trigger for this issue.
Being clearer about the distinction of 'number of instructions' vs 'number of source lines' would help a lot. This can take the form of providing just percentages instead of '2 out of 10',  using 'Instruction Set Coverage ' instead of 'Line Coverage'(looked over jacaco and the same can be applied there), adding a 'Total Source Lines'

**Comment by hcoles** [comment]
253 is not a count of instructions. It is a count of lines that contain executable code. 

Each of these lines might have multiple instructions (in the sense of bytecode instructions). It might also contain multiple instructions (in the sense of java statements and expressions).

What is being measured is line coverage, not instruction/statement coverage.

**Comment by sebi-hgdata** [comment]
Using 'instruction' is unclear also, 'expression statements' would be the correct form as you pointed out (this was my intention to refer too).

In the context of 'line that contain executable code coverage' , having a list of expression statements like ```int x=0; x++; if(1!=0) return; x++;```  (all on the same line ) would result in coverage of 100%, because statements after the return do not count. Now, this kind of scenario is uncommon, but still proves that counting just lines with expression statements is not always correct.

Now, in the context of clarity, we can still do some report changes to be more specific on what it contains, at least to be more clear that we are not referring to source code lines.

**Comment by hcoles** [comment]
@sebi-hgdata I'm unclear about what changes you are suggesting to the report - could you provide an example?

Regarding your point about branch statements on a single line. This is a well known limitation of line coverage. Branch coverage solves this.

**Comment by sebi-hgdata** [comment]
Instead of 'Line coverage ' use 'Lines with expression statements coverage'

Re, branch coverage, I think it will not say that the last statement was not executed, as it applies only to control structures in a conceptual way.
A better generalization would be to check that all statements on a line are executed and ... just googling around it seem that there is the concept of "Statement coverage", and probably this is the more general concept that will say that the last statement on this example was not executed.

Anyway, thanks a lot for this discussion.
