### ISSUE TITLE
Can we switch the port used by PiTest

### ISSUE THREAD

**Issue by caligarisdesk** [hcoles/pitest#243]
I noticed that PIT uses port 8092.  Unfortunately, when running couchbase through vbox, pitest does not always detect that port 8092 is in use.  As a result, pitest hangs.

http://www.speedguide.net/port.php?port=8092
https://github.com/hcoles/pitest/blob/d4db5667cf802e280602b6bfd807272604f02a9e/pitest/src/main/java/org/pitest/util/SocketFinder.java#L25

I didn't see that one could change the default port used.  Can we add this as a parameter?

**Comment by caligarisdesk** [comment]
I'm not that familiar with socket libraries, but according to the SO below, should we also check DatagramSocket?

http://stackoverflow.com/questions/434718/sockets-discover-port-availability-using-java

**Comment by hcoles** [comment]
I think it might be possible to replace the whole thing with `new ServerSocket(0)`.

This would change to port range to something outside of pitest's control so it can't be parameterised, but should push the responsibility for finding an ephemeral port to the JDK.

**Comment by hcoles** [comment]
@caligarisdesk I've published a 1.1.8 snapshot, can you let me know if it resolves the issue.

**Comment by caligarisdesk** [comment]
Cool, thanks!  I'm having trouble pulling down a snapshot build, but as long as the port used keeps changing, it should work well for my configuration.

**Comment by hcoles** [comment]
@caligarisdesk 1.1.8 has now been released with this change. Can you report back if it has/hasn't resolved the issue.

**Comment by caligarisdesk** [comment]
Thanks for the release!  Just brought 1.1.8 via the gradle plug-in with the same vagrant/couchbase condition as before.  Pitest runs and completes successfully.
