### ISSUE TITLE
PIT does not support System classloader

### ISSUE THREAD

**Issue by drieselliott** [hcoles/pitest#253]
I have my surefire plugin configured like this:

```
<configuration>
    <useSystemClassLoader>true</useSystemClassLoader>
    <useManifestOnlyJar>false</useManifestOnlyJar>
</configuration>
```

Due to my set-up I can't get PIT to run with a green suite. Do you have any suggestions?

**Comment by hcoles** [comment]
Can you provide a bit more detail about your setup?

I've not played much with these setting in surefire myself. A quick google suggests you are probably try to work round a long classpath in windows. Is this correct?

**Comment by drieselliott** [comment]
I did some further testing and it seems that there was some kind of misconfiguration on my part the first time I set it up. Now everything seems to work fine.
