### ISSUE TITLE
Inline styles in HTML report violate Content Security Policy

### ISSUE THREAD

**Issue by jakub-bochenski** [hcoles/pitest#256]
Trying to view the report on a server with CSP enabled results in `Content Security Policy: The page's settings blocked the loading of a resource at self ("style-src https://acme.com").`

I'd be glad to send you a PR extracting the styles to a separate file if you consider it a viable improvement.

**Comment by hcoles** [comment]
I'd be happy to accept a PR thanks. 

It's possible that extracting the styles could cause issues in other scenarios (for the eclipse plugin perhaps?), so it would be preferable for this to be configurable.

**Comment by jakub-bochenski** [comment]
Great. This isn't a blocker for us so it will get back to this once I have some spare time

**Comment by hcoles** [comment]
Should be fixed in next release thanks to PR from @kiftio
