### ISSUE TITLE
Promote gradle quick start guide

### ISSUE THREAD

**Issue by mcandre** [hcoles/pitest#257]
Please add a gradle quick start link on the official Quickstart page, to make it easier for gradle users to learn pitest.

http://pitest.org/quickstart/

**Comment by KyleRogers** [comment]
The gradle plugin for pitest is maintained by @szpak and is not a part of pitest core. Documentation can be found `[here](http://gradle-pitest-plugin.solidsoft.info/)`

Maybe we could link to the project and documentation. Would that be sufficient @mcandre ?

What do you think @hcoles?

**Comment by mcandre** [comment]
> Would that be sufficient @mcandre ?

Yes!

**Comment by hcoles** [comment]
@mcandre I've added a link to the gradle plugin here http://pitest.org/quickstart/
