### ISSUE TITLE
Xstream dependency leaks Java 8 bytecode into pitest

### ISSUE THREAD

**Issue by philglover** [hcoles/pitest#262]
In commit ad1f0cfca7dbb2cb25352c1d3d6412a86ae8f726 (1.1.6 release) a number of dependencies were upgraded.  xstream moved from 1.4.2 to 1.4.8.

It appears that there is some java 8 bytecode in the xstream jar which is then shaded into pitest.  Pitclipse builds an OSGI bundle using Apache Felix, and after this change Felix identifies that Java 8 is a required capability:

Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.8))"

This means that to update Pitclipse to a later version of pitest brings in an unexpected dependency on Java 8.

Rolling back xstream to 1.4.2 changes the requirement down to Java 6.

Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.6))"

**Comment by hcoles** [comment]
Sounds like you've been through some painful debugging.

I'd prefer not to roll back the version of xstream if possible as there have been some bugs in it that PIT users have run into, such as this one.

http://x-stream.github.io/jira/761/

Do you know which classes contain the bytecode and their purpose? It may be possible to shade them out.

**Comment by philglover** [comment]
Thankfully after learning the power of git bisect, the problem space became a lot easier to identify.  I wasn't aware of the issues caused by 1.4.2 .  Let me evaluate a couple of other alternatives and I'll get back to you.

**Comment by philglover** [comment]
The required java capability can be disabled in felix so I have done that instead.  If I get time, I'll work out the xstream lib issue as they advertise it being Java 6 compliant
