### ISSUE TITLE
Can't resolve JUnit dependency

### ISSUE THREAD

**Issue by jeandersonbc** [hcoles/pitest#265]
Hi,

I've cloned some Maven Java projects from Github to give a try on pitest but I'm unable to execute pitest:

`[ERROR] Failed to execute goal org.pitest:pitest-maven:1.1.9:mutationCoverage (default-cli) on project guava: Execution default-cli of goal org.pitest:pitest-maven:1.1.9:mutationCoverage failed: No test library found on classpath. PIT requires either JUnit 4 (but can run JUnit 3 tests) or TestNG
[ERROR] See http://pitest.org for more details.`

However, after cloning [Guava](https://github.com/google/guava.git), running `mvn clean install` and `mvn test`, runs smoothly.

I'm not a Maven expert, but I don't understand why the pitest plugin doesn't understand the JUnit if tests run out-of-the-box.

Any help?

Thanks in advance

**Comment by hcoles** [comment]
The most likely problem is that the project is using JUnit3.

Which projects are you seeing this error for?

**Comment by jeandersonbc** [comment]
Hi @hcoles, thanks for the promptly reply :smile: 

I just attempted to use on Guava (https://github.com/google/guava) first.
After cloning the project and running "mvn test", it executes all tests from the project

In the root pom.xml file (https://github.com/google/guava/blob/master/pom.xml) you can see the JUnit 4 dependency declaration.

I thought that by just adding the PIT plugin entry on the same pom file, I would be able to execute PIT mvn goals. There must be something that I'm missing but I can't see what it is exactly.

What I'm really interested is in running tests against mutated code. I'm looking for a systematic way to generate mutations. I am aware that PIT do this but on bytecodes and I've seen this thread (https://groups.google.com/forum/#!msg/pitusers/9MB4ZUhUJ34/SeECRxKqQo4J). However, before using PIT for my experiments, I wanted to try it and understand what it does and how does it works.

**Comment by hcoles** [comment]
Guava looks to have all its units tests in a separate module. 

This is highly unusual for a java projects, unless there is some technological constraint unit tests are normally placed in the same module as the code (for maven and gradle projects usually under src/test/java).

At the moment PIT doesn't support unconventional projects such as this out of the box, but with some work you ought to be able to mutate it using the command line client.

**Comment by jeandersonbc** [comment]
@hcoles Good to know. Maybe this information should be added in the "Quick-start for Maven" page.
I will see if I can tweak some code from PIT for mutant generation since I'm really interested running the same set of mutants against a particular test suite :)

By the way, does PIT generates mutants in a deterministic way? In another words, given the default settings and a given target class, does PIT produces the same sequence of generated mutants?

**Comment by hcoles** [comment]
Yes PIT generates mutants in a fully deterministic way - PIT will always generate the same mutants for the same input.

**Comment by jeandersonbc** [comment]
@hcoles thanks for the promptly response and the assistance
I believe you can close this thread now :smile:
