### ISSUE TITLE
Scala support

### ISSUE THREAD

**Issue by alexec** [hcoles/pitest#267]
Hi,

Can I please ask, has there been any recent attempts to try PIT with Scala code bases and SBT? I can see the SBT plugin has not been updated for some time.

Alex

**Comment by alexec** [comment]
OK. So, I've done some spiking

SBT is a popular Scala build tool. So, firstly I [forked](https://github.com/alexec/sbt-pit) the existing SBT Pit plugin, and updated to latest PIT. 

I wanted to see if it worked with the built in test frameworks. So I created an [SBT project](https://github.com/alexec/sbt-pit-junit-example) using Unit with a mixture of simple Java and Scala classes. 

ScalaTest is a popular Scala test framework. To be practically, like SBT, we need to support this. So I created a [basic plugin](https://github.com/alexec/pitest-scalatest-plugin) for it.

Finally, I created [a project](https://github.com/alexec/sbt-pit-scalatest-example) to test SBT with ScalaTest.

After that, I ran it with a realistic code-base. I found some interesting things:

* Case classes have lots of missed lines of code. This is just like Lombok @Data classes. No surprise here.
* Some mutators are not used:

```
================================================================================
- Statistics
================================================================================
>> Generated 11537 mutations Killed 175 (2%)
>> Ran 486 tests (0.04 tests per mutation)
================================================================================
- Mutators
================================================================================
> org.pitest.mutationtest.engine.gregor.mutators.ConditionalsBoundaryMutator
>> Generated 4 Killed 2 (50%)
> KILLED 2 SURVIVED 1 TIMED_OUT 0 NON_VIABLE 0 
> MEMORY_ERROR 0 NOT_STARTED 0 STARTED 0 RUN_ERROR 0 
> NO_COVERAGE 1 
--------------------------------------------------------------------------------
> org.pitest.mutationtest.engine.gregor.mutators.VoidMethodCallMutator
>> Generated 2840 Killed 0 (0%)
> KILLED 0 SURVIVED 32 TIMED_OUT 0 NON_VIABLE 0 
> MEMORY_ERROR 0 NOT_STARTED 0 STARTED 0 RUN_ERROR 0 
> NO_COVERAGE 2808 
--------------------------------------------------------------------------------
> org.pitest.mutationtest.engine.gregor.mutators.ReturnValsMutator
>> Generated 8240 Killed 148 (2%)
> KILLED 148 SURVIVED 176 TIMED_OUT 0 NON_VIABLE 0 
> MEMORY_ERROR 0 NOT_STARTED 0 STARTED 0 RUN_ERROR 0 
> NO_COVERAGE 7916 
--------------------------------------------------------------------------------
> org.pitest.mutationtest.engine.gregor.mutators.MathMutator
>> Generated 111 Killed 0 (0%)
> KILLED 0 SURVIVED 15 TIMED_OUT 0 NON_VIABLE 0 
> MEMORY_ERROR 0 NOT_STARTED 0 STARTED 0 RUN_ERROR 0 
> NO_COVERAGE 96 
--------------------------------------------------------------------------------
> org.pitest.mutationtest.engine.gregor.mutators.NegateConditionalsMutator
>> Generated 342 Killed 25 (7%)
> KILLED 25 SURVIVED 13 TIMED_OUT 0 NON_VIABLE 0 
> MEMORY_ERROR 0 NOT_STARTED 0 STARTED 0 RUN_ERROR 0 
> NO_COVERAGE 304 
--------------------------------------------------------------------------------
```

**Comment by hcoles** [comment]
I spent some time a couple of years ago looking at adding Scala support to PIT with a vague plan to make it a commercial add on. 

I produced a working spike, but decided not to continue as the cost of supporting it looked likely to be very high.

The main issue is that a large percentage of mutations are junk once you start using any of Scala's language features as they are mutations in scaffolding code generated by the compiler rather than code that can be linked back to logic implemented by the user. These have to be filtered out. It was possible to identify them via various tricks in many (but not all) cases, but there was no guarantee that these tricks would keep working as the scala compiler evolved.

The other problem was type erasure. This is an issue when mutating Java, but is a bigger issue when mutating Scala due to the more advanced type system coupled with the higher likelihood that scala programs would exercise it. This might be solvable using the data stored in the annotations added by the compiler but more investigation is needed there.

I suspect mutating Scala would be best done as a compiler plugin rather than by bytecode manipulation.

**Comment by mbj** [comment]
Agreed.

I think that languages that do *not* have a very close mapping from AST to bytecode (Java has it for example) is better done at the AST level.

**Comment by alexec** [comment]
Interesting. I'm also wondering about demand for Scala support. I could not find much on the Internet about it. If there's no demand, regardless of how interesting a technical problem it is, if no one want it, it would not be worthwhile supporting.

"Junk" mutations are a problem in Java, as they produce a high number of false issues (e.g. code covered by e2e tests, but not by any test unit used by PIT). If useful mutation get buried by junk mutations, then the practical usefulness is reduced.

@hcoles do you still have the spike code?

**Comment by hcoles** [comment]
Mutations in code only covered by e2e tests are not junk - they are legitimately telling you that there is logic not tested by your unit tests. Integration code can usually be kept within separate from unit-testable code, so ignoring it ought to be a case of excluding packages from the analysis.

The junk created for Scala is different. It is logic that the programmer didn't actually write and it is intermingled with the code that they did.

I'm also not sure there would be a much general demand for mutating Scala. 

I do have the spike code somewhere, not sure if I'm ready to release it into the open yet though.

**Comment by mbj** [comment]
> Mutations in code only covered by e2e tests are not junk - they are legitimately telling you that there is logic not tested by your unit tests. Integration code can usually be kept within separate from unit-testable code, so ignoring it ought to be a case of excluding packages from the analysis.

+1

> The junk created for Scala is different. It is logic that the programmer didn't actually write and it is intermingled with the code that they did.

Another way to say this: Mutations on the bytecode level might NOT have a corresponding source representation, when the source is not mostly 1:1 (as with Java and Java bytecode is mostly the case).

And as Scala is in many was much more high level than Java, the mutations to bytecode from Scala might not be as relevant as mutations to bytecode from Java.

**Comment by alexec** [comment]
Thank you Mr Coles. 

I agree about your interpretation of "junk".  I don't think my comments are clear. E2e tests are slower, and you're correct -- we've tended to exclude them, and the infrastructure code from analysis.

I've used PiTest extremely successfully on several projects, and it's been key in finding serious bugs (and seriously bad tests :) ) in real world applications, both micro-services and monoliths. Things you would not have wanted to go live. I'm a massive fan and would strongly recommend for any project. It's been especially useful where we have domain logic in the application (lots of if statements, conditionals).

I'm going to shelve this experiment for the moment. 

Thank you for taking time to reply, no everyone does on Github.

**Comment by hcoles** [comment]
@alexec If any of the organisations those projects were for could provide a quote for the website it would be much appreciated.

**Comment by alexec** [comment]
@hcoles -- I don't currently work for a company using it, but I'll drop an email to a colleague and see if they're interested.

**Comment by hcoles** [comment]
I'm currently working on adding a small library to pitest that allows easy matching of bytecode sequences. The initial use case for this is to detect infinite loops without executing any tests, but the intent is to create something that allows simple static analysis checks to be added to pitest with relative ease.

This duplicates a lot of what the scala spike was doing. It should be relatively straightforward to port the scala filters over to the new system.

I don't have time to work on support Scala however (and I think there will always be issues trying to do it at the bytecode level), so this would require some-one else to be willing to take ownership of it.

**Comment by nespera** [comment]
I'm interested in Scala mutation in pitest. I don't have the time to take ownership of the thing, but would be able to lend a hand if someone else steps up to the plate...

**Comment by alexrosenfeld10** [comment]
@nespera Not sure if you've found this, but there's a project [here ](https://github.com/sugakandrey/scalamu) that offers support. I know this doesn't solve the issue at hand, but may work as a placeholder until pitest has Scala support.

**Comment by pedrorijo91** [comment]
haven't tested it yet, but stryker also supports scala recently: http://stryker-mutator.io/stryker4s/
