### ISSUE TITLE
PIT 1.1.10 maxSurviving issues

### ISSUE THREAD

**Issue by tbuchber** [hcoles/pitest#269]
I tested PIT 1.1.10. I love that I can now set maxSurviving. However, I did find a couple of issues.

1.The minimum maxSurviving value supported is 1. I really want to set it to 0. However, line 387 in pitest/AbstractPitMojo.java [if ((this.maxSurviving > 0)] limits maxSurviving to >=1.

2.The message at failure is displaying the incorrect number of max survivors. Line 391 in pitest/AbstractPitMojo.java is displaying mutationThreshold instead of maxSurviving.

**Comment by theangrydev** [comment]
Would setting <mutationThreshold>100</mutationThreshold> achieve what you want instead?

**Comment by hcoles** [comment]
@theangrydev maxSurviving was introduced as the threshold doesn't quite allow you the break the build on a surviving mutant due to rounding.

It sounds like it is impressively broken for such as simple feature. I'll put out a fix when I get chance, or am happy to accept a PR.

**Comment by tbuchber** [comment]
Your fixes look correct to me. Thanks for the fixes. I look forward to trying 1.1.11. Thank you!
