### ISSUE TITLE
Windows Reports Tests Failure while Ubuntu doesn't

### ISSUE THREAD

**Issue by rnveach** [hcoles/pitest#272]
I am trying to test out pitest on a project I work on in Windows, and pitest reports that the suite isn't green, but the same branch in an Ubuntu VM completes successfully. Both have the same maven version.

The project and test branch: https://github.com/rnveach/checkstyle/tree/pitest
pitest configuration: https://github.com/rnveach/checkstyle/commit/9f39f4be4af9e05e6978b38df5b9a1dc25677a5a

The tests I run through Window's maven all pass with `mvn test`.
````
-------------------------------------------------------
 T E S T S
-------------------------------------------------------

Results :

Tests run: 1842, Failures: 0, Errors: 0, Skipped: 1

[INFO] 
[INFO] --- xml-maven-plugin:1.0.1:validate (default) @ checkstyle ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
````

I tried turning on debugging in maven when running pitest and pitest's verbose, but nothing new gets reported to point to the tests that fail (that I could find) or the issue.

Can pitest report the failing tests, with any pertinent information like maven would when running these tests (which class and method failed and any assertion they get)?
This may at least guide me to where the issue is.

I have attached maven output of `org.pitest:pitest-maven:mutationCoverage`.
[output.txt](https://github.com/hcoles/pitest/files/311022/output.txt)

**Comment by hcoles** [comment]
The coverage stage stops when a test fails, so your failing test is most likely com.puppycrawl.tools.checkstyle.utils.TokenUtilsTest.testTokenValueIncorrect2.

The most common reason for tests failing at the coverage stage are

a) Problem tests getting picked up that aren't usually run
b) Test order dependencies in the suite
c) An issue with an unusual test runner

As it's running ok for you on linux a and c are ruled out, so it's either a test order dependency or something I've not seen before.

I can't think of a reason why the order would be different between windows and linux, but this is possible.

If I can find a windows machine I'll try and dig into this. Not sure where I'll find one though.

**Comment by rnveach** [comment]
@hcoles 
> The coverage stage stops when a test fails, so your failing test is most likely com.puppycrawl.tools.checkstyle.utils.TokenUtilsTest.testTokenValueIncorrect2.

Either `stops when a test fails` is incorrect, or something else is wrong.
After removing the method in question still caused pitest to fail, I removed the entire test class. Pitest's last test is now `ScopeUtilsTest`, which was in my original output, and pitest is still saying the suite isn't green.
As far as I can tell, the test order looks the same from the first run except `TokenUtilsTest` tests aren't listed.

> c) An issue with an unusual test runner

This could be the cause as I have seen this type of issue on Windows before, where a custom runner on windows failed but passed on linux, but I would think that would show up during `mvn test` unless pitest is interfering somehow.
Some type of display saying "this test failed" in pitest's log would help with this. Until then, I will try deleting random/all tests to find the culprit.

> order would be different between windows and linux

I will see if this is true when I get the chance.

**Comment by rnveach** [comment]
I was able to get pitest past the green suite issue by deleteing:
* com.puppycrawl.tools.checkstyle.utils.CommonUtilsTest
* com.puppycrawl.tools.checkstyle.internal.XDocsPagesTest

One uses `PowerMockRunner`, the other doesn't. I will see if I can identify a way to see if it is an order issue.

**Comment by rnveach** [comment]
I am closing this issue. It looks like it is a test order issue between 3 tests.
* `com.puppycrawl.tools.checkstyle.MainTest.testDebugOption`
* `com.puppycrawl.tools.checkstyle.internal.XDocsPagesTest.testAllCheckSections`
* `com.puppycrawl.tools.checkstyle.internal.XDocsPagesTest.testAllXmlExamples`

````
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.puppycrawl.tools.checkstyle.internal.XDocsPagesTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.962 sec - in com.puppycrawl.tools.checkstyle.internal.XDocsPagesTest
Running com.puppycrawl.tools.checkstyle.MainTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.162 sec - in com.puppycrawl.tools.checkstyle.MainTest



6:17:33 PM PIT >> INFO : MINION : 6:17:33 PM PIT >> FINE : Running 3 units
6:17:33 PM PIT >> INFO : MINION : 6:17:33 PM PIT >> FINE : Gathering coverage for test Description [testClass=com.puppycrawl.tools.checkstyle.MainTest, name=com.puppycrawl.tools.checkstyle.MainTest]
6:17:37 PM PIT >> INFO : MINION : 6:17:37 PM PIT >> FINE : Gathering coverage for test Description [testClass=com.puppycrawl.tools.checkstyle.internal.XDocsPagesTest, name=testAllCheckSections(com.puppycrawl.tools.checkstyle.internal.XDocsPagesTest)]
6:17:39 PM PIT >> INFO : MINION : 6:17:39 PM PIT >> FINE : Gathering coverage for test Description [testClass=com.puppycrawl.tools.checkstyle.internal.XDocsPagesTest, name=testAllXmlExamples(com.puppycrawl.tools.checkstyle.internal.XDocsPagesTest)]
6:18:12 PM PIT >> FINE : MINION : FAIL Description [testClass=com.puppycrawl.tools.checkstyle.internal.XDocsPagesTest, name=testAllXmlExamples(com.puppycrawl.tools.checkstyle.internal.XDocsPagesTest)] -> java.lang.OutOfMemoryError: Java heap space
````

Removing any of the 3 tests makes the suite green. 
Somehow the first 2 are causing `XDocsPagesTest.testAllXmlExamples` to be the point of failure.

I still don't know the exact cause for why the test fails, but I have actually created a workaround in `MainTest` that makes everything green and pitest. I believe it is because one of our tests, one I created in fact, leaves logging on max and doesn't reset it back for future tests. https://github.com/rnveach/checkstyle/commit/9e90543ff6b345530b1f880ef516ed831e1164d3

As for the order of tests in Linux versus Windows, there doesn't seem to be an order difference. So something else is causing Windows to fail and Linux to pass.
