### ISSUE TITLE
How to mock final class method

### ISSUE THREAD

**Issue by Tanushree-Mishra** [hcoles/pitest#274]
Can you please give example how to mock final class method

**Comment by hcoles** [comment]
@Tanushree-Mishra Pitest is not a mocking framework, could you give a bit more detail on what the issue is that you're encountering?

**Comment by Tanushree-Mishra** [comment]
Hi 
I am trying to mock a method in final class such that it will return the desire result. Is there anyway to do the same?

Thanks
Tanushree

**Comment by hcoles** [comment]
Something like powermock will let you do this. Pitest is not a mocking framework, so will not.

**Comment by lkwg82** [comment]
this can be closed
