### ISSUE TITLE
Is there any way i can check mutators of math operation done on local variables inside a method

### ISSUE THREAD

**Issue by Tanushree-Mishra** [hcoles/pitest#275]
Hi
Is there any way i can check mutators of math operation done on local variables inside a method

Thanks
Tanushree
![mutation_issue](https://cloud.githubusercontent.com/assets/19972099/16219943/3e69fc4e-37a7-11e6-8bfb-cf944144f419.png)

**Comment by Tanushree-Mishra** [comment]
hi 
any suggestion how to write mutation test case for this method.

Thanks
Tanushree

**Comment by KyleRogers** [comment]
Hi,

if you have questions, you can post them at the mailing list/user group: https://groups.google.com/forum/#!forum/pitusers
GitHub issues should be used to report bugs and errors.

-----
The surviving mutants are telling you that you don't have test cases in place that check the calculation in your method. You need some tests that clearly check the return value ("str") for the correct year used and the current time/time zone used.
Maybe some test like

```
final String FINAL_YEAR = <precalculated value expected in output>
final String EXPECTED_UTCOID_START = MediationConstant.ELEMENT_OID  + "." + FINAL_YEAR;
final String result = testedObject.createUTCOID();

assertThat(result, startsWith(EXPECTED_UTCOID_START));
```
I hope that will give you the clue you need.  Your snippet is not telling the whole story thus I cannot be more precise.

**Comment by Tanushree-Mishra** [comment]
Thanks a lot for the suggestion... It worked
