### ISSUE TITLE
Classpath too long on windows

### ISSUE THREAD

**Issue by iwarapter** [hcoles/pitest#276]
I have a project with a very large number of dependencies, when we try to run pitest (using the gradle plugin) we get:

```
CreateProcess error=206, The filename or extension is too long
```

I tried resolving this by instead providing a fat jar with all the dependencies and the appropriate manifest Class-Path but no joy, i ended up getting:

```
No test library found on classpath. PIT requires either JUnit 4 (but can run JUnit 3 tests) or TestNG
```

Is there another work around to deal with the windows limit on command length?

**Comment by iwarapter** [comment]
Have you had a chance to look into this? I'd be happy to help provide support for a pathing jar if you can point me at the right place to implement it.

**Comment by hcoles** [comment]
Sorry not had time to look at this.

This might be just a case of getting pitest to recognise the Class-Path manifest header, which could be as simple as some sort of change to the crusty old code in -

https://github.com/hcoles/pitest/blob/8f654ad3849d5dc5b7cbe59dddea788d19ded317/pitest/src/main/java/org/pitest/classpath/ClassPath.java

Or it could be a bit more involved. It will probably require a some experimentation.

**Comment by luisa123456** [comment]
Long Path Tool is the perfect utility that can solve all the long path issues. Download this software online.

**Comment by hcoles** [comment]
@iwarapter does the fix in #289 resolve this for you?

**Comment by viswaramamoorthy** [comment]
Try https://github.com/viswaramamoorthy/gradle-util-plugins

**Comment by szpak** [comment]
@iwarapter It's fixed in PIT itself, but unfortunately it is broken in the current Gradle plugin version. You can see the discussion and a possible workaround [here](https://github.com/szpak/gradle-pitest-plugin/issues/50#issuecomment-276675197).

To get notification when this issue is fixed please subscribe to [#56](https://github.com/szpak/gradle-pitest-plugin/issues/56) (I propose to fix that issue).

**Comment by szpak** [comment]
@iwarapter It should be fixed in just released version 1.2.2 of the plugin.

**Comment by Bleki** [comment]
With version 1.4.8 it got broken by me. With previous version (1.4.7) it still works fine.

**Comment by szpak** [comment]
@Bleki The previous comment is dated to 2017. Please report the repression in a separate issue. If you use the Gradle plugin in [its issue tracker](https://github.com/szpak/gradle-pitest-plugin/issues), otherwise in this repo.

**Comment by szpak** [comment]
Unless @iwarapter did not agree, this problem should have been already fixed for 3 years+ and that issue could be closed.
