### ISSUE TITLE
Is there any way to write mutation check for operations done on local variables

### ISSUE THREAD

**Issue by Tanushree-Mishra** [hcoles/pitest#277]
Hi
Is there any way to write mutation check for operations done on local variables?

Thanks
Tanushree

![mutation_issue](https://cloud.githubusercontent.com/assets/19972099/16294541/d4643906-393e-11e6-8ff3-b624b025a1c1.png)

**Comment by KyleRogers** [comment]
See my answer at https://groups.google.com/forum/#!topic/pitusers/FQ6gjWWvvuQ

Regards
Stefan

**Comment by Tanushree-Mishra** [comment]
Hi
I tried with both valid and invalid path for file existence getting checked inside a void method. But still mutants are getting survived.

attached the sample project.
[SampleJunit.zip](https://github.com/hcoles/pitest/files/331533/SampleJunit.zip)

![filecheck_mutation](https://cloud.githubusercontent.com/assets/19972099/16334043/5e8819bc-3a1c-11e6-96d4-f486a37c8baf.png)
