### ISSUE TITLE
Bug: Some "removed call to" mutations claim to have been killed but actually weren't

### ISSUE THREAD

**Issue by theangrydev** [hcoles/pitest#282]
I don't have a minimal example yet, will put one up when I get time

**Comment by theangrydev** [comment]
Are the mutations generated always independent? 

By that I mean, are two mutations ever applied at the same time or will they always be applied individually to a fresh copy of the class?

I can't isolate the issue well unfortunately. 

I have seen this today on a large suite of tests where if I manually mutate the class in the way pitest claims it has, then the test listed under "Tests examined" in the report remains green.

The mutation is "removed call to" and the active mutators I have are:
REMOVE_CONDITIONALS_EQUAL_ELSE_MUTATOR
INCREMENTS_MUTATOR
VOID_METHOD_CALL_MUTATOR
RETURN_VALS_MUTATOR
REMOVE_CONDITIONALS_ORDER_ELSE_MUTATOR
MATH_MUTATOR
NEGATE_CONDITIONALS_MUTATOR
INVERT_NEGS_MUTATOR
CONDITIONALS_BOUNDARY_MUTATOR
REMOVE_CONDITIONALS_ORDER_IF_MUTATOR
REMOVE_CONDITIONALS_EQUAL_IF_MUTATOR

There are several calls to a logger that, if removed, will not cause any tests to fail, but pitest thinks it has killed those mutations. I can add any number of additional uncovered logger calls and they are also incorrectly identified as killed.

There are some "removed conditional" and "negated conditional" mutations that are correctly killed.

Not an awful lot of information for you to go on here... I'll update this if I find anything else out.

**Comment by theangrydev** [comment]
It could be because I am using <threads>5</threads> and have a shared resource that I haven't accounted for. I'll look into that and let you know.

**Comment by theangrydev** [comment]
I ran my suite with `<threads>1</threads>` and pitest behaved as expected. Looks like a problem with my test suite not pitest, so closing this issue

**Comment by ShrutiJoshi112** [comment]
Hello, I am having a similar kind of issue. In most of my project files it shows "removed call to 'a specific code line'--> SURVIVED".
Not sure how to cover these lines, if you could please help
