### ISSUE TITLE
pitest should ignore abstract test classes

### ISSUE THREAD

**Issue by estekhin** [hcoles/pitest#295]
https://github.com/hcoles/pitest/blob/master/pitest/src/main/java/org/pitest/testng/TestNGTestUnitFinder.java (and probably similar classes for JUnit) should ignore abstract classes even if these classes contain test annotations.

When running, such abstract "test" classes will fail to instantiate, and pitest will report "org.pitest.help.PitHelpError: All tests did not pass without mutation when calculating line coverage. Mutation testing requires a green suite.".

Besides checking whether the candidate class is non-abstract, pitest should also check whether the class has no-arg constructor.

**Comment by hcoles** [comment]
Released in 1.2.0
