### ISSUE TITLE
Using JUnit @Test(expected=*Exception.class) leads to "Mutation testing requires a green suite."

### ISSUE THREAD

**Issue by lstosik** [hcoles/pitest#299]
With such annotation JUnit passes the test when exception is thrown but `pitest` thinks exception means failure. I am not sure if it is supposed to be supported if not it would be nice to get a warning about it.

**Comment by hcoles** [comment]
Pitest supports JUnit expected exceptions (I've just double checked with a simple test with release 1.10), so I think you the issue you are encountering is something different.

Can you put together a minimal project that reproduces the issue?

**Comment by lstosik** [comment]
It ended being some order dependency between tests, sorry for invalid report.
