### ISSUE TITLE
Question about constant mutators

### ISSUE THREAD

**Issue by theangrydev** [hcoles/pitest#310]
Will the Inline Constant Mutator mutate the "magic string" in the following?
```java
foo("magic string");
```

```java
private static final String FOO = "magic string";
```

I'm also interested in whether the Experimental Member Variable Mutator might overlap in the second case?

**Comment by theangrydev** [comment]
The intent here is to be able to detect missing test coverage of magic constants, which would be a very powerful tool to have

**Comment by hcoles** [comment]
The inline constant mutator doesn't touch string constants.

It should however be possible to write something that does.

**Comment by theangrydev** [comment]
Great, I'll have a go at implementing that when I get some time

**Comment by bcisneros** [comment]
@theangrydev Did you open an issue to include this feature?
I am interested to have this feature, so if you need some help please let me know or I can create and work on it if you don't mind.

**Comment by theangrydev** [comment]
No, I have not had the chance to look at this. Feel free to take ownership of it :+1:

**Comment by bcisneros** [comment]
Thanks. Did you have any start point I need to check? If not, don't worry I will check the project structure to learn from scratch.

**Comment by theangrydev** [comment]
You could start by looking at how the [existing mutators](https://github.com/hcoles/pitest/tree/master/pitest/src/main/java/org/pitest/mutationtest/engine/gregor/mutators) are implemented.

**Comment by bcisneros** [comment]
Cool, thanks again
