### ISSUE TITLE
How to fix this Compile Error: Failure to find org.pitest:pitest-build-config:jar

### ISSUE THREAD

**Issue by cocowhy1013** [hcoles/pitest#311]
### I am using "mvn clean compile" trying to compile source code of this project, especially pitest package and suffer from this failure. How can I fix this? It seems to be some source jar missing in market.

E:\Tool\PIT\pitest-master\pitest-master>mvn clean compile -rf :pitest
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] pitest
[INFO] pitest-html-report
[INFO] pitest-maven
[INFO] pitest-command-line
[INFO] pitest-ant
[INFO] pitest-maven-verification
[INFO] pitest-groovy-verification
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building pitest 1.1.11-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ pitest ---
[INFO] Deleting E:\Tool\PIT\pitest-master\pitest-master\pitest\target
[INFO]
[INFO] --- maven-checkstyle-plugin:2.15:check (checkstyle) @ pitest ---
[WARNING] The POM for org.pitest:pitest-build-config:jar:1.1.11-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] pitest ............................................. FAILURE [  1.209 s]
[INFO] pitest-html-report ................................. SKIPPED
[INFO] pitest-maven ....................................... SKIPPED
[INFO] pitest-command-line ................................ SKIPPED
[INFO] pitest-ant ......................................... SKIPPED
[INFO] pitest-maven-verification .......................... SKIPPED
[INFO] pitest-groovy-verification ......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.479 s
[INFO] Finished at: 2016-11-16T19:40:35+08:00
[INFO] Final Memory: 11M/26M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.15:check (checkstyle) on project pitest: Execution checkstyle of goal org.apache.maven.plugins:maven-checkstyle-plugin:2.15:check failed: Plugin org.apache.maven.plugins:maven-checkstyle-plugin:2.15 or one of its dependencies could not be resolved: 
**Failure to find org.pitest:pitest-build-config:jar:1.1.11-SNAPSHOT in http://repository.apache.org/snapshots was cached in the local repository**, 
resolution will not be reattempted until the update interval of apache.snapshots has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException

**Comment by hansjoachim** [comment]
The module `pitest-build-config` is part of the pitest-project, but the `compile` step won't create a jar file of it and store it somewhere. So when you get to the next module which requires `pitest-build-config`, maven has already forgotten about it and cannot find it. Could you try `mvn clean install`? This will package up and add the jar files to your local maven repository, making them available for other modules (or project) you want to build. Latest master built succesfully for me. :)

**Comment by rnveach** [comment]
I get the same error when doing `clean install` on the root directory when running maven using eclipse's built in maven.

````
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T11:41:47-05:00)
Maven home: M:\pitestWorkspace\pitest\EMBEDDED
Java version: 1.8.0_152, vendor: Oracle Corporation

[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building pitest 1.4.6-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ pitest ---
[INFO] 
[INFO] --- maven-checkstyle-plugin:2.15:check (checkstyle) @ pitest ---
[INFO] Downloading: http://repository.apache.org/snapshots/org/pitest/pitest-build-config/1.4.6-SNAPSHOT/maven-metadata.xml
[INFO] Downloading: http://repository.apache.org/snapshots/org/pitest/pitest-build-config/1.4.6-SNAPSHOT/pitest-build-config-1.4.6-SNAPSHOT.pom
[WARNING] The POM for org.pitest:pitest-build-config:jar:1.4.6-SNAPSHOT is missing, no dependency information available
[INFO] Downloading: http://repository.apache.org/snapshots/org/pitest/pitest-build-config/1.4.6-SNAPSHOT/pitest-build-config-1.4.6-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.717 s
[INFO] Finished at: 2019-02-11T19:43:14-05:00
[INFO] Final Memory: 14M/307M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.15:check (checkstyle) on project pitest: Execution checkstyle of goal org.apache.maven.plugins:maven-checkstyle-plugin:2.15:check failed: Plugin org.apache.maven.plugins:maven-checkstyle-plugin:2.15 or one of its dependencies could not be resolved: Could not find artifact org.pitest:pitest-build-config:jar:1.4.6-SNAPSHOT in apache.snapshots (http://repository.apache.org/snapshots) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
````

Running the command outside eclipse solved the issue but then the install failed in the 3rd entry named `pitest`. I get the following errors:
````
Apache Maven 3.2.1 (ea8b2b07643dbb1b84b6d16e1f08391b666bc1e9; 2014-02-14T12:37:5
2-05:00)
Maven home: D:\Program Files\apache-maven-3.2.1
Java version: 1.8.0_171, vendor: Oracle Corporation
Java home: D:\Program Files\JDK8\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "x86", family: "dos"

....

Results :

Failed tests:
  CRCR1Test.shouldReplaceIntegerLdcWith1:197->MutatorTestBase.getFirstMutant:161
->MutatorTestBase.getFirstMutant:152 No mutant found
  CRCR2Test.shouldReplaceIntegerLdcWith0:197->MutatorTestBase.getFirstMutant:161
->MutatorTestBase.getFirstMutant:152 No mutant found
  CRCR3Test.shouldReplaceIntegerLdcWithMinus1:197->MutatorTestBase.getFirstMutan
t:161->MutatorTestBase.getFirstMutant:152 No mutant found
  CRCR4Test.shouldReplaceIntegerLdcWithMinusConstant:197->MutatorTestBase.getFir
stMutant:161->MutatorTestBase.getFirstMutant:152 No mutant found
  CRCR5Test.shouldReplaceIntegerLdcWithConstantPlus1:198->MutatorTestBase.getFir
stMutant:161->MutatorTestBase.getFirstMutant:152 No mutant found
  CRCR6Test.shouldReplaceIntegerLdcWithConstantMinus1:198->MutatorTestBase.getFi
rstMutant:161->MutatorTestBase.getFirstMutant:152 No mutant found
  ManifestUtilsTest.shouldParseTheManifestsItCreates:16
Expecting:
  <[M:\some\path\foo.jar:\some\path]>
to contain exactly (and in same order):
  <[M:\some\path\foo.jar, M:\some\path]>
but some elements were not found:
  <[M:\some\path\foo.jar, M:\some\path]>
and others were not expected:
  <[M:\some\path\foo.jar:\some\path]>


Tests in error:
  CRCR1Test.shouldReplaceLargeIntegerConstantsWith1:134 » NoClassDefFound org/pi
...
  CRCR2Test.shouldReplaceLargeIntegerConstantsWith0:134 » NoClassDefFound org/pi
...
  CRCR3Test.shouldReplaceLargeIntegerConstantsWithMinus1:135 » NoClassDefFound o
...
  CRCR4Test.shouldReplaceLargeIntegerConstantsWithMinusConstant:134 » NoClassDef
Found
  CRCR5Test.shouldReplaceLargeIntegerConstantsWithConstantPlus1:135 » NoClassDef
Found
  CRCR6Test.shouldReplaceLargeIntegerConstantsWithConstantMinus1:135 » NoClassDe
fFound

....

[INFO] Reactor Summary:
[INFO]
[INFO] pitest-parent ..................................... SUCCESS [  0.631 s]
[INFO] Build Config ...................................... SUCCESS [  4.222 s]
[INFO] pitest ............................................ FAILURE [01:15 min]
````
