### ISSUE TITLE
exclude generated classes

### ISSUE THREAD

**Issue by thomas-mc-work** [hcoles/pitest#315]
I have classes which are tested that use generated classes (actually i use automatic generated builders: https://github.com/mkarneim/pojobuilder). These generated classes always have the standard annotation `@Generated` for identification. Is it possible to exclude these generated classes from the analysis?

**Comment by hcoles** [comment]
Unfortunately `@Generated ` has only source level retention so isn't visible in the bytecode. Pitest would need to start parsing source files in order to support this.

**Comment by thomas-mc-work** [comment]
Ok, thanks. My workaround is an exclusion of all source files which end with "Builder" since all these files never contain any crucial logic:

    <excludedClasses>
        <param>*Builder</param>
    </excludedClasses>
