### ISSUE TITLE
getting started on adding new operators?

### ISSUE THREAD

**Issue by monperrus** [hcoles/pitest#324]
How to add a new mutation operator in Pitest?

Google gives me [this thread](https://groups.google.com/forum/#!topic/pitusers/_22ITrzEA_8):

>To add a mutation operator to pit you currently need to do three things
>
>1) Create an new instance of MethodMutatorFactory
>2) Create a new MethodVisitor to do the work of creating the mutant
>3) Update org.pitest.mutationtest.engine.gregor.config.Mutator so that pitest knows about the new operator

Is that still correct? Nothing more to do?

**Comment by hcoles** [comment]
Yes, this should still be all that's required.

Point 2 is the hard bit.

**Comment by monperrus** [comment]
Do you welcome pull requests proposing new operators?
