### ISSUE TITLE
Test case using Mockito spy() testing abstract bean class fails.

### ISSUE THREAD

**Issue by rterp** [hcoles/pitest#329]
Pit is printing the following error when attempting to run via maven:
 name=com.lynden.esperanto.endpoint.jpa.DefaultJpaConsumerEndpointtest] did not pass without mutation.

The class passes test its JUnit without issues when running 'mvn test'.  The class is a bean with only getters/setters, which the test is testing.  The wrinkle however is that the class is abstract and is being instantiated in the JUnit test using mockito's spy() method.

Other than that there are nothing else special about this class and test class.  Testing order does not matter, and it is not using any special command line properties.  

Is there anything else that I should be looking for?

**Comment by hcoles** [comment]
If you can put together a minimal project that reproduces the issue I'll take a look.

**Comment by rterp** [comment]
OK, so it turns out that it isn't Mockito spy() that is causing the issue, its the @Getter annotations in the lombok library, and the fact that the bean has no methods since its annotated.  

I've removed the dependency to the lombok library from my code and introduced getter methods to the bean and pit is able to properly run.  I'll leave my code in this state so that I can use pit, but not sure if its something that you still would want to address.


```
package com.lynden.esperanto.endpoint.jpa;

import lombok.Getter;

public abstract class DefaultJpaConsumerEndpoint extends AbstractJpaEndpointDescriptor {

    @Getter
    protected String namedQuery;
    
    @Getter
    protected String persistenceUnit;
    
    @Getter
    protected boolean usingSharedPersistanceUnit;
    
}
```

**Comment by hcoles** [comment]
Thanks for the update.

Using Lombok with pitest has come up before. I thought the conclusion was that it generally worked (but I might be misremembering). 

I'd imagine the issue here is similar to that encountered with frameworks like powermock that re-write  bytecode at runtime. Pitest needs to ensure that any calls the framework makes to retrieve the bytecode receive pitest's mutated version of the class.
