### ISSUE TITLE
Unclear documentation on mutationThreshold and coverageThreshold

### ISSUE THREAD

**Issue by magneticflux-** [hcoles/pitest#330]
The documentation on these two parameters should specify that they accept integer percentages rather than absolute integer values. See magneticflux-/MinesweeperJ#9 and szpak/gradle-pitest-plugin#57.

**Comment by szpak** [comment]
Maybe you could provide a PR with proposed change? The site code is here: https://github.com/hcoles/pitest-site/tree/gh-pages/quickstart
