### ISSUE TITLE
Mutating initialization of static final fields

### ISSUE THREAD

**Issue by mbergenlid** [hcoles/pitest#331]
I have the following example:

```java
import java.util.ArrayList;

public class StaticFinalField {
   private static final ArrayList<String> FIELD = initializeField();

   private static ArrayList<String> initializeField() {
      return new ArrayList<>();
   }

   public int useTheStaticField() {
      return FIELD.size();
   }
}
```
And the corresponding test:
```java
   @Test
   public void test() {
      final StaticFinalField staticFinalField = new StaticFinalField();
      assertEquals(0, staticFinalField.useTheStaticField());
   }
```

PITest reports that mutating the return value of `initializeField()` (i.e. setting it to null) survives all tests but clearly setting it to `null` will cause a `NullPointerException` in the assert.
Shouldn't static state also be reloaded for each mutation?

**Comment by hcoles** [comment]
This is a known issue - the static analysis that determines if code is used
during static initialisation us very limited - it only considers code in
static initialisation blocks.

It would be good to extend it to cover cases like this. There would however
be a question over what the behaviour should be for code executed both
during initialization and elsewhere.

**Comment by hcoles** [comment]
Release 1.2.1 extends the static analysis used to detect static initialization code. 

This case should be covered - can you confirm if the issue is fixed for you?
