### ISSUE TITLE
Pitest mutations false-negatively survive in methods called from static initializers.

### ISSUE THREAD

**Issue by Nimfadora** [hcoles/pitest#353]
When applied to class with a static initializers pitest gives false negative results (mutations shows as survived, but actually tests are failing).
For class [PackageObjectFactory.java](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/PackageObjectFactory.java) it shows such survivors (the _fillShortToFullModuleNamesMap_ method is called from static initialization block):
<img width="350" alt="2017-06-05 22 59 13" src="https://cloud.githubusercontent.com/assets/10544767/26800645/cd68f2f2-4a42-11e7-8c6e-83409dea9f73.png">

The detailed report is here: [report](https://nimfadora.github.io/com.puppycrawl.tools.checkstyle/PackageObjectFactory.java.html)
Looks like pitest does not reload class in ClassLoader when checking whether mutations survive.

**Comment by romani** [comment]
@Nimfadora , please confirm:
1) real removal of any of this lines give a failure of uts in our build.
2) recheck that this issue is not related to fact that we run pitest on part of the code (our profiles, that we use for performance reason)

@Nimfadora , please provide in this issue exact commands on how to reproduce the problem.

**Comment by hcoles** [comment]
@Nimfadora

This is a known issue, which ought to be in the FAQ, but apparently is not.

Static initializers cause a bit of a problem with two of the strategies pitest uses to make mutation testing usable fast.

1. Coverage targeting

Pitest will only run tests that execute the line of code where a mutation is placed. Unfortunately the only test to execute a static initializer will be the **first** test to run that causes that class to load.

2. Mutant insertion

Pitest inserts mutants into a jvm by re-writing the class after it has loaded. This is orders of magnitude faster than starting a new jvm or creating a new classloader, but code in static initializer blocks is not re-run so the mutants have no effect.

Pitest does try to mitigate this - code in static initializer blocks will (by default) not be mutated. There is an option to mutate it, in which case pitest will create these mutants in new classloaders and run all tests that hit the mutated class against them. This is slow.

The code in your example isn't actually in a static initalizer blocks however - it's in a private static method that is (presumably) called from a static initializer. Pitest isn't currently aware that it should give these mutants special treatment.

It should be possible to extend the static initializer detection to include private static methods that are not also called from elsewhere in the class - this is an open issue however.

**Comment by Nimfadora** [comment]
@romani  1&2 points are true. 
The exact command is `mvn clean verify -Ppitest-checkstyle-common org.pitest:pitest-maven:mutationCoverage`

@hcoles thanks for reply. I guess extending static initializer detection will solve our problem.

**Comment by romani** [comment]
@hcoles ,

> It should be possible to extend the static initializer detection to include private static methods that are not also called from elsewhere in the class - this is an open issue however.

can you share link to the open issue ? 
just for tracking, to make use we update our code after you fix the issue.

**Comment by hcoles** [comment]
@romani It was tracked #53 but given the details there are a little sparse I'll close that one again and track it here.

**Comment by hcoles** [comment]
@romani

I've finally done a little work on this as it fits nicely with the new extension point being added in the next release.

This changes in https://github.com/hcoles/pitest/tree/analysis

Make it (relatively) easy to perform basic static analysis on mutants and alter or remove them from processing.

As a first use case I've added an analysis that performs a very simple check to find code that is active during static initialization. If will recognise mutants as being active then if

* They are in a <clinit> method (as is currently the case)
* They are in a *private* method *directly* called from <clinit>

There is plenty that this will miss, but it is an improvement on the current behaviour, and may be enough for your codebase.

**Comment by romani** [comment]
@hcoles ,thanks a lot, as you will release fix, let us know by creation of issue to use new version.
Our goal is to archive 100% coverage by pitest, with minimal amount of exclusions/skips.

**Comment by hcoles** [comment]
release in 1.2.1

**Comment by romani** [comment]
@hcoles , please close this issue, it works fine on 1.2.1
