### ISSUE TITLE
maven plugin outputs classpath with each test

### ISSUE THREAD

**Issue by jasonmfehr** [hcoles/pitest#358]
When I run pit using the maven plugin, the classpath for the project is written out to the console repeatedly.  This generates a lot of extra noise in the builds.  Writing out the classpath seems to be something that should happen only when running in debug mode, but I do not know the history behind why that classpath is written out.  Can that classpath output be switched to only happen when running in debug mode, or is that classpath output there for a reason?

Thanks,
Jason

**Comment by hcoles** [comment]
Yes that's kind of annoying isn't it.

Fortunately it's fixed in the 1.21 snapshot. Planning to release towards the end of the month.

**Comment by jasonmfehr** [comment]
Excellent.  Thanks!
