### ISSUE TITLE
Removed assignment to member variable - false warning when field initialized with default value

### ISSUE THREAD

**Issue by hcoles** [hcoles/pitest#36]
_From [esko.luo...@gmail.com](https://code.google.com/u/102883237794451111459/) on April 02, 2012 08:50:29_

What steps will reproduce the problem? Create a class with a member variable that is initialized to the default value of that type, for example 0. An example is the "private int workers = 0;" in https://github.com/orfjackal/jumi/blob/master/jumi-core/src/main/java/fi/jumi/core/runners/WorkerCounter.java What is the expected output? What do you see instead? Now the above class gives the report "Removed assignment to member variable workers : SURVIVED". I think it would be better to not remove the assignment of initializers with default value, because that mutation changes nothing - the field will be initialized to the same value regardless of the assignment. (Making the initializer explicit can improve code readability, so that's why I often use them, instead of using the implicit default value.) What version of the product are you using? On what operating system? 0.26, Win 7

_Original issue: http://code.google.com/p/pitestrunner/issues/detail?id=36_

**Comment by maxgabut** [comment]
I reproduce it with pitest v1.4.3. However this is now documented, and it is not that big of a deal.

I think we should close it now.

**Comment by maxgabut** [comment]
@hcoles what about closing this one ?
