### ISSUE TITLE
custom MutationFilterFactory and integration

### ISSUE THREAD

**Issue by sbuisson** [hcoles/pitest#385]
I see in the readme : "To use these plugins via maven add them as dependencies to the pitest-maven plugin (i.e **not** to your project dependencies) e.g"

Do you mean than if we want to use our own custom MutationFilterFactory, we should recompile the pitest-maven-plugin each times, with our own customisation?

**Comment by hcoles** [comment]
There's no need to compile - you can set the dependencies at runtime.

There's an example in the branch of the project below that shows how to add the export plugin.

https://github.com/hcoles/triangle-example/tree/export_example
