### ISSUE TITLE
Maven plugin not marked @threadSafe

### ISSUE THREAD

**Issue by unguiculus** [hcoles/pitest#388]
We run our Maven builds with multiple threads in order to make them faster. Maven complains about the pitest plugin because it is not marked thread-safe.

```
[WARNING] *****************************************************************
[WARNING] * Your build is requesting parallel execution, but project      *
[WARNING] * contains the following plugin(s) that have goals not marked   *
[WARNING] * as @threadSafe to support parallel building.                  *
[WARNING] * While this /may/ work fine, please look for plugin updates    *
[WARNING] * and/or request plugins be made thread-safe.                   *
[WARNING] * If reporting an issue, report it against the plugin in        *
[WARNING] * question, not against maven-core                              *
[WARNING] *****************************************************************
[WARNING] The following plugins are not marked @threadSafe in Plasma Web:
[WARNING] org.pitest:pitest-maven:1.2.2
[WARNING] Enable debug to see more precisely which goals are not marked @threadSafe.
[WARNING] *****************************************************************
```

Is just the annotation missing? Or does the plugin have issues running with parallel execution?

**Comment by hcoles** [comment]
The plugin itself should be thread safe. I'm not 100% clear on what the semantics are for running maven plugins in parallel though. Trying to run two instance of the pitest plugin on the module would cause issues as they would duplicate the work and write to the same file. Two instances working on different input would be fine.

**Comment by bradflood** [comment]
The unit of concurrency is a maven module. 

https://cwiki.apache.org/confluence/display/MAVEN/Parallel+builds+in+Maven+3
"This build-mode analyzes your project's dependency graph and schedules modules that can be built in parallel according to the dependency graph of your project."

Based on that, combined with your explanation that the pitest plugin can execute on different modules, it should be safe to mark the goal as threadsafe.

**Comment by hcoles** [comment]
Closing as released in1.2.3
