### ISSUE TITLE
Junk mutation in lambdas

### ISSUE THREAD

**Issue by hcoles** [hcoles/pitest#389]
As per the report here

https://groups.google.com/forum/#!topic/pitusers/D9wXNGlsozo

The compiler seems to implement null checks in lambdas by calling getclass

https://stackoverflow.com/questions/43115645/in-java-lambdas-why-is-getclass-called-on-a-captured-variable/43116722

This results in surviving junk mutants.

**Comment by hcoles** [comment]
released in 1.2.4

**Comment by SkittishSloth** [comment]
I just tested this against the latest release; I'm still getting "removed call to java/lang/Object::getClass → SURVIVED". The report does say (at the bottom) it was generated with 1.2.4.

**Comment by hcoles** [comment]
Well, that will teach me to close issues myself.

The fix was tested against the originally reported example and should catch any call to getClass in a synthetic method. So either you're seeing a slightly different scenario or I've done something stupid.

Can you post an example of code where you're still seeing this?

**Comment by SkittishSloth** [comment]
I'm having "technical difficulties" with my work laptop at the moment, so I'll try and get an example here ASAP but might be a bit. However, it *does* look like your fix took care of most of the scenarios - there is definitely a lot fewer instances.

At the moment, the only real pattern I can see is that *some* of my calls using a method reference are triggering it. Going off vavr again (from the original post on the Google Group), a call to try.flatMap(method:: reference) triggers it, but try.onSuccess(method:: reference) doesn't.

(I'm on my phone right now, so please excuse typos)

**Comment by SkittishSloth** [comment]
I'll need to double check, but I *think* it also only occurred when there were no other mutations. I might be wrong, but it's worth mentioning if you're able to look a little before I can get my laptop up and running again.

**Comment by SkittishSloth** [comment]
Okay, you can ignore a good chunk of what I've posted - it *does* happen during the .onSuccess call, and it *does* happen with multiple mutations (which I figured, but the only examples I'd found were where it was the only mutation).

Very simple reproduction, using vavr and an SLF4J logger:

```
private Logger logger;

public void logStuff(Try<String> toLog) {
  toLog.onSuccess(logger::info);
}
```

This will generate two mutants, a removal for Try::onSuccess, and a removal for Object::getClass. Now, if I convert that to a "regular" lambda instead of a method reference - `toLog.onSuccess(s -> logger.info(s))` - the mutant for Object::getClass goes away.

**Comment by hcoles** [comment]
Ok, should be easy to reproduce then.

Since it's clear that the getClass call isn't being generated in a synthetic method there is a good chance that it will not be possible to distinguish it from one created by a programmer putting a pointless call to getClass into their code. 

This means there will need to be a choice in behaviour between never mutating calls to getClass that disguard the return value or accepting these junk mutations. The former would seem to make more sense, but we can look at that when we've dug further.

**Comment by hcoles** [comment]
1.2.5 has just been released. It replaces the check that the method is synthetic with a check that the POP after the get class call is not immediately followed by a new label. This seems to be able to distinguish between the compiler generated case and a manual dead getClass call.

If some junk mutations still get through I'll drop the check for the label as the junk ones will probably be more common than programmers littering their code with pointless getClass calls.
