### ISSUE TITLE
Does Pitest work with Spock?

### ISSUE THREAD

**Issue by stevedefazio** [hcoles/pitest#394]
First I'd like to say that I've used pit in the past with junit/mockito and it's worked great. But I recently tried to build a project that I'm testing with Spock (the source is all java, but the tests are groovy), and I'm getting 0% coverage, and the message "According to coverage no tests hit the mutation" on things that are most definitely covered. I'm using pitest-maven version 1.2. And when I say 0% coverage, I mean I'm seeing things like

then: 1 * obj.method is not killing a mutation deleting my call to that method.

Does Pitest work with Spock?

**Comment by szpak** [comment]
Yes, it does. I have used PIT in that combination only in Gradle projects, but there is an Goovy/Spock [integration test](https://github.com/hcoles/pitest/tree/master/pitest-groovy-verification) in PIT codebase with Maven which configuration you can inspect.

**Comment by stevedefazio** [comment]
Okay great, I was hoping it was a mistake on my end. Thank you!

**Comment by stevedefazio** [comment]
I reviewed the example, and I was just being a dummy - I missed the maven-compiler-plugin for groovy. It works now.

**Comment by szpak** [comment]
Great to hear :).

Btw, probably you can close this issue now.
