### ISSUE TITLE
Do not create mutations that introduce unreachable code

### ISSUE THREAD

**Issue by theangrydev** [hcoles/pitest#396]
For example, mutating a conditional boundary can create unreachable code in this kind of scenario:
```
if (x == y) {
} else if (x < y) {
} else {
}
```

Mutating `x < y` to `x <= y` creates a branch that can never be hit, since the `==` branch is hit first in the equality case.

**Comment by nespera** [comment]
I believe that is creating an equivalent mutation, because the code behaviour is not altered. Detection of equivalent mutations is non-trivial - there are people doing PhDs on this topic.

**Comment by hcoles** [comment]
Yes, this is an equivalent mutation.

It is not generally possible to detect them, but there is value in filtering out specific types if they can be reliably be detected by static analysis without false positives.

I'm sceptical that it would be practical in this case, but the only way to find out for sure would be for someone to try and implement it.
