### ISSUE TITLE
Why PiTest removed call to “forEach” SURVIVED, and how to fix it ?

### ISSUE THREAD

**Issue by forEachSurvived** [hcoles/pitest#401]
[https://stackoverflow.com/questions/46386599/pitest-removed-call-to-foreach-survived](https://stackoverflow.com/questions/46386599/pitest-removed-call-to-foreach-survived)

```
.forEach(entry -> callFunction()); // removed call to lab/rat/Rat::callFunction ? TIMED_OUT 
                                  // removed call to java/util/stream/Stream::forEach ? SURVIVED
```

with manually modified source code as following -- test fails
`.forEach(entry -> {}); `

with modified code as following -- one more mutation created
```
.forEach( // removed call to java/util/stream/Stream::forEach ? SURVIVED 
          // removed call to lab/rat/Rat::callFunction ? TIMED_OUT

          entry -> callFunction() // replaced return of integer sized value with (x == 0 ? 1 : 0) ? KILLED 
);
```

I think mutation should be killed but it survived. I am looking for the reason why it's happening and how to fix these 2 things: (1) Timeout (2) mutation survived.

**Comment by hcoles** [comment]
It certainly looks as if the test should kill the removal of the forEach and in a trivial example I've just put together a similar test kills a similar mutation.

If you can package these code snippets up into a complete project (with build script) that reproduces the issue I'll take a look.

It also isn't obvious why the removal of callFunction would result in a timeout - again if you can create a complete executable example I'll take a look.

**Comment by forEachSurvived** [comment]
Creating the project with the content of the question did not reproduce the issue on my side either. Though in original project the issue is consistently reproduced which I will not be able to share due to some policies at the moment. One thing to note is that the original project encounters many time outs on unexpected lines of code.

I will try to extract the relevant code again and share if required. Kindly close and delete this issue. Thank you.
