### ISSUE TITLE
Using PIT as a library, problem with coverage

### ISSUE THREAD

**Issue by danglotb** [hcoles/pitest#405]
Hello all.

I am trying to use PIT as a library inside my own Java project.

I tried to run pit on a toy-project to understand how it works.

You can find a Piece of Code [here](https://gist.github.com/danglotb/81fb6ca6f2611afc038785077525bcee) (as a GitGist).

When PIT run, it first computes the code coverage of tests. It seems that PIT found the tests, but it results with no coverage.

We can see such lines:

    11:16:07 AM PIT >> FINE : According to coverage no tests hit the mutation MutationDetails [id=MutationIdentifier [location=Location [clazz=example.Example, method=charAt, methodDesc=(Ljava/lang/String;I)C], indexes=[4], mutator=org.pitest.mutationtest.engine.gregor.mutators.RemoveConditionalMutator_ORDER_IF], filename=Example.java, block=0, lineNumber=12, description=removed conditional - replaced comparison check with true, testsInOrder=[], isInFinallyBlock=false, poison=NORMAL]

for all mutations.

Since no test is covering any mutation location, PIT does not run test and no mutants are killed.

If I run pit from command-line, using the maven-plugin, tests kill 13 mutants over 25 generated. Command Line:

```
mvn org.pitest:pitest-maven:mutationCoverage -DreportDirectory=out -DtargetClasses=example.* -Dmutators=ALL -DtargetTests=example.TestSuiteExample -DoutputFormats=CSV
```

Could you please indicate me what I am doing wrong in the setup of PIT as library?

I searched for a post with a tutorials but I had no success.

Best regards,

-- Benjamin.

**Comment by hcoles** [comment]
If you can package the gist up into a project I can clone that reproduces the issue I can take a look.

**Comment by danglotb** [comment]
Hello, thank you.

Please find a minimalist project to reproduce [here](https://github.com/danglotb/PIT-library)

**Comment by hcoles** [comment]
Not immediate obvious what's wrong but I'll dig in when I get chance.

**Comment by danglotb** [comment]
Thank you @hcoles

**Comment by danglotb** [comment]
Hello

Did you have the change to have a look?

Thank you.

**Comment by hcoles** [comment]
I don't yet understand why this causes a problem, but the issue looks to be the use of a lambda to specify the target classes.

If you replace

```java
data.setTargetClasses(Collections.singletonList(string -> string.startsWith("example.")));
```

```java
data.setTargetClasses(Glob.toGlobPredicates(Arrays.asList("example.*")));
```

Everything works fine.
