### ISSUE TITLE
[Bug] : SCM goal  don't work  in the module of  a project:

### ISSUE THREAD

**Issue by sbuisson** [hcoles/pitest#407]
The method " findModifiedClassNames()" in the ScmMojo class don't work for the modules of a maven module project : some issue with the path: the name of the module appear two times:

/Users/sbuisson/workspace-perso/parentProject/moduleProject/moduleProject/src/test/java/com/example/MyRequestTest2.java

My scmRootDir is set at ../

I've this issue in the 1.2.1 version

**Comment by sarahBuisson** [comment]
https://github.com/hcoles/pitest/pull/408

**Comment by hcoles** [comment]
released in 1.2.5
