### ISSUE TITLE
[BUG] scm goal don't work if the classes updated are test

### ISSUE THREAD

**Issue by sarahBuisson** [hcoles/pitest#412]
Hello,

I've create a project to illustrate the scmMutationCoverage Goal : https://github.com/sarahBuisson/pitest-scm-test/branches

The issue is in the branch  https://github.com/sarahBuisson/pitest-scm-test/tree/updateTestCoveringNoCoveredClassOnMaster:

The last commit update only the test-file. Consequently no classes will be mutated.

I propose a solution, but I'm not sure how to implement-it.:
In case of scmGoal:
- run a first times the mutation for all the updated classes, with All the test ( aka, what's the current scm goal do)
- then run a second time the goals for all un updated-classes, with only the  updated test
- merge the two report.

What do you think of-it?

Regards, Sarah Buisson

**Comment by sarahBuisson** [comment]
@hcoles Another solution would be to have the ability to have custom Interceptor, in order to filter the tests.

**Comment by hcoles** [comment]
Thanks for the report - I think this was a known issue when the SCM goal was first implemented but I doubt the reasoning has been documented anywhere.

I'm not really sure what the "correct" behaviour should be.

I don't think your suggestion of merging two runs would quite work. The 2nd run would result in a lot of surviving mutants in classes unrelated to the test.

What's needed is a report on the mutations that the modified test class is "meant" to kill. I don't think the can be decided programatically.

The closest I can think of would be to mutate all the classes that are executed by the modified test(s) as well as any modified classes. As this would likely have quite a high false positive rate (ie would mutate classes that the programmer did not expect) it should only be done if a flag is set to request the behaviour.
