### ISSUE TITLE
Allow exclusion of test classes by name

### ISSUE THREAD

**Issue by hcoles** [hcoles/pitest#428]
The excludedClasses parameter currently excludes classes both from being mutated and from being executed as tests.

In order to simplify the codebase and provide better support for JUnit 5 the old mechanism of separating classes on the classpath into tests/not tests needs to be removed. This mechanism is now only needed in three corner cases

* Legacy builds that do not compile tests and production code to separate paths
* Research style activity using the command line tool
* Pitest's own test suite

The ability to exclude classes from mutation by regex/glob but still run them as tests should largely cover these corner cases  (e.g set excludedClasses to *Test).

**Comment by sarahBuisson** [comment]
you should add it to the doc of the pitest.org website.
