### ISSUE TITLE
Move export plugin into main codebase

### ISSUE THREAD

**Issue by hcoles** [hcoles/pitest#432]
The export plugin is useful for debugging, now that minimum java version has been raised to 7 nothing prevents it from being moved into the main codebase for convenient use.

**Comment by justinwm** [comment]
Hi Thanks very much for your contribution :-)

I am wondering how can I enable this feature in command line? or it is just impossible.

If so, I will switch to Maven.

Looking forward for your reply.

Best
Ming

**Comment by justinwm** [comment]
@hcoles 

Hi, This is exactly what I want and it works!  Thanks very much!!

Best
