### ISSUE TITLE
junit5 plugin v0.3 does not find tests

### ISSUE THREAD

**Issue by christophsturm** [hcoles/pitest#436]
I'm filing this here because issues are not enabled in the junit5 plugin repo.

with pitest 1.2.5 and junit plugin 0.2 everything runs fine for me. updating to pitest 1.3.1 and plugin 0.3 it does not find any tests. 

```
5:32:38 PM PIT >> FINE : MINION : Installing PIT agent

5:32:38 PM PIT >> INFO : Sending 73 test classes to minion
5:32:38 PM PIT >> INFO : Sent tests to minion
5:32:38 PM PIT >> INFO : MINION : 5:32:38 PM PIT >> FINE : Expecting 73 tests classes from parent
5:32:38 PM PIT >> FINE : Tests classes received
5:32:38 PM PIT >> INFO : Checking environment

5:32:39 PM PIT >> INFO : MINION : 5:32:39 PM PIT >> INFO : Found  0 tests

5:32:39 PM PIT >> INFO : MINION : 5:32:39 PM PIT >> INFO : Dependency analysis reduced number of potential tests by 0

5:32:39 PM PIT >> INFO : MINION : 5:32:39 PM PIT >> INFO : 0 tests received

5:32:39 PM PIT >> INFO : MINION : 5:32:39 PM PIT >> FINE : Running 0 units
```

**Comment by hcoles** [comment]
Can you post a link to a minimal project that reproduces the issue?

**Comment by christophsturm** [comment]
i forgot to mention that it's a kotlin project. but it did work with older pitest and older plugin
https://github.com/christophsturm/pitest-gradle-it

**Comment by hcoles** [comment]
It looks as if the autodetection of the junit-5 plugin is not working when running via gradle and pitest is defaulting to legacy junit. This is most likely a bug on the pitest side. It should be possible to work round it by setting the test plugin explicitly, but unfortunately the gradle plugin hasn't yet been updated to support the new parameter.

I've raised an issue here.

https://github.com/szpak/gradle-pitest-plugin/issues/76

**Comment by christophsturm** [comment]
i made a pr for the gradle plugin to add support for testPlugin.

one thing I'm not sure about: how can i specify two plugins? for example when i want to use the kotlin plugin and the junit5 plugin.

**Comment by hcoles** [comment]
Generally pitest plugins are activated just by adding them to pitest's classpath, so using the kotlin plugin and another plugin is just  question of putting both of them on the classpath.

Test plugins are a special case - pitest needs to be told which one to use as only one test plugin can be active at a time (and the default junit4 plugin will always be present).

**Comment by christophsturm** [comment]
Thanks, that makes sense.

**Comment by maxgabut** [comment]
This is closed on gradle-pitest side, so I assume that we can also those this issue.
