### ISSUE TITLE
PrimitiveReturnsMutator cannot handle byte

### ISSUE THREAD

**Issue by MLacos** [hcoles/pitest#439]
Hi,

When I have a function that has the byte return type than and activate the PrimitiveReturnsMutator an  IllegalStateException rises which tells me that it does not return an integer type.

When I looked around in the code I found this piece which seems to cause it for creating a message. This is found in org.pitest.mutationtest.engine.gregor.mutators.PrimitiveReturnsMutator.

When adding a case with Type.BYTE no extra unittest test seems to fail.

`
private String makeMessage(String methodDescriptor) {
        int sort = Type.getReturnType(methodDescriptor).getSort();
        switch (sort) {
        case Type.INT:
          return "replaced int return with 0";
        case Type.CHAR:
          return "replaced char return with 0";
        case Type.SHORT:
          return "replaced short return with 0";
        default:
          throw new IllegalStateException(
              methodDescriptor + " does not return integer type");
        }
      }
`

**Comment by hcoles** [comment]
That's not good. Thanks for reporting.

**Comment by hcoles** [comment]
Fixed in 1.3.2 release
