### ISSUE TITLE
Website link to IDEA plugin outdated

### ISSUE THREAD

**Issue by JonasDralle** [hcoles/pitest#446]
on http://pitest.org/links/ the link to the intellij plugin is outdated

intelliJ plugin URL
Is:
http://plugins.intellij.net/plugin/?idea&pluginId=7119
Should be:
https://plugins.jetbrains.com/plugin/7119-pit-mutation-testing-idea-plugin

EDIT: only the intellij link is outdated

**Comment by szpak** [comment]
@JonasDralle The summary of that issue suggest that a link to the Gradle plugin is outdated, but it's not.

**Comment by JonasDralle** [comment]
How so? "A and B oudated" is clearly visible.
You can suggest a better title.

**Comment by szpak** [comment]
Maybe I didn't get it correctly, but the summary suggests that links to the gradle plugin and the idea plugin for PIT are outdated. However, the link to the Gradle plugin is correct.

Maybe you wanted to write:
> Website link to IDEA plugin outdated

?

**Comment by JonasDralle** [comment]
You're right. When I tested it the gradle URL was unable to resolve - probably my bad.
I changed the title and ticket description accordingly.

**Comment by hcoles** [comment]
@JonasDralle Thanks - now fixed.
