### ISSUE TITLE
question: how could we create a source-code level mutation engine?

### ISSUE THREAD

**Issue by monperrus** [hcoles/pitest#450]
Some mutation operators are easier to be implemented at the source code level than at the bytecode level.

How could we create a source-code level mutation engine for Pit?

**Comment by hcoles** [comment]
This would require some re-work to how PIT operates. The main thing that would need to change is how mutations are passed to the the child processes. 

At the moment the child processes are passed a unique id which they can use to re-create them. This is lightweight in terms of both memory and cpu as bytecode manipulation is fast.

To process source based mutants this would need to change. The most likely scheme would be for the parent process to create a binary diff to pass to the child. Some experimentation would be required to see how well this performed - once concern would be that the diffs would be too large for them to all be held in memory by the parent process (as is currently the case for the ids).

**Comment by monperrus** [comment]
Thanks a lot for the detailed answer.

Would you be interested in a pull request that would add support for source code level mutants? Would you consider merging it?

**Comment by hcoles** [comment]
In principle yes, but it would depend on the details of the PR (properly tested, conforms to coding style etc etc).

I think this would need to be done in two parts

1. A PR with the changes required to allow a source based engine.

This PR would need to include the results of performance tests run before and after the change (both using the default mutation engine) against some real codebases such as JodaTime.

2. The engine itself. This would be best implemented as a plugin so it would not actually need to be merged into the main codebase.

**Comment by monperrus** [comment]
> I think this would need to be done in two parts

OK, that's clear, thanks.

> a plugin so it would not actually need to be merged into the main codebase.

Interesting, this raises a question about the pitest ecosystem https://github.com/hcoles/pitest/issues/451
