### ISSUE TITLE
question: how to add plugin repos under https://github.com/pitest/?

### ISSUE THREAD

**Issue by monperrus** [hcoles/pitest#451]
In our group, we are writing plugins for pitest that may be useful for others, and for which we'd be very happy to welcome external contributions.

The best place to be visible and attract contributions would be under the pitest organization.

What's the process to propose new repos under https://github.com/pitest/?

**Comment by monperrus** [comment]
@hcoles do you have any input on putting repos under https://github.com/pitest/?

Thanks!

**Comment by UrsMetz** [comment]
@monperrus I think you can create a pull request against https://github.com/hcoles/pitest-site with your proposed updated list of plugins.

**Comment by UrsMetz** [comment]
@monpress sorry I misunderstood your question, I guess it is up to @hcoles to create new repos under the pitest organisation.

**Comment by monperrus** [comment]
Thanks Urs for the insight. We're looking forward to @hcoles input on that community topic.

**Comment by hcoles** [comment]
We're happy to include things in the org (and welcome the work and contribution) but also want to avoid having projects under it that are not in a usable state. 

At the moment there is no defined process for putting something under the org, but a simple approach that should work would be for people to go through the following steps.

1. Create a repo elsewhere on github 
2. Produce enough code to demonstrate that an idea is viable and there is interest in developing it
3. Create an issue here to request the repo is forked under the pitest org

**Comment by monperrus** [comment]
> We're happy to include things in the org (and welcome the work and contribution)

Excellent.

> a simple approach that should work would be for people to go through the following steps

That's clear, thanks. I would only suggest to move the repo instead of forking, because 1) Github handles this very well (all links are kept, etc) and 2) it avoids confusion (only one issue tracker, etc.)

We will open an issue :-)
