### ISSUE TITLE
pitest 1.3.0 and higher does not work with testng 

### ISSUE THREAD

**Issue by rhdietrich** [hcoles/pitest#475]
When running pitest 1.3.0 or higher with testng pitest fails with the message 'PIT requires JUnit 4.6'.
That is true also for testng version 6.1.1. Up to version 1.2.5 pitest accepts testng up to the hghest version (currently 6.14.3)

**Comment by Stephan202** [comment]
Hi @rhdietrich; see #458. In short, when using Maven you'll have to specify `<testPlugin>testng</testPlugin>`.

**Comment by rhdietrich** [comment]
@Stephan202 Thank you, that's it! Maybe adjust the text on the Pitest FAQ page to stress the testplugin paramter and it's default? you can close this issue,

**Comment by Stephan202** [comment]
Leaving that to @hcoles ;)

**Comment by hcoles** [comment]
@Stephan202 thanks for resolving to this.
