### ISSUE TITLE
Show column of the mutation

### ISSUE THREAD

**Issue by slaout** [hcoles/pitest#476]
Hello,

Given this line:

    if (a == 42 || b != 43)

We get such report:

1. negated conditional → KILLED
2. negated conditional → KILLED
3. removed conditional - replaced equality check with false → SURVIVED
4. removed conditional - replaced equality check with false → KILLED
5. removed conditional - replaced equality check with true → KILLED
6. removed conditional - replaced equality check with true → SURVIVED

But we do not know which condition is faulty in the if: the a test, the b one, or both?

With a column indication, we could easily see that the "a == 42" test failed, and not the other one.

The column should be the one of the start of the condition (here, the column of "a").

**Comment by hcoles** [comment]
Unfortunately column information is not included in the bytecode, so this is not possible.

**Comment by hcoles** [comment]
Closing as there is no way to implement this without switching to ast based mutation.
