### ISSUE TITLE
Inherited Tests Not Recognized (JUnit 5)

### ISSUE THREAD

**Issue by SkittishSloth** [hcoles/pitest#488]
Not even 100% sure it's an actual issue, or if I'm just doing something wrong.

I have a series of tests with a common abstract base test class. The base test has the actual @Test methods in use, and the child classes implement some methods to initialize stuff used in those tests. Running everything directly via gradle test works fine - the tests are definitely executed (I intentionally made them fail just to verify, and they do). When I run it under PITest, they aren't executed. Everything else - non-inherited tests - runs fine, and I get appropriate coverage metrics. If I manually override the test methods in the child classes and explicitly add the @Test annotation to those, then PITest picks them up and everything runs fine. (I did also try this with test interfaces - @Test on default methods, which JUnit 5 supports and some suggest as a better alternative to abstract bases, but the results were the same.)

Am I doing something wrong? Is this expected behavior and I simply need to rethink my testing approach? I've used PITest for a while, and I've never come across this before - however, I believe this is the first time I've tried something like this in JUnit 5, and my understanding is they have changed some of the semantics/details/whatever around annotation inheritance (https://github.com/junit-team/junit5/issues/960). I'm not sure how (or even if) that could have effected PITest. 

Please let me know if there's anything else you need.

**Comment by SkittishSloth** [comment]
I have a quick sample here; hopefully it'll 

Actual classes under test:
```
abstract class BaseClass {

  public final String sayHello() {
    return "Hello " + getName();
  }

  abstract String getName();
}

class Child extends BaseClass {
  @Override
  String getName() {
    return "John";
  }
}
```

And the tests:
```
abstract class BaseClassTest {

  protected abstract BaseClass createInstance();

  protected abstract String expectedName();

  @Test
  void shouldGiveAppropriateName() {
    final BaseClass instance = createInstance();

    assertTrue(instance.sayHello().contains(expectedName()));
  }
}

class ChildTest extends BaseClassTest {
  @Override
  protected BaseClass createInstance() {
    return new Child();
  }

  @Override
  protected String expectedName() {
    return "John";
  }

  // This shouldn't be necessary. The tests will execute
  // perfectly fine under the standard JUnit runner without
  // this, but PITest won't pick them up.
  @Test
  @Override
  void shouldGiveAppropriateName() {
    super.shouldGiveAppropriateName();
  }
}
```

**Comment by SkittishSloth** [comment]
Great - thank you! (Feel free to close when it gets merged, if I forget to.)

**Comment by hcoles** [comment]
Thanks @tobiasstadler PR is now merged and a release should be syncing to maven central.

**Comment by SkittishSloth** [comment]
It's working great! I was able to clear out a lot of stupid, redundant code now :) Thank you!

One thing though: now I'm getting a ton of logs, i.e.

> stderr  : 4:53:43 PM PIT >> INFO : No test coverage for mutation  MutationDetails [id=MutationIdentifier [location=Location...

(But a *lot* of that)

All I did was change the version of the juni5 plugin from 0.5 to 0.6, and I'm not seeing anything in the change set between those versions that would suggest anything related to logging.

Thoughts?

**Comment by SkittishSloth** [comment]
It looks like this isn't working quite right. It's giving me what appears to be correct coverage statistics, but the reports have the code covered by the tests marked as RUN_ERROR. If I run them the previous way - overriding the test methods and annotating them as Test - it works correctly.
