### ISSUE TITLE
Question: NO_COVERAGE reported as mutation coverage failure?

### ISSUE THREAD

**Issue by sebastientromp** [hcoles/pitest#489]
Hello,

I have a question for which I couldn't find an answer in the docs or online.
I have some lines that are not covered by tests, and in the Mutation Report, it looks like these are considered as Mutation Coverage failures:

Report:
![screenshot_2018-07-23 screenshot 1](https://user-images.githubusercontent.com/7889624/43080358-e07fb1fe-8e8f-11e8-84d5-c1f647dcb0d9.png)

Details:
![screenshot_2018-07-23 screenshot](https://user-images.githubusercontent.com/7889624/43080338-d39fd2f2-8e8f-11e8-8f11-d70c3c28cfff.png)

Am I understanding this correctly?
If so, is it possible that Mutation Coverage do not report failures for lines that are not covered by tests?

Thanks for your help!

Seb

**Comment by hcoles** [comment]
Yes, mutations on uncovered lines are treated as surviving mutants, but they are given a special status of "uncovered" so they can be easily identified as mutants that were not challenged by a test.

**Comment by sebastientromp** [comment]
Is this behavior configurable (directly in pitest or is a workaround available)? Or if not, and if you're open to making this configurable, would you accept PRs for this?
I've been pretty impressed with the relevance of the results (apart from the Coverage one), so I'm looking at having a 100% success rate policy (we're already there - or almost - if we exclude the coverage ones).

**Comment by hcoles** [comment]
This is not currently configurable.

If uncovered mutants were excluded from the mutation score this would give a measure of the strength of the implemented tests. 

I'd be happy to accept a PR that added an additional "test strength" measure calculated in this way. I would prefer not to add options that changed the way the standard mutation score was calculated, as this would cause confusion.

**Comment by sebastientromp** [comment]
Got it! "Test strength" is precisely what we're after, as it combines nicely with "test coverage" for an overall measure of the test harness.

Would you have any pointers as to where to start looking in the code?

**Comment by mxd4** [comment]
Hi! Did anything change regarding this issue, and if not would you still be willing to accept such a PR @hcoles ?
Thanks a lot

**Comment by hcoles** [comment]
Tests strength was included in release 1.6.1
