### ISSUE TITLE
Write latest report to latest dir

### ISSUE THREAD

**Issue by drdamour** [hcoles/pitest#492]
It'd be nice if every time the report is run in addition to the timestamp it output the results to a latest dir...then users could just refresh browser as they fix things.

When i work i like to run tests continuously as i make changes and watch the errors go away.  right now every time i go to look at pitest report i have to nav to root then pick the latest one.

obv i can add some symlink plugin stuff..but it'd be nice if this just happened ootb i think.  also all html output could have a link to latest then

**Comment by hcoles** [comment]
If you set the timeStampedReports parameter to false then pitest will always write to the same location and you can just refresh the browser.

**Comment by drdamour** [comment]
oh i should have mentioned i am doing this as a "workaround"...losing the history locally...probably good enough for 99% of use cases.

thanks!
