### ISSUE TITLE
Add mutation percentage info when success

### ISSUE THREAD

**Issue by pedrorijo91** [hcoles/pitest#493]
Hey,

While using maven, I run the mutation testing using the command specified in the docs:

```
mvn org.pitest:pitest-maven:mutationCoverage
```

if I specify a certain [mutation threshold](http://pitest.org/quickstart/maven/#mutationthreshold) that is not met,  I get an error message on the command line:

```
[ERROR] Failed to execute goal org.pitest:pitest-maven:1.4.0:mutationCoverage (default-cli) on project <XXXXX>: Mutation score of 85 is below threshold of 100 -> [Help 1]
```

and this is simple but good enough.  But I have no similar output when the score is above the threshold. As far as I've seen, there's no option/configuration for that. Can you confirm? 

Looking at the source code, if I wanted to implement this, it would be rather easy no?
It seems I would only need to add a simple log at https://github.com/hcoles/pitest/blob/master/pitest-maven/src/main/java/org/pitest/maven/AbstractPitMojo.java?utf8=%E2%9C%93#L378-L382. And for consistency, probably also add to https://github.com/hcoles/pitest/blob/master/pitest-command-line/src/main/java/org/pitest/mutationtest/commandline/MutationCoverageReport.java#L42-L51 no?

Note: using version 1.4.0

**Comment by hcoles** [comment]
Hi @pedrorijo91 pitest already outputs the mutation score for a successful run.

In the example output below

`-================================================================================
- Timings
================================================================================
> scan classpath : < 1 second
> coverage and dependency analysis : 36 seconds
> build mutation tests : < 1 second
> run mutation analysis : 3 minutes and 57 seconds
--------------------------------------------------------------------------------
> Total  : 4 minutes and 34 seconds
--------------------------------------------------------------------------------
================================================================================
- Statistics
================================================================================
>> Generated 850 mutations Killed 805 (95%)
>> Ran 5473 tests (6.44 tests per mutation)
================================================================================
- Mutators
================================================================================
> org.pitest.mutationtest.engine.gregor.mutators.ConditionalsBoundaryMutator
>> Generated 27 Killed 14 (52%)
> KILLED 7 SURVIVED 13 TIMED_OUT 7 NON_VIABLE 0 
> MEMORY_ERROR 0 NOT_STARTED 0 STARTED 0 RUN_ERROR 0 
> NO_COVERAGE 0 
--------------------------------------------------------------------------------
> org.pitest.mutationtest.engine.gregor.mutators.IncrementsMutator
>> Generated 4 Killed 4 (100%)
> KILLED 4 SURVIVED 0 TIMED_OUT 0 NON_VIABLE 0 
> MEMORY_ERROR 0 NOT_STARTED 0 STARTED 0 RUN_ERROR 0 
> NO_COVERAGE 0 
--------------------------------------------------------------------------------
> org.pitest.mutationtest.engine.gregor.mutators.VoidMethodCallMutator
>> Generated 72 Killed 58 (81%)
> KILLED 58 SURVIVED 7 TIMED_OUT 0 NON_VIABLE 0 
> MEMORY_ERROR 0 NOT_STARTED 0 STARTED 0 RUN_ERROR 0 
> NO_COVERAGE 7 
--------------------------------------------------------------------------------
> org.pitest.mutationtest.engine.gregor.mutators.RemoveConditionalMutator_EQUAL_ELSE
>> Generated 71 Killed 68 (96%)
> KILLED 65 SURVIVED 1 TIMED_OUT 3 NON_VIABLE 0 
> MEMORY_ERROR 0 NOT_STARTED 0 STARTED 0 RUN_ERROR 0 
> NO_COVERAGE 2 
--------------------------------------------------------------------------------
> org.pitest.mutationtest.engine.gregor.mutators.ReturnValsMutator
>> Generated 531 Killed 520 (98%)
> KILLED 517 SURVIVED 5 TIMED_OUT 3 NON_VIABLE 0 
> MEMORY_ERROR 0 NOT_STARTED 0 STARTED 0 RUN_ERROR 0 
> NO_COVERAGE 6 
--------------------------------------------------------------------------------
> org.pitest.mutationtest.engine.gregor.mutators.MathMutator
>> Generated 43 Killed 41 (95%)
> KILLED 39 SURVIVED 1 TIMED_OUT 2 NON_VIABLE 0 
> MEMORY_ERROR 0 NOT_STARTED 0 STARTED 0 RUN_ERROR 0 
> NO_COVERAGE 1 
--------------------------------------------------------------------------------
> org.pitest.mutationtest.engine.gregor.mutators.NegateConditionalsMutator
>> Generated 102 Killed 100 (98%)
> KILLED 84 SURVIVED 0 TIMED_OUT 15 NON_VIABLE 0 
> MEMORY_ERROR 1 NOT_STARTED 0 STARTED 0 RUN_ERROR 0 
> NO_COVERAGE 2 
--------------------------------------------------------------------------------
`
The overall mutation score appears in the statistics section towards the top. Score for each mutation operator are also shown.

Possibly the overall score should be moved to the bottom?

**Comment by pedrorijo91** [comment]
ups, sorry, I can see now. I would say the mutators list could be considered extra information (as in, something that should be printed only if explicitly specified), but I think that changing the order would be a good start to make the juicy summary more visible.
