### ISSUE TITLE
PIT is generating equivalent mutations

### ISSUE THREAD

**Issue by pedrorijo91** [hcoles/pitest#497]
I've seen a couple of SURVIVED mutants that are basically equivalent to the original code base.

I don't have a full example yet, but I've seen it happen in lines whose original content is something like `return true;` and it replaces by an equal mutant `return true;` which obviously will survive.

Is this a known bug? is there any workaround? If I wanted to help, where should I start looking into?

Thanks,
Pedro

**Comment by hcoles** [comment]
Not a known issue, could you post an example?

**Comment by pedrorijo91** [comment]
I have this method:


```
    @Override
    public boolean validate(final String value) {
        if (!super.validate(value)) {
            return false;
        }

        if (value == null) {
            return true;
        }

        try {
            Double.valueOf(value);
            return true;

        } catch (final NumberFormatException e) {
            return false;
        }
    }
```

and I have this report:

![image](https://user-images.githubusercontent.com/1999050/43764065-50737352-9a24-11e8-81fd-8c9c2d64728d.png)

(let me know if you prefer any other output format)

**Comment by hcoles** [comment]
Thanks for the example, this is indeed a bug in the new return values mutators.

What's meant to happen is that pitest generates a whole bunch of mutants, but then filters out the ones such as this that are trivially equivalent. Unfortunately the filter is overly simplistic, looking for unbroken bytecode sequences such as "load a constant representing true" followed by "return it".

This is working most of the time, but in your example javac (but not the eclipse compiler) inserts debug line number information between the "load a constant" and "return it" bit, breaking the matching.

Pitest has a bytecode matching library built into it that knows how to ignore this stuff, but this filter isn't using it as it looked like it could get away with something simpler. Fortunately it shouldn't be a large job to convert it.

**Comment by hcoles** [comment]
Ok, that's fixed in master, will push a release out soon.

Thanks for the report. Most users would not see this as the new mutators are not switched on by default. Please do report any other similar issues - the plan is to replace the existing return vals mutator with the new set in the near future, but as this bug demonstrates there could still be some unexpected problems.

**Comment by pedrorijo91** [comment]
wow, thanks for the quick fix :) Just a note, I also found it happened with `return Optional.empty()`

for now I have all mutators enabled (testing PIT in a small lib), will let you know if I find anything else worthy!

**Comment by hcoles** [comment]
I would like to be able to claim that all fixes to pitest are that fast, but that would be woefully untrue.

Optional.empty *should* also be fixed, but I didn't add additional test cases for all the supported types so it is possible I am mistaken.

**Comment by pedrorijo91** [comment]
will let you know as soon as the new release is out ;)

**Comment by hcoles** [comment]
Closing as 1.4.1 is now released.

**Comment by pedrorijo91** [comment]
both `return true;` and `return Optional.empty()` false positives have been fixed :) once again, thanks a lot for the quick iteration @hcoles
