### ISSUE TITLE
RUN_ERROR During Inherited Tests (JUnit 5)

### ISSUE THREAD

**Issue by SkittishSloth** [hcoles/pitest#498]
As a follow up to [this previous issue](https://github.com/hcoles/pitest/issues/488), things don't seem to be working quite right. I commented there, but I'm not sure how Github handles comments on closed issues, so I don't know if there were any notifications about the comments.

After that fix, running the tests using just inheritance and not overriding the test methods, the tests execute - as in, the build passes - and the report shows the light-green background indicating the code has line coverage. However, instead of any kind of killed/survived status, the mutation coverage is gray and the status is RUN_ERROR. 

There's a *lot* of logging; lot's of stuff along the lines of:

> stderr  : 4:53:43 PM PIT >> INFO : No test coverage for mutation  MutationDetails [id=MutationIdentifier [location=Location...

If I go back to the way I was running them before the fix - with the test methods overridden in the class - everything works perfectly.

Please let me know if you need any further information; I couldn't figure anyway to get more details out of the logs, and I truncated the message above because I'm not sure what exactly was relevant or not.

**Comment by tobiasstadler** [comment]
Sorry for the late reply. I think I fixed your issue in pitest/pitest-junit5-plugin#10

**Comment by SkittishSloth** [comment]
Awesome - thank you!

When might there be a new release for the JUnit plugin to include that?

**Comment by hcoles** [comment]
@SkittishSloth  I just cut a release now.
