### ISSUE TITLE
Compute a full mutation matrix

### ISSUE THREAD

**Issue by nrainer** [hcoles/pitest#510]

**Comment by nrainer** [comment]
See pull request https://github.com/hcoles/pitest/pull/511

**Comment by nrainer** [comment]
Can be closed. Has been solved with #511.

**Comment by dormaayan** [comment]
@nrainer Thanks for implementing this feature!

Can you write here how to use that feature? Specifically, how to configure the `pom.xml` file to use it and what is the expected outcome

Many Thanks!

**Comment by nrainer** [comment]
@dormaayan I thought it was documented somewhere on pitest.org, but I couldn't find it.
To use this feature, you need to configure:
 ```
<fullMutationMatrix>true</fullMutationMatrix>
<outputFormats>
  <param>XML</param>
</outputFormats>
```

Hence, the feature will only be working if XML output is used.
As a result, the XML entries will have nodes like
```
<killingTests>foo|foo2</killingTests>
<succeedingTests>bar</succeedingTests>
```

Hence, instead of the node `<killingTest>` the nodes `<killingTests>` and `<succeedingTests>` are used. Test cases are (currently) separated using `|`.
Note that the matrix will not be complete for entries with the result `TIMED_OUT` or `MEMORY_ERROR`.

**Comment by SaraTawfig** [comment]
Note that the matrix will not be complete for entries with the result TIMED_OUT or MEMORY_ERROR.

'm having this problem (the result TIMED_OUT ) , what's the solution plz?
