### ISSUE TITLE
Whether the test framework is supported or not

### ISSUE THREAD

**Issue by yuanxiaomama** [hcoles/pitest#527]
Hello,this is a test framework,tests are referenced on the classpath,but no codes，whether pitest support? 
pom:
                      `<plugin>`
				`<groupId>org.pitest</groupId>`
				`<artifactId>pitest-maven</artifactId>`
				`<version>1.4.2</version>`
				`<executions>`
					`<execution>`
						`<id>compute-mutation-coverage</id>`
						`<goals>`
							`<goal>mutationCoverage</goal>`
						`</goals>`
					`</execution>`
				`</executions>`
				`<configuration>`
					`<mutators>`
						`<mutator>ALL</mutator>`
					`</mutators>`
					`<testPlugin>testng</testPlugin>`
					`<threads>4</threads>`
					`<timeoutFactor>4</timeoutFactor>`
					`<timestampedReports>false</timestampedReports>`
				`</configuration>`
			`</plugin>`

terminal:
[INFO] Skipping project because:
[INFO]   - Project has no tests, it is empty.

<img width="425" alt="2" src="https://user-images.githubusercontent.com/24218946/46780456-73942800-cd4f-11e8-9160-5b7f9b4fa5a4.png">
<img width="340" alt="default" src="https://user-images.githubusercontent.com/24218946/46780457-742cbe80-cd4f-11e8-82aa-8cdaf0180e8f.png">

**Comment by hcoles** [comment]
I'm not quite sure what your expected behaviour is here. It appears that you have no code to mutate so what else could pitest do except skip the project?

If you have code that you intend to deliver as some sort of library that you would like to mutate you should place this under src/main, separate from the tests that verify its behaviour.

**Comment by yuanxiaomama** [comment]
thank you for your reply，but src and test is separate，it's just test framework and the tests send request to service

**Comment by hcoles** [comment]
Could you explain clearly what behaviour you expect to see is in this scenario.
