### ISSUE TITLE
Unclear documentation that globs don't bring in nested classes by default

### ISSUE THREAD

**Issue by rnveach** [hcoles/pitest#541]
Identified at https://github.com/checkstyle/checkstyle/pull/6254 ,

We found out only by looking at the reports, that pitest doesn't bring in nested classes when you specify the full class name in the `targetClasses` parameter with no `*` on the end. When we started adding `*`s to all our full class names, we got new pitest failures because of missing mutations on nested classes.

This is not clear in the documentation at http://pitest.org/quickstart/maven/ , if it isn't considered a bug. It should be specifically stated in the documentation in big letters, that nested classes aren't picked up by default when a glob has no `*` in it.

**Comment by maxgabut** [comment]
I'm not sure if it should be considered a bug. I clearly see how it may be surprising (what would be the point of including a class and not its inner classes ?), but it also makes sense somehow. @hcoles do you have an opinion on this ?

Anyway, it's easy to document, so we can always [do that](https://github.com/hcoles/pitest-site/pull/77) and maybe change the behavior later.

**Comment by hcoles** [comment]
The update to the documentation is now merged (thanks for the report @rnveach and the fix @maxgabut).

I'm concerned that trying to auto included nested classes would result in a bunch of new issues as other classes were accidentally included. Happy to look at a PR that managed to achieve this cleanly without any false matches though.

**Comment by maxgabut** [comment]
I'm closing this issue as the documentation aspect of it is done.

Regarding the auto inclusion of nested classes, another issue could be created if someone wants to have a go at it.
