### ISSUE TITLE
Should document that excludedClasses now requires excludedClass subtags (single string value worked before)

### ISSUE THREAD

**Issue by Pr0methean** [hcoles/pitest#548]
I'm using Pitest 1.4.3. When I updated Powermock from 2.0.0-beta5 to 2.0.0, I got an error saying that excludedClasses was a String when a List was expected. My excludedClasses tag was `<excludedClasses>io.github.pr0methean.betterrandom.prng.AesCounterRandom</excludedClasses>`. Looking online for examples, I eventually determined that the proper form was `<excludedClasses><excludedClass>io.github.pr0methean.betterrandom.prng.AesCounterRandom</excludedClass></excludedClasses>`, which seems to have fixed the problem. (https://github.com/Pr0methean/BetterRandom/pull/73 will confirm the fix if it is automatically merged with e6db769 as the last commit.) This needs to be documented.

**Comment by maxgabut** [comment]
Hi @Pr0methean

I tried both syntaxes (with and without sub tags) and both worked for me. You can see my code on [branch pitest-issues/548 of maxgabut/pitest-sample](https://github.com/maxgabut/pitest-sample/tree/pitest-issues/548). Is it possible that something else broke you build ?

If you think there really is a problem with pitest here, can you try to put together a minimalist sample demonstrating it ?

About the documentation, `excludedClasses` is currently described in [the documentation](http://pitest.org/quickstart/maven/) as a:
> List of globs to match against class names.

So while it could be more user friendly with a sample, it is already documented as a list.

**Comment by maxgabut** [comment]
I'm closing this issue because I don't think there is a problem with Pitest here. Don't hesitate to comment if you disagree.
