### ISSUE TITLE
NoSuchMethodError: java.nio.ByteBuffer.flip

### ISSUE THREAD

**Issue by pzygielo** [hcoles/pitest#557]
When run on JDK8, maven build fails with following reported
```
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.pitest:pitest-maven:1.4.4:mutationCoverage (runPitest) on project isbn: Execution runPitest of goal org.pitest:pitest-maven:1.4.4:mutationCoverage failed: An API incompatibility was encountered while executing org.pitest:pitest-maven:1.4.4:mutationCoverage: java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
```
with stacktrace referring to line 34 of https://github.com/hcoles/pitest/blob/9ac9fad55b35b4b2016c932a58c17565239a765d/pitest/src/main/java/org/pitest/util/StreamUtil.java#L30-L39

Similar to https://jira.mongodb.org/browse/JAVA-2559 (as linked in https://github.com/functional-streams-for-scala/fs2/issues/1357).

**Comment by pzygielo** [comment]
Manifest for 1.4.3 declares
```
Implementation-Version: 1.4.3
Created-By: Apache Maven 3.3.3
Build-Jdk: 1.8.0_181
```
and for 1.4.4
```
Created-By: Apache Maven 3.3.3
Build-Jdk: 10.0.2
Implementation-Version: 1.4.4
```

**Comment by asm0dey** [comment]
Yup, my project build also fails: https://travis-ci.org/asm0dey/school-crm/builds/485205291?utm_source=github_status&utm_medium=notification

**Comment by hcoles** [comment]
Just rebuilt on java 8 as 1.4.6, hopefully this resolves the issue.

**Comment by pzygielo** [comment]
Will check 1.4.5 as soon as it's in central.
Fingers crossed!

**Comment by pzygielo** [comment]
Confirmed, 1.4.5 solves my issue. Hope it works for @asm0dey as well.
Thank you for new release.
