### ISSUE TITLE
Not reporting junit incompatibilities

### ISSUE THREAD

**Issue by hcoles** [hcoles/pitest#56]
_From [henry.co...@googlemail.com](https://code.google.com/u/110593770751416093310/) on September 10, 2012 21:59:38_

Seems to work in some scenarios, but PMD (using JUnit 4.4) gives an unhelpful 

   [pitest] at java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:222)
   [pitest] at java.util.concurrent.FutureTask.get(FutureTask.java:83)

_Original issue: http://code.google.com/p/pitestrunner/issues/detail?id=56_

**Comment by hcoles** [comment]
Finally fixed in 1.1.5

**Comment by lkwg82** [comment]
So this can be closed?
