### ISSUE TITLE
Release 1.4.4 links wrong

### ISSUE THREAD

**Issue by rnveach** [hcoles/pitest#562]
https://github.com/hcoles/pitest/releases/tag/pitest-parent-1.4.4

> `#518 - Experimental BigInteger mutator (thanks @ripdajacker)`
`#513 - Sort mutators in html report (thanks @ThLeu)`
`#553 - Classic mutators from literature (thanls @LaurentTho3)`

Sort mutators is actually #523 .
Classis mutators is actually #533 .

**Comment by maxgabut** [comment]
Hi @rnveach, thanks for letting us know. I updated the release note to link to the right issues.
