### ISSUE TITLE
>=1.4.3 WithHistory not generating properly the report

### ISSUE THREAD

**Issue by josebrandao13** [hcoles/pitest#568]
Hi,

From >=1.4.3 when running with history all the content on the pit-report folder is replaced with an empty XML. 

With version 1.4.2 if I run with withHistory the report is properly generated including the HTML report.

Can somebody help ?

**Comment by hcoles** [comment]
Did you cleat out the history file when you upgraded the version? It will fail with an (unhelpful) error if you do not.

Pitest  1.4.5 runs fine with withHistory on sample projects. Can you provide an example project that reproduces the issues you're seeing along with the precise steps to reproduce?

**Comment by josebrandao13** [comment]
Basically:
*Run pit withHistory = false; Report is generated ok and the pit-report folder has the HTML report.
*Re-run with withHistory = true and the content of the folder is replaced with the xml report empty. Pit runs well in this case the report is just not showing anything.

I have not cleared between versions but I runned without history on the same version and then with history. This should replace the history for a specific version right?

**Comment by hcoles** [comment]
The history file is brittle and will often not be compatible between versions. It should be deleted when you switch versions.

Running without history does not delete the file.

**Comment by josebrandao13** [comment]
Where is the location of the history file by default ?

**Comment by hcoles** [comment]
The file location is logged at info level.

**Comment by josebrandao13** [comment]
I deleted the file, upgraded the version and it worked.
Thanks
