### ISSUE TITLE
Kotlin Generated Code Mutation Survival

### ISSUE THREAD

**Issue by SkittishSloth** [hcoles/pitest#569]
When running against kotlin code, I'm getting a *lot* of false survivals of `removed call to kotlin/jvm/internal/Intrinsics::checkExpressionValueIsNotNull → SURVIVED`. I'm assuming this is code that's generated by the kotlin compiler for non-nullable types; I'm seeing it in lots of places, and I'm definitely not calling it anywhere directly.

Kinda related, on an interpolated String (i.e. "Hello $name"), I'm getting a `removed call to java/lang/StringBuilder::toString → SURVIVED`. I'm early in writing tests for this project, so this might go away when I've actually written coverage for it, but it's a little confusing at first. Not as big a problem as the null check.

If I add the Intrinsics class to the avoidCallsTo configuration, both of these goes away *BUT* I lose a lot of other potentially useful mutations too. (And the StringBuilder one is pretty useful too, assuming it kills when I've added the appropriate tests.) I've tried explicitly adding the method to avoidCalls, tried adding it to excludedMethods, no joy. I didn't expect adding it to avoidCalls to work, I believe that's class level, and I might've been using some wrong syntax for excludedMethods.

Any ideas?

**Comment by hcoles** [comment]
The fix for this would be the kotlin plugin

https://github.com/pitest/pitest-kotlin

However it is looking for someone to develop and maintain it.

**Comment by SkittishSloth** [comment]
Oh wow - I wasn't aware of that. I'll definitely check it out.

Is there any list of plugins like this? I don't recall seeing anything on
the site, I might've just missed it though.

**Comment by JoaoGFarias** [comment]
@hcoles Any hope to it be published, even without active maintenance? https://github.com/pitest/pitest-kotlin/issues/3

**Comment by hugovanelk** [comment]
I solved the problem by using avoidCallsTo in the configuration:

```
 <plugin>
        <groupId>org.pitest</groupId>
        <artifactId>pitest-maven</artifactId>
        <version>1.5.2</version>
        <dependencies>
          <dependency>
            <groupId>org.pitest</groupId>
            <artifactId>pitest-junit5-plugin</artifactId>
            <version>0.12</version>
          </dependency>
        </dependencies>
        <configuration>
          <!-- targetClass and targetTests here -->
          <avoidCallsTo>
            <avoidCallsTo>kotlin.jvm.internal</avoidCallsTo>
            <avoidCallsTo>kotlinx.coroutines</avoidCallsTo>
          </avoidCallsTo>
        </configuration>
      </plugin>
```

**Comment by hcoles** [comment]
Kotlin support is now available at https://docs.arcmutate.com/docs/kotlin.html
