### ISSUE TITLE
"MutationTestMinion" process continually stealing keyboard focus

### ISSUE THREAD

**Issue by bol-com-pschmitz** [hcoles/pitest#581]
While running mutation test coverage using the Maven plugin on my Mac, a process called "MutationTestMinion" (as evidenced by an empty menu bar with the title "MutationTestMinion" appearing) continually steals the keyboard focus from whatever I am doing. This is EXTREMELY ANNOYING and makes it impossible to do anything else while it runs. This is with version org.pitest:pitest-maven:1.4.3. Can this be fixed? Or is there a workaround to mitigate this problem?

**Comment by Stephan202** [comment]
Drive-by-comment, untested (I don't have a Mac myself): @bol-com-pschmitz you could try to pass `-Djava.awt.headless=true` using the [`jvmArgs`](http://pitest.org/quickstart/maven/#jvmargs) setting.

**Comment by bol-com-pschmitz** [comment]
Thanks @Stephan202 , that helped!

Perhaps PIT should be doing that by default? Or if not then it would be good to add this to the documentation.

**Comment by Stephan202** [comment]
I can imagine that 0.01% of PIT users may be negatively affected by unconditionally setting this property, but it does sound like this makes for a good default.

**Comment by maxgabut** [comment]
@bol-com-pschmitz could you try using this branch https://github.com/maxgabut/pitest/tree/headless-by-default to see if it fix you problem ?  If it does I'll submit a pull request with its content.

**Comment by bol-com-pschmitz** [comment]
I tried, and it works!

**Comment by maxgabut** [comment]
It's now merged in master and it will be released in the next version > 1.4.7
