### ISSUE TITLE
Does PITtest support symbolic execution?

### ISSUE THREAD

**Issue by Marvinmw** [hcoles/pitest#583]
Does PITtest support symbolic execution?

**Comment by maxgabut** [comment]
I'm not sure to understand what you mean by that. Could you elaborate a bit more ?

**Comment by Marvinmw** [comment]
Thanks for your reply. I mean if PIT can generate the test cases like KLEE by symbolic execution.

**Comment by maxgabut** [comment]
PIT does not generate test cases. It generate "mutant" version of the classes under test (by changing their bytecode) and then run tests on them to know if the test are able to detect the mutations.
