### ISSUE TITLE
Exclude mutator for class or method

### ISSUE THREAD

**Issue by Alexilmarranen** [hcoles/pitest#585]
How to exclude some mutator by name for method, class or package?

Since the latest version of ROR mutations survive for trivial code:
`
...
if (this.isValid())
...
`

> 2. equal to less or equal → SURVIVED

I would like to exclude a mutation for the method, because changing the test code to kill this mutation seems strange to me.
Maybe I misunderstand something...

Thanks!

**Comment by Alexilmarranen** [comment]
I researched the code and documentation more carefully - could there be an increase in the number of mutator groups and adding the group STABLE = ALL - EXPERIMENTAL would solve a similar problem?

**Comment by maxgabut** [comment]
Hi @Alexilmarranen, your second idea (with a new mutator group) would impact all classes. Would it be OK for you ?

**Comment by Alexilmarranen** [comment]
@maxgabut Прошу прощения за поздний ответ. Я думаю вы правы - это плохая идея. Моя изначальная проблема также решена - вероятно мутация выживала при тестировании с бета-версией JUnit. Думаю эта issue должна быть закрыта.

**Comment by rnveach** [comment]
Google translate:
> I'm sorry for the late reply. I think you are right - this is a bad idea. My original problem was also solved - the mutation probably survived during testing with the beta version of JUnit. I think this issue should be closed.

**Comment by Alexilmarranen** [comment]
Sorry for mistake with language :(
