### ISSUE TITLE
Exclude synthetic classes by default

### ISSUE THREAD

**Issue by SchulteMarkus** [hcoles/pitest#591]
Hi,

as part of my project, I am getting classes produced, which will have a name like _$SomeServiceDefinition.class_.

**Proposal**: Add "*.$*" as default configuration for excluded classes.

**Background**: I am using [micronaut-inject](https://docs.micronaut.io/latest/guide/index.html#ioc) as CDI container in my application. Mentioned classes will be produced as part of compiling, and Pitest will fail with an error like

> [ERROR] Failed to execute goal org.pitest:pitest-maven:1.4.6:mutationCoverage (default-cli) on project abcdef: Execution default-cli of goal org.pitest:pitest-maven:1.4.6:mutationCoverage failed: The class com.zuora.$SomeServiceDefinition.class does not contain source debug information. All classes must have an associated source file

, following configuration is my **workaround**

```
<configuration>
  <excludedClasses>
    <!-- Synthetic classes -->
    <excludedClass>*.$*</excludedClass>
  </excludedClasses>
</configuration>
```

**Comment by maxgabut** [comment]
Hi @SchulteMarkus, thank you for submitting this issue.

You're presenting your solution as a workaround, but actually it looks good to me.

In fact as long as the configuration allows you to use the framework of you choice, I think that it's fine. Adding rules to the defaults to match one project or framework creates the risk of a conflict with someone else's use case (arguably the riks is low here, be still).

**Comment by SchulteMarkus** [comment]
Hi @maxgabut ,

thanks for your feedback! In my opinion, my solution should be part of the defaults, but I can of course understand your point.
