### ISSUE TITLE
PitTest not detecting any testNG tests

### ISSUE THREAD

**Issue by wschilling** [hcoles/pitest#602]
I am running a code baseline that was used approximately one year ago with PiTest to verify some code with what was at the current time the current PitTest version.  I opened the code up with the latest IntelliJ plug in and tried to duplicate the results.  The tool is unable to find any TestNG tests.

I am attaching a verbose output log below.  I have also attached the project.  
C:\bin\Java\jdk-11.0.1\bin\java.exe "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA 2018.2.6\lib\idea_rt.jar=3917:C:\Program Files\JetBrains\IntelliJ IDEA 2018.2.6\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\JetBrains\IntelliJ IDEA 2018.2.6\lib\idea_rt.jar" com.intellij.rt.execution.CommandLineWrapper C:\Users\walte\AppData\Local\Temp\idea_classpath55808229 org.pitest.mutationtest.commandline.MutationCoverageReport --reportDir E:/temp/PITTestDemo/report --sourceDirs E:/temp/PITTestDemo/src --targetClasses demo.* --targetTests demo.* --outputFormats XML,HTML --verbose=true --includeLaunchClasspath false --classPath E:\temp\PITTestDemo\out\test\PITTestDemo,E:\temp\PITTestDemo\out\production\PITTestDemo,C:\Users\walte\.m2\repository\org\testng\testng\6.10\testng-6.10.jar,C:\Users\walte\.m2\repository\com\beust\jcommander\1.48\jcommander-1.48.jar,C:\Users\walte\.m2\repository\junit\junit\4.12\junit-4.12.jar,C:\Users\walte\.m2\repository\org\hamcrest\hamcrest-core\1.3\hamcrest-core-1.3.jar
11:48:09 AM PIT >> INFO : ---------------------------------------------------------------------------
11:48:09 AM PIT >> INFO : Enabled (+) and disabled (-) features.
11:48:09 AM PIT >> INFO : -----------------------------------------
11:48:09 AM PIT >> INFO : +FFBLOCK        Filters mutations in code duplicated by finally block inlining
11:48:09 AM PIT >> INFO : +FSTATI         Filters mutations in static initializers and code called only from them
11:48:09 AM PIT >> INFO : +FSEQUIVEQUALS  Filters equivalent mutations that affect only performance in short cutting equals methods
11:48:09 AM PIT >> INFO : +FFEACH         Filters mutations in compiler generated code that implements for each loops
11:48:09 AM PIT >> INFO : +FINFINC        Filters mutations to increments that may cause infinite loops
11:48:09 AM PIT >> INFO : +FFLOOP         Filters any mutations to increments in for loops as they may cause timeouts
11:48:09 AM PIT >> INFO : +FRETEQUIV      Filters return vals mutants with bytecode equivalent to the unmutated class
11:48:09 AM PIT >> INFO : +FINULL         Filters mutations in compiler generated code that checks for null by calling getClass
11:48:09 AM PIT >> INFO : +FTRYWR         Filters mutations in code generated for try with resources statements
11:48:09 AM PIT >> INFO : +FKOTLIN        Filters out junk mutations in bytecode created by compiler for kotlin language features
11:48:09 AM PIT >> INFO : +FSTATINIT      Filters mutations in static initializers and code called only from them
11:48:09 AM PIT >> INFO : +FLOGCALL       Filters mutations in code that makes calls to logging frameworks
11:48:09 AM PIT >> INFO : +FINFIT         Filters mutations that may cause infinite loops by removing calls to iterator.next
11:48:09 AM PIT >> INFO : +FANN           Filters mutations in classes and methods with matching annotations of class or runtime retention
11:48:09 AM PIT >> INFO :   [annotation]    Annotation to avoid (full package name not required)
11:48:09 AM PIT >> INFO : -CLASSLIMIT     Limits the maximum number of mutations per class
11:48:09 AM PIT >> INFO :   [limit]         Integer value for maximum mutations to create per class
11:48:09 AM PIT >> INFO : -EXPORT         Exports mutants bytecode and other details to disk
11:48:09 AM PIT >> INFO : ---------------------------------------------------------------------------
11:48:10 AM PIT >> FINE : Running report with ReportOptions [targetClasses=[demo.*], excludedMethods=[], excludedClasses=[], excludedTestClasses=[], codePaths=[], reportDir=E:/temp/PITTestDemo/report, historyInputLocation=null, historyOutputLocation=null, sourceDirs=[E:\temp\PITTestDemo\src], classPathElements=[C:\Users\walte\.IntelliJIdea2018.2\config\plugins\pit-idea-plugin\lib\pitest-1.4.3.jar, E:\temp\PITTestDemo\out\test\PITTestDemo, E:\temp\PITTestDemo\out\production\PITTestDemo, C:\Users\walte\.m2\repository\org\testng\testng\6.10\testng-6.10.jar, C:\Users\walte\.m2\repository\com\beust\jcommander\1.48\jcommander-1.48.jar, C:\Users\walte\.m2\repository\junit\junit\4.12\junit-4.12.jar, C:\Users\walte\.m2\repository\org\hamcrest\hamcrest-core\1.3\hamcrest-core-1.3.jar], mutators=[], features=[], dependencyAnalysisMaxDistance=-1, jvmArgs=[], numberOfThreads=1, timeoutFactor=1.25, timeoutConstant=4000, targetTests=[^demo\..*$], loggingClasses=[], maxMutationsPerClass=0, verbose=true, failWhenNoMutations=true, outputs=[XML, HTML], groupConfig=TestGroupConfig [excludedGroups=[], includedGroups=[]], fullMutationMatrix=false, mutationUnitSize=0, shouldCreateTimestampedReports=true, detectInlinedCode=false, exportLineCoverage=false, mutationThreshold=0, coverageThreshold=0, mutationEngine=gregor, javaExecutable=null, includeLaunchClasspath=false, properties={}, maxSurvivors=-1, excludedRunners=[], includedTestMethods=[], testPlugin=junit, useClasspathJar=false]
11:48:10 AM PIT >> FINE : System class path is C:\Users\walte\.IntelliJIdea2018.2\config\plugins\pit-idea-plugin\lib\xpp3_min-1.1.4c.jar;C:\Users\walte\.IntelliJIdea2018.2\config\plugins\pit-idea-plugin\lib\xmlpull-1.1.3.1.jar;C:\Users\walte\.IntelliJIdea2018.2\config\plugins\pit-idea-plugin\lib\xstream-1.4.8.jar;C:\Users\walte\.IntelliJIdea2018.2\config\plugins\pit-idea-plugin\lib\pitest-entry-1.4.3.jar;C:\Users\walte\.IntelliJIdea2018.2\config\plugins\pit-idea-plugin\lib\pitest-command-line-1.4.3.jar;C:\Users\walte\.IntelliJIdea2018.2\config\plugins\pit-idea-plugin\lib\pitest-1.4.3.jar;E:\temp\PITTestDemo\out\test\PITTestDemo;E:\temp\PITTestDemo\out\production\PITTestDemo;C:\Users\walte\.m2\repository\org\testng\testng\6.10\testng-6.10.jar;C:\Users\walte\.m2\repository\com\beust\jcommander\1.48\jcommander-1.48.jar;C:\Users\walte\.m2\repository\junit\junit\4.12\junit-4.12.jar;C:\Users\walte\.m2\repository\org\hamcrest\hamcrest-core\1.3\hamcrest-core-1.3.jar
11:48:10 AM PIT >> FINE : Maximum available memory is 4010 mb
11:48:10 AM PIT >> FINE : MINION : Installing PIT agent

11:48:10 AM PIT >> INFO : Sending 2 test classes to minion
11:48:10 AM PIT >> INFO : Sent tests to minion
11:48:10 AM PIT >> INFO : MINION : 11:48:10 AM PIT >> FINE : Expecting 2 tests classes from parent
11:48:10 AM PIT >> FINE : Tests classes received
11:48:10 AM PIT >> INFO : Checking environment

11:48:10 AM PIT >> INFO : MINION : 11:48:10 AM PIT >> INFO : Found  0 tests

11:48:10 AM PIT >> INFO : MINION : 11:48:10 AM PIT >> INFO : Dependency analysis reduced number of potential tests by 0

11:48:10 AM PIT >> INFO : MINION : 11:48:10 AM PIT >> INFO : 0 tests received

11:48:10 AM PIT >> INFO : MINION : 11:48:10 AM PIT >> FINE : Running 0 units

11:48:10 AM PIT >> FINE : Coverage generator Minion exited ok
11:48:10 AM PIT >> INFO : Calculated coverage in 0 seconds.
11:48:10 AM PIT >> FINE : Used memory after coverage calculation 11 mb
11:48:10 AM PIT >> FINE : Free Memory after coverage calculation 240 mb
11:48:10 AM PIT >> FINE : According to coverage no tests hit the mutation MutationDetails [id=MutationIdentifier [location=Location [clazz=demo.CalculatorExample, method=add, methodDesc=(II)I], indexes=[5], mutator=org.pitest.mutationtest.engine.gregor.mutators.MathMutator], filename=CalculatorExample.java, block=1, lineNumber=21, description=Replaced integer addition with subtraction, testsInOrder=[], isInFinallyBlock=false, poison=NORMAL]
11:48:10 AM PIT >> FINE : According to coverage no tests hit the mutation MutationDetails [id=MutationIdentifier [location=Location [clazz=demo.CalculatorExample, method=add, methodDesc=(II)I], indexes=[6], mutator=org.pitest.mutationtest.engine.gregor.mutators.ReturnValsMutator], filename=CalculatorExample.java, block=1, lineNumber=21, description=replaced return of integer sized value with (x == 0 ? 1 : 0), testsInOrder=[], isInFinallyBlock=false, poison=NORMAL]
11:48:10 AM PIT >> FINE : According to coverage no tests hit the mutation MutationDetails [id=MutationIdentifier [location=Location [clazz=demo.CalculatorExample, method=subtract, methodDesc=(II)I], indexes=[5], mutator=org.pitest.mutationtest.engine.gregor.mutators.MathMutator], filename=CalculatorExample.java, block=2, lineNumber=35, description=Replaced integer subtraction with addition, testsInOrder=[], isInFinallyBlock=false, poison=NORMAL]
11:48:10 AM PIT >> FINE : According to coverage no tests hit the mutation MutationDetails [id=MutationIdentifier [location=Location [clazz=demo.CalculatorExample, method=subtract, methodDesc=(II)I], indexes=[6], mutator=org.pitest.mutationtest.engine.gregor.mutators.ReturnValsMutator], filename=CalculatorExample.java, block=2, lineNumber=35, description=replaced return of integer sized value with (x == 0 ? 1 : 0), testsInOrder=[], isInFinallyBlock=false, poison=NORMAL]
11:48:10 AM PIT >> FINE : According to coverage no tests hit the mutation MutationDetails [id=MutationIdentifier [location=Location [clazz=demo.CalculatorExample, method=multiply, methodDesc=(II)I], indexes=[5], mutator=org.pitest.mutationtest.engine.gregor.mutators.MathMutator], filename=CalculatorExample.java, block=3, lineNumber=46, description=Replaced integer multiplication with division, testsInOrder=[], isInFinallyBlock=false, poison=NORMAL]
11:48:10 AM PIT >> FINE : According to coverage no tests hit the mutation MutationDetails [id=MutationIdentifier [location=Location [clazz=demo.CalculatorExample, method=multiply, methodDesc=(II)I], indexes=[6], mutator=org.pitest.mutationtest.engine.gregor.mutators.ReturnValsMutator], filename=CalculatorExample.java, block=3, lineNumber=46, description=replaced return of integer sized value with (x == 0 ? 1 : 0), testsInOrder=[], isInFinallyBlock=false, poison=NORMAL]
11:48:10 AM PIT >> FINE : According to coverage no tests hit the mutation MutationDetails [id=MutationIdentifier [location=Location [clazz=demo.CalculatorExample, method=divide, methodDesc=(II)I], indexes=[5], mutator=org.pitest.mutationtest.engine.gregor.mutators.MathMutator], filename=CalculatorExample.java, block=4, lineNumber=57, description=Replaced integer division with multiplication, testsInOrder=[], isInFinallyBlock=false, poison=NORMAL]
11:48:10 AM PIT >> FINE : According to coverage no tests hit the mutation MutationDetails [id=MutationIdentifier [location=Location [clazz=demo.CalculatorExample, method=divide, methodDesc=(II)I], indexes=[6], mutator=org.pitest.mutationtest.engine.gregor.mutators.ReturnValsMutator], filename=CalculatorExample.java, block=4, lineNumber=57, description=replaced return of integer sized value with (x == 0 ? 1 : 0), testsInOrder=[], isInFinallyBlock=false, poison=NORMAL]
11:48:10 AM PIT >> FINE : According to coverage no tests hit the mutation MutationDetails [id=MutationIdentifier [location=Location [clazz=demo.CalculatorExample, method=summation, methodDesc=(I)I], indexes=[9], mutator=org.pitest.mutationtest.engine.gregor.mutators.NegateConditionalsMutator], filename=CalculatorExample.java, block=5, lineNumber=69, description=negated conditional, testsInOrder=[], isInFinallyBlock=false, poison=NORMAL]
11:48:10 AM PIT >> FINE : According to coverage no tests hit the mutation MutationDetails [id=MutationIdentifier [location=Location [clazz=demo.CalculatorExample, method=summation, methodDesc=(I)I], indexes=[9], mutator=org.pitest.mutationtest.engine.gregor.mutators.ConditionalsBoundaryMutator], filename=CalculatorExample.java, block=5, lineNumber=69, description=changed conditional boundary, testsInOrder=[], isInFinallyBlock=false, poison=NORMAL]
11:48:10 AM PIT >> FINE : According to coverage no tests hit the mutation MutationDetails [id=MutationIdentifier [location=Location [clazz=demo.CalculatorExample, method=summation, methodDesc=(I)I], indexes=[14], mutator=org.pitest.mutationtest.engine.gregor.mutators.MathMutator], filename=CalculatorExample.java, block=6, lineNumber=70, description=Replaced integer addition with subtraction, testsInOrder=[], isInFinallyBlock=false, poison=NORMAL]
11:48:10 AM PIT >> FINE : According to coverage no tests hit the mutation MutationDetails [id=MutationIdentifier [location=Location [clazz=demo.CalculatorExample, method=summation, methodDesc=(I)I], indexes=[18], mutator=org.pitest.mutationtest.engine.gregor.mutators.IncrementsMutator], filename=CalculatorExample.java, block=6, lineNumber=71, description=Changed increment from -1 to 1, testsInOrder=[], isInFinallyBlock=false, poison=NORMAL]
11:48:10 AM PIT >> FINE : According to coverage no tests hit the mutation MutationDetails [id=MutationIdentifier [location=Location [clazz=demo.CalculatorExample, method=summation, methodDesc=(I)I], indexes=[24], mutator=org.pitest.mutationtest.engine.gregor.mutators.ReturnValsMutator], filename=CalculatorExample.java, block=7, lineNumber=73, description=replaced return of integer sized value with (x == 0 ? 1 : 0), testsInOrder=[], isInFinallyBlock=false, poison=NORMAL]
11:48:10 AM PIT >> FINE : According to coverage no tests hit the mutation MutationDetails [id=MutationIdentifier [location=Location [clazz=demo.CalculatorExample, method=isPositive, methodDesc=(I)Z], indexes=[4], mutator=org.pitest.mutationtest.engine.gregor.mutators.NegateConditionalsMutator], filename=CalculatorExample.java, block=8, lineNumber=83, description=negated conditional, testsInOrder=[], isInFinallyBlock=false, poison=NORMAL]
11:48:10 AM PIT >> FINE : According to coverage no tests hit the mutation MutationDetails [id=MutationIdentifier [location=Location [clazz=demo.CalculatorExample, method=isPositive, methodDesc=(I)Z], indexes=[4], mutator=org.pitest.mutationtest.engine.gregor.mutators.ConditionalsBoundaryMutator], filename=CalculatorExample.java, block=8, lineNumber=83, description=changed conditional boundary, testsInOrder=[], isInFinallyBlock=false, poison=NORMAL]
11:48:10 AM PIT >> FINE : According to coverage no tests hit the mutation MutationDetails [id=MutationIdentifier [location=Location [clazz=demo.CalculatorExample, method=isPositive, methodDesc=(I)Z], indexes=[12], mutator=org.pitest.mutationtest.engine.gregor.mutators.ReturnValsMutator], filename=CalculatorExample.java, block=10, lineNumber=83, description=replaced return of integer sized value with (x == 0 ? 1 : 0), testsInOrder=[], isInFinallyBlock=false, poison=NORMAL]
11:48:10 AM PIT >> FINE : According to coverage no tests hit the mutation MutationDetails [id=MutationIdentifier [location=Location [clazz=demo.CalculatorExample, method=compare, methodDesc=(II)I], indexes=[9], mutator=org.pitest.mutationtest.engine.gregor.mutators.NegateConditionalsMutator], filename=CalculatorExample.java, block=11, lineNumber=95, description=negated conditional, testsInOrder=[], isInFinallyBlock=false, poison=NORMAL]
11:48:10 AM PIT >> FINE : According to coverage no tests hit the mutation MutationDetails [id=MutationIdentifier [location=Location [clazz=demo.CalculatorExample, method=compare, methodDesc=(II)I], indexes=[20], mutator=org.pitest.mutationtest.engine.gregor.mutators.NegateConditionalsMutator], filename=CalculatorExample.java, block=13, lineNumber=97, description=negated conditional, testsInOrder=[], isInFinallyBlock=false, poison=NORMAL]
11:48:10 AM PIT >> FINE : According to coverage no tests hit the mutation MutationDetails [id=MutationIdentifier [location=Location [clazz=demo.CalculatorExample, method=compare, methodDesc=(II)I], indexes=[20], mutator=org.pitest.mutationtest.engine.gregor.mutators.ConditionalsBoundaryMutator], filename=CalculatorExample.java, block=13, lineNumber=97, description=changed conditional boundary, testsInOrder=[], isInFinallyBlock=false, poison=NORMAL]
11:48:10 AM PIT >> FINE : According to coverage no tests hit the mutation MutationDetails [id=MutationIdentifier [location=Location [clazz=demo.CalculatorExample, method=compare, methodDesc=(II)I], indexes=[35], mutator=org.pitest.mutationtest.engine.gregor.mutators.ReturnValsMutator], filename=CalculatorExample.java, block=15, lineNumber=102, description=replaced return of integer sized value with (x == 0 ? 1 : 0), testsInOrder=[], isInFinallyBlock=false, poison=NORMAL]
11:48:10 AM PIT >> FINE : According to coverage no tests hit the mutation MutationDetails [id=MutationIdentifier [location=Location [clazz=demo.CalculatorTest, method=testSimpleAdd, methodDesc=()V], indexes=[9], mutator=org.pitest.mutationtest.engine.gregor.mutators.VoidMethodCallMutator], filename=CalculatorTest.java, block=2, lineNumber=33, description=removed call to org/testng/AssertJUnit::assertEquals, testsInOrder=[], isInFinallyBlock=false, poison=NORMAL]
11:48:10 AM PIT >> FINE : According to coverage no tests hit the mutation MutationDetails [id=MutationIdentifier [location=Location [clazz=demo.CalculatorTest, method=testSubtract0, methodDesc=()V], indexes=[9], mutator=org.pitest.mutationtest.engine.gregor.mutators.VoidMethodCallMutator], filename=CalculatorTest.java, block=3, lineNumber=41, description=removed call to org/testng/AssertJUnit::assertEquals, testsInOrder=[], isInFinallyBlock=false, poison=NORMAL]
11:48:10 AM PIT >> FINE : According to coverage no tests hit the mutation MutationDetails [id=MutationIdentifier [location=Location [clazz=demo.CalculatorTest, method=testSubtract1, methodDesc=()V], indexes=[9], mutator=org.pitest.mutationtest.engine.gregor.mutators.VoidMethodCallMutator], filename=CalculatorTest.java, block=4, lineNumber=50, description=removed call to org/testng/AssertJUnit::assertEquals, testsInOrder=[], isInFinallyBlock=false, poison=NORMAL]
11:48:10 AM PIT >> FINE : According to coverage no tests hit the mutation MutationDetails [id=MutationIdentifier [location=Location [clazz=demo.CalculatorTest, method=testMultiply, methodDesc=()V], indexes=[9], mutator=org.pitest.mutationtest.engine.gregor.mutators.VoidMethodCallMutator], filename=CalculatorTest.java, block=5, lineNumber=59, description=removed call to org/testng/AssertJUnit::assertEquals, testsInOrder=[], isInFinallyBlock=false, poison=NORMAL]
11:48:10 AM PIT >> FINE : According to coverage no tests hit the mutation MutationDetails [id=MutationIdentifier [location=Location [clazz=demo.CalculatorTest, method=testDivide, methodDesc=()V], indexes=[9], mutator=org.pitest.mutationtest.engine.gregor.mutators.VoidMethodCallMutator], filename=CalculatorTest.java, block=6, lineNumber=69, description=removed call to org/testng/AssertJUnit::assertEquals, testsInOrder=[], isInFinallyBlock=false, poison=NORMAL]
11:48:10 AM PIT >> FINE : According to coverage no tests hit the mutation MutationDetails [id=MutationIdentifier [location=Location [clazz=demo.CalculatorTest, method=testDivide, methodDesc=()V], indexes=[18], mutator=org.pitest.mutationtest.engine.gregor.mutators.VoidMethodCallMutator], filename=CalculatorTest.java, block=6, lineNumber=70, description=removed call to org/testng/AssertJUnit::assertEquals, testsInOrder=[], isInFinallyBlock=false, poison=NORMAL]
11:48:10 AM PIT >> FINE : According to coverage no tests hit the mutation MutationDetails [id=MutationIdentifier [location=Location [clazz=demo.CalculatorTest, method=testSummation, methodDesc=()V], indexes=[8], mutator=org.pitest.mutationtest.engine.gregor.mutators.VoidMethodCallMutator], filename=CalculatorTest.java, block=7, lineNumber=76, description=removed call to org/testng/AssertJUnit::assertEquals, testsInOrder=[], isInFinallyBlock=false, poison=NORMAL]
11:48:10 AM PIT >> FINE : According to coverage no tests hit the mutation MutationDetails [id=MutationIdentifier [location=Location [clazz=demo.CalculatorTest, method=testSummation, methodDesc=()V], indexes=[16], mutator=org.pitest.mutationtest.engine.gregor.mutators.VoidMethodCallMutator], filename=CalculatorTest.java, block=7, lineNumber=77, description=removed call to org/testng/AssertJUnit::assertEquals, testsInOrder=[], isInFinallyBlock=false, poison=NORMAL]
11:48:10 AM PIT >> FINE : According to coverage no tests hit the mutation MutationDetails [id=MutationIdentifier [location=Location [clazz=demo.CalculatorTest, method=testSummation, methodDesc=()V], indexes=[24], mutator=org.pitest.mutationtest.engine.gregor.mutators.VoidMethodCallMutator], filename=CalculatorTest.java, block=7, lineNumber=78, description=removed call to org/testng/AssertJUnit::assertEquals, testsInOrder=[], isInFinallyBlock=false, poison=NORMAL]
11:48:10 AM PIT >> FINE : According to coverage no tests hit the mutation MutationDetails [id=MutationIdentifier [location=Location [clazz=demo.CalculatorTest, method=testPositive, methodDesc=()V], indexes=[7], mutator=org.pitest.mutationtest.engine.gregor.mutators.VoidMethodCallMutator], filename=CalculatorTest.java, block=8, lineNumber=83, description=removed call to org/testng/AssertJUnit::assertTrue, testsInOrder=[], isInFinallyBlock=false, poison=NORMAL]
11:48:10 AM PIT >> FINE : According to coverage no tests hit the mutation MutationDetails [id=MutationIdentifier [location=Location [clazz=demo.CalculatorTest, method=testPositive, methodDesc=()V], indexes=[14], mutator=org.pitest.mutationtest.engine.gregor.mutators.VoidMethodCallMutator], filename=CalculatorTest.java, block=8, lineNumber=84, description=removed call to org/testng/AssertJUnit::assertTrue, testsInOrder=[], isInFinallyBlock=false, poison=NORMAL]
11:48:10 AM PIT >> FINE : According to coverage no tests hit the mutation MutationDetails [id=MutationIdentifier [location=Location [clazz=demo.CalculatorTest, method=testPositive, methodDesc=()V], indexes=[21], mutator=org.pitest.mutationtest.engine.gregor.mutators.VoidMethodCallMutator], filename=CalculatorTest.java, block=8, lineNumber=85, description=removed call to org/testng/AssertJUnit::assertFalse, testsInOrder=[], isInFinallyBlock=false, poison=NORMAL]
11:48:10 AM PIT >> FINE : According to coverage no tests hit the mutation MutationDetails [id=MutationIdentifier [location=Location [clazz=demo.CalculatorTest, method=testCompare, methodDesc=()V], indexes=[9], mutator=org.pitest.mutationtest.engine.gregor.mutators.VoidMethodCallMutator], filename=CalculatorTest.java, block=9, lineNumber=90, description=removed call to org/testng/AssertJUnit::assertEquals, testsInOrder=[], isInFinallyBlock=false, poison=NORMAL]
11:48:10 AM PIT >> FINE : According to coverage no tests hit the mutation MutationDetails [id=MutationIdentifier [location=Location [clazz=demo.CalculatorTest, method=testCompare, methodDesc=()V], indexes=[18], mutator=org.pitest.mutationtest.engine.gregor.mutators.VoidMethodCallMutator], filename=CalculatorTest.java, block=9, lineNumber=91, description=removed call to org/testng/AssertJUnit::assertEquals, testsInOrder=[], isInFinallyBlock=false, poison=NORMAL]
11:48:10 AM PIT >> FINE : According to coverage no tests hit the mutation MutationDetails [id=MutationIdentifier [location=Location [clazz=demo.CalculatorTest, method=testCompare, methodDesc=()V], indexes=[27], mutator=org.pitest.mutationtest.engine.gregor.mutators.VoidMethodCallMutator], filename=CalculatorTest.java, block=9, lineNumber=92, description=removed call to org/testng/AssertJUnit::assertEquals, testsInOrder=[], isInFinallyBlock=false, poison=NORMAL]
11:48:10 AM PIT >> INFO : Created  2 mutation test units
11:48:10 AM PIT >> FINE : Used memory before analysis start 19 mb
11:48:10 AM PIT >> FINE : Free Memory before analysis start 232 mb
11:48:10 AM PIT >> FINE : Running 2 units
11:48:10 AM PIT >> INFO : Completed in 0 seconds
================================================================================
- Mutators
================================================================================
> org.pitest.mutationtest.engine.gregor.mutators.ConditionalsBoundaryMutator
>> Generated 3 Killed 0 (0%)
> KILLED 0 SURVIVED 0 TIMED_OUT 0 NON_VIABLE 0 
> MEMORY_ERROR 0 NOT_STARTED 0 STARTED 0 RUN_ERROR 0 
> NO_COVERAGE 3 
--------------------------------------------------------------------------------
> org.pitest.mutationtest.engine.gregor.mutators.IncrementsMutator
>> Generated 1 Killed 0 (0%)
> KILLED 0 SURVIVED 0 TIMED_OUT 0 NON_VIABLE 0 
> MEMORY_ERROR 0 NOT_STARTED 0 STARTED 0 RUN_ERROR 0 
> NO_COVERAGE 1 
--------------------------------------------------------------------------------
> org.pitest.mutationtest.engine.gregor.mutators.VoidMethodCallMutator
>> Generated 15 Killed 0 (0%)
> KILLED 0 SURVIVED 0 TIMED_OUT 0 NON_VIABLE 0 
> MEMORY_ERROR 0 NOT_STARTED 0 STARTED 0 RUN_ERROR 0 
> NO_COVERAGE 15 
--------------------------------------------------------------------------------
> org.pitest.mutationtest.engine.gregor.mutators.ReturnValsMutator
>> Generated 7 Killed 0 (0%)
> KILLED 0 SURVIVED 0 TIMED_OUT 0 NON_VIABLE 0 
> MEMORY_ERROR 0 NOT_STARTED 0 STARTED 0 RUN_ERROR 0 
> NO_COVERAGE 7 
--------------------------------------------------------------------------------
> org.pitest.mutationtest.engine.gregor.mutators.MathMutator
>> Generated 5 Killed 0 (0%)
> KILLED 0 SURVIVED 0 TIMED_OUT 0 NON_VIABLE 0 
> MEMORY_ERROR 0 NOT_STARTED 0 STARTED 0 RUN_ERROR 0 
> NO_COVERAGE 5 
--------------------------------------------------------------------------------
> org.pitest.mutationtest.engine.gregor.mutators.NegateConditionalsMutator
>> Generated 4 Killed 0 (0%)
> KILLED 0 SURVIVED 0 TIMED_OUT 0 NON_VIABLE 0 
> MEMORY_ERROR 0 NOT_STARTED 0 STARTED 0 RUN_ERROR 0 
> NO_COVERAGE 4 
--------------------------------------------------------------------------------
================================================================================
- Timings
================================================================================
> scan classpath : < 1 second
> coverage and dependency analysis : < 1 second
> build mutation tests : < 1 second
> run mutation analysis : < 1 second
--------------------------------------------------------------------------------
> Total  : < 1 second
--------------------------------------------------------------------------------
================================================================================
- Statistics
================================================================================
>> Generated 35 mutations Killed 0 (0%)
>> Ran 0 tests (0 tests per mutation)

Process finished with exit code 0
Open report in browser

[PITTestDemo.zip](https://github.com/hcoles/pitest/files/3139065/PITTestDemo.zip)

**Comment by VGoudkov** [comment]
**pom.xml** (part)

```
<dependencies>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
        </dependency>
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>6.14.3</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.pitest</groupId>
                <artifactId>pitest-maven</artifactId>
                <version>1.4.8</version>
                <configuration>
                    <targetClasses>
                        <param>
                            my.classes.packages.*
                        </param>
                    </targetClasses>
                    <targetTests>
                        <param>
                            my.classes.packages.*
                        </param>
                    </targetTests>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
        </plugins>
    </build>
```

**Test method**
```
import org.testng.annotations.Test;

import static org.testng.Assert.assertFalse;
import static org.testng.Assert.assertTrue;

public class AppTest {
    @Test
    @org.junit.Test
    public void testIsOdd() {
        assertTrue(App.isEven(2));
        assertFalse(App.isEven(3));
    }
}
```

**Comment by szpak** [comment]
@VGoudkov The built-in TestNG plugin for PIT has to be explicitly activated (since 1.3.0 or so). Try to set `testPlugin` to `testng`.
