### ISSUE TITLE
Transfer Pitclipse repository to the Pitest organization

### ISSUE THREAD

**Issue by echebbi** [hcoles/pitest#619]
Hi,

I have recently started to contribute to [Pitclipse](https://github.com/philglover/pitclipse), which provides an Eclipse IDE integration for Pitest. @philglover (the author of the project) and I think that it would be relevant to move the repository under the Pitest organization.

Would that be possible?

@philglover according to [the docs](https://help.github.com/en/articles/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account) I believe that it will be up to you to start the transfer

Moreover, we would like to benefit from the following CI tools:
 -  Travis CI (the repo is already using it, but I guess that some paths will have to be changed)
 -  CodeCov
 -  SonarCloud

I am a collaborator of the project but it seems that it's not enough to be able to activate them (not sure about SonarCloud though) so one of the owners will have to do this.

**Comment by hcoles** [comment]
If @philglover transfers the repo across I can set you both up as admins.

Alternatively I can clone it under the org.

**Comment by divyakumarjain** [comment]
@hcoles seems like the is no progress on this topic. Do you want to clone the repo?

Seems like there are lot open issues for piclipse.

**Comment by echebbi** [comment]
I still do not have any news from @philglover, even though I sent him a mail a week ago.

Regarding Pitclipse, a lot of issues should be fixed by PR https://github.com/philglover/pitclipse/pull/80.

**Comment by hcoles** [comment]
Happy to clone it, but I think it's @echebbi's call on whether to do that now or wait for a response from @philglover

**Comment by echebbi** [comment]
I just received a mail from @philglover: he does not have access to its PC at the moment but still managed to transfer the ownership!

> See [https://github.com/pitest/pitclipse](https://github.com/pitest/pitclipse)

@hcoles could you grant me the admin rights so that I can configure the different tools?

**Comment by philglover** [comment]
As far as I can tell, it is transferred now.

**Comment by hcoles** [comment]
@philglover Thanks Phil, it looks transferred to me too.

**Comment by hcoles** [comment]
@echebbi You should have admin rights now.

**Comment by echebbi** [comment]
After a few tests I can confirm that I have the admin rights now, thank you! I successfully managed to configure [Travis CI](https://travis-ci.com/pitest/pitclipse), [CodeCov](https://codecov.io/github/pitest/pitclipse) and [SonarCloud](https://sonarcloud.io/dashboard?id=org.pitest%3Aorg.pitest.pitclipse).

However, two problems remain:

1. PR are not decorated by CodeCov and SonarCloud. To solve this, I believe that both apps must be allowed by the Pitest organization. I'll investiguate this later but it will likely require an action from you @hcoles.

2. Travis CI does not send tests results to SonarCloud. It seems that for some reason Travis CI does not use properly the SonarCloud token I give it. I'm currently trying to fix this issue; I think that I should be able to do this by myself.

I'll close this issue once those problems have been fixed.

**Comment by echebbi** [comment]
I finally managed to use SonarCloud properly, so the second issue is fixed.

@hcoles you should have received requests from the [CodeCov](https://github.com/apps/codecov) and [SonarCloud](https://github.com/apps/sonarcloud) GitHub Apps to access the _pitclipse_ repository. Accepting them should be enough to allow PR decoration.

**Comment by hcoles** [comment]
@echebbi That should be done now.

**Comment by echebbi** [comment]
Works like a charm, thank you!

![image](https://user-images.githubusercontent.com/25926433/63089267-8bcc6900-bf57-11e9-8d5f-0b3175f1793d.png)

**Comment by LorenzoBettini** [comment]
Hi

sorry if I go back to this issue but I've been trying to get in touch with @echebbi without success.
There are few problems with the deployed composite update site of Pitclipse that should be fixed. Moreover, Bintray is going to shut down soon and we should find another place to host the Eclipse update site of Pitclipse (not to mention that probably also Travis CI is not a good solution anymore due to their changed free plan). I contributed to Pitclipse in the past and I'd like to contribute a new CI infrastructure and a new place for the update site (I was thinking of GitHub pages but if there are other suggestions...).
Is there any chance to have admin rights?
Of course, I could fork the project but I'd like to avoid that since it's already in the pitest organization.
Thanks in advance
Lorenzo

**Comment by hcoles** [comment]
Hi @LorenzoBettini. Thanks for looking into this. I'm happy to set you up with admin rights. I'd suggest creating an issue on the pitclipse project to cover the "few problems" with the update site so there's a place for discussion in case there's any disagrement on the approach.

**Comment by echebbi** [comment]
Hi Lorenzo, Henri.  I'm sorry for the absence: I've been terribly busy with personal and professional matters. @LorenzoBettini, I just gave you the Admin rights on the Pitclipse repository so that you can contribute freely. I wasn't aware of the upcoming issues with Travis CI and Bintray; could you create an issue on the repository so that we can discuss about the possible alternatives? 
Thanks, Emmanuel

**Comment by LorenzoBettini** [comment]
@hcoles thank you for the admin rights!
@echebbi no problem! I'll create issues where we can discuss the next step

**Comment by LorenzoBettini** [comment]
Dear @hcoles , following https://github.com/pitest/pitclipse/issues/122#issuecomment-827412993 , we would need someone with admin rights to create a new GitHub repository under the pitest organization for storing the p2 update site for pitclipse (me and @echebbi would also need admin rights on that new repository). The repository could be called `pitclipse-releases`. If possible, another repository, e.g., `pitclipse-snapshots` might be useful for releasing p2 update sites with snapshot or milestone releases.

Many thanks in advance

**Comment by hcoles** [comment]
You should both now have invites to the new repositories.

**Comment by LorenzoBettini** [comment]
Thank you so much @hcoles !
