### ISSUE TITLE
Please add some --quiet option or similar

### ISSUE THREAD

**Issue by Vampire** [hcoles/pitest#652]
Pitest is way too verbose by default for inclusion in a Gradle run for example.
It would be nice if it had some option to be quiet except for warnings and errors,
so that the Gradle plugin or a Gradle build script can set it up so that info logging is only shown if info level logging is enabled, and verbose if debug logging is enabled. (The latter is already possible with `verbose = logger.isDebugEnabled`).

Gradle builds for example should by default be very quiet except for warnings and errors, so that those are better seen and only show informational messages if info-level logging is enabled.

**Comment by zielint0** [comment]
Is there any chance to implement it?

**Comment by binkley** [comment]
I have a similar experience with the Maven plugin:

1. Researching the code base, the `Log` class _hard-codes_ the `INFO` level
2. I didn't find uses of the `setLevel` method except within this class, ie, no configuration call to it
3. Experimented with `-DPIT.level=WARNING` both for Maven's JVM, and the `<jvmArg>` configuration for the plugin: No effect

**Comment by hcoles** [comment]
#934 added a verbosity parameter which allows the amount of noise to be configured.
