### ISSUE TITLE
Found  0 tests when testing commons-collections

### ISSUE THREAD

**Issue by crabfishxy** [hcoles/pitest#694]
I'm new to Pitest. So I downloaded java's common-collections source code to have a try. And the version is 4.4. However, after I ran mutationCoverage, I found some classes have no coverage. For example, the `LRUMap` class:
![Screenshot_20191012_231104](https://user-images.githubusercontent.com/18566621/66710404-959afe80-ed45-11e9-8d5a-c445905063db.png)
And Pitest said found 0 tests. I'm not sure what went wrong. Here are the configuration.
```
      <plugin>
        <groupId>org.pitest</groupId>
        <artifactId>pitest-maven</artifactId>
        <version>1.4.10</version>
        <configuration>
          <targetClasses>
            <param>org.apache.commons.collections4.map.LRUMap*</param>
          </targetClasses>
          <targetTests>
            <param>org.apache.commons.collections4.map.LRUMapTest*</param>
          </targetTests>
        </configuration>
      </plugin>
```
I also found that all classes which found 0 tests imported `org.junit.framework.Test`. But I have no idea how to solve it.
The source codes and tests could be find below:
[LRUMap](https://github.com/apache/commons-collections/blob/master/src/main/java/org/apache/commons/collections4/map/LRUMap.java)
[LRUMapTest](https://github.com/apache/commons-collections/blob/master/src/test/java/org/apache/commons/collections4/map/LRUMapTest.java)
Thanks!

**Comment by crabfishxy** [comment]
OK, I found this problem is similar to https://github.com/hcoles/pitest/issues/172#issue-58249594.
After I delete the suite and succeeded found the tests running Pitest. But I still hope there is another way to solve this problem...

**Comment by Crissal1995** [comment]
Probably same problem found as #863

**Comment by Crissal1995** [comment]
@hcoles was the issue solved? If so, what is the PR related to this change?
bonus question, is this the same issue found in #863?
