### ISSUE TITLE
Question regarding Pitest configuration - threads

### ISSUE THREAD

**Issue by trance1st** [hcoles/pitest#701]
Hello, 
It is not clear for me how those threads are used:
- a thread runs all tests against one minion, another thread runs all tests against another minion and so on
- more threads run tests in parallel against one minion.
 
To rephrase: it is safe to use more threads if my tests are dependent? 

Many thanks, 
Bogdan

**Comment by rnveach** [comment]
> it is safe to use more threads if my tests are dependent?

Unless you mean *independent*, if 1 test relies on another test (which is dependent) then more than 1 thread isn't safe.

Dependency is just 1 requirement. IMO, your tests need to be completely thread safe to have more than 1 run at a time. For example, my project's tests rely on the actual file system and they are not thread safe because 1 test could modify the same file another test is reading from for the results of a test.

**Comment by hcoles** [comment]
If tests are dependent on each other then they are not suitable for mutation testing, even with a single thread, as they will have run order dependencies.

**Comment by trance1st** [comment]
Thanks for replies. 

> If tests are dependent on each other then they are not suitable for mutation testing
Sorry, I wasn't clear enough: tests are independent meaning they can ran in any order but cannot be ran in parallel because they are not thread safe. 

If the pitest threads are used as I first described, then if we have tests that are not thread safe it is still safe to configure pitest with more than 1 thread.
> a thread runs all tests one by one against one minion, another thread runs all tests against another minion and so on

Shortly: if tests can be ran in any order but cannot be ran in parallel it is safe to increase the threads for pitest?

**Comment by hcoles** [comment]
Pitest create a new minion for each thread, and a new jvm for each minion.

So, if your tests really can be run in any order, then pitest can safely run them in parallel (assuming they are not reading/writing state external from the jvm).

However, in most cases tests that are not thread safe cannot be run in any order. If your code contains mutable static state (e.g in singletons), then they very likely have hidden test order dependencies.

**Comment by trance1st** [comment]
@hcoles 
Many thanks. It is clear now. 
I find this info very useful and I suggest to add it to the official doc if you also think so.

> Pitest create a new minion for each thread, and a new jvm for each minion.
So, if your tests really can be run in any order, then pitest can safely run them in parallel (assuming they are not reading/writing state external from the jvm).

>
