### ISSUE TITLE
How to Run Security Mutators by using Maven

### ISSUE THREAD

**Issue by arif420566** [hcoles/pitest#708]
Using configuration in maven pom.xml and using mutationEngine gregor i did able to run the gregor mutators but unable to run the security mutators. Can anyone please assist me how to run the security mutators using maven?

Thank you,

**Comment by hcoles** [comment]
What do you mean by "the security mutators"?

**Comment by arif420566** [comment]
there are 15 new mutators in the security folder url: https://github.com/Iotho/pitest-sec/tree/master/pitest/src/main/java/org/pitest/mutationtest/engine/gregor/mutators/experimental/security, i would like to use them in my java test case using maven.

**Comment by hcoles** [comment]
That is someone's fork of pitest. You will need to ask the author of that repo how it should be used.

**Comment by arif420566** [comment]
ow, sorry for posting here.
Thank you for your answer.
