### ISSUE TITLE
[report aggregation] Wrong coverage when reports are merged

### ISSUE THREAD

**Issue by aurelien-baudet** [hcoles/pitest#718]
Expected acceptance test
====================

**GIVEN**
  - A multi-maven module with this structure:
    ```
    parent
    ├ submodule-a
    │  └ src/main/java
    │     └ foo.ClassA
    │  └ src/test/java
    │     └ foo.ClassATest
    ├ submodule-b
    │  └ src/main/java
    │     └ foo.ClassB
    │  └ src/test/java
    │     └ foo.ClassBTest
    └ reporting
    ```
  - The `reporting` submodule generates aggregated report using `report-aggregate` goal
    ```xml
    <plugins>
	   <plugin>
		<groupId>org.pitest</groupId>
		<artifactId>pitest-maven</artifactId>
		<executions>
			<execution>
				<id>merge-pitest-reports</id>
				<phase>site</phase>
				<goals>
					<goal>report-aggregate</goal>
				</goals>
			</execution>
		</executions>
	   </plugin>
    </plugins>
    ```
  - The `reporting` module has dependencies to `submodule-a` end `submodule-b`:
    ```xml
    <dependencies>
		<dependency>
			<groupId>com.foo</groupId>
			<artifactId>submodule-a</artifactId>
		</dependency>
		<dependency>
			<groupId>com.foo</groupId>
			<artifactId>submodule-b</artifactId>
		</dependency>
    </dependencies>
    ```
  - The test `foo.ClassATest` kills the mutants of `ClassA`
  - The test `foo.ClassBTest` partially kills the mutants of `ClassA`
  - The test `foo.ClassBTest` kills all the mutants of `ClassB`

**WHEN**
 -  I run mutation testing and report aggregation

**THEN**
  -  The report indicates 100% coverage as every mutant has been killed by at least one test defined in any submodule
  - The detailed report for `ClassA` indicates 100% coverage

---

The current behavior indicates `NO_COVERAGE` with red line on some lines when reports are aggregated.

Example
=======

Submodule that unit test the `StringToArrayConverter` class:
![image](https://user-images.githubusercontent.com/645363/72294568-3ebc0280-366f-11ea-99fb-3dc0b7058806.png)

Submodule that doesn't test at all the `StringToArrayConverter` class but has dependency on first module:
![image](https://user-images.githubusercontent.com/645363/72294590-4e3b4b80-366f-11ea-8098-bfe245ff6040.png)

Submodule that has integration tests on both submodules and that indirectly partially tests `StringToArrayConverter` class:
![image](https://user-images.githubusercontent.com/645363/72294646-67dc9300-366f-11ea-8f61-816dd4b75876.png)

**Aggregated report:**
![image](https://user-images.githubusercontent.com/645363/72294741-98bcc800-366f-11ea-8f03-cabd3f5ba2ee.png)

It is not 100% coverage on `StringToArrayConverter` class.

---

Additional information:
- using pitmp-maven-plugin 1.3.7 to run mutation tests 
- using pitest-maven 1.4.10 to aggregate reports
- using descartes mutation engine

**Comment by aurelien-baudet** [comment]
I think I found the issue.

`MutationHtmlReportListener` annotates each line of code with associated mutations (by creating a `Line` instance). The associated mutations are sorted using `ResultComparator` so `KILLED` status is at the end of the sorted list. Later when the string template is parsed, a style is applied through `LineStyle` class associated to the `Line`. The `getMutation` method class `this.line.detectionStatus()`  that contains the following code:
```java
  public Optional<DetectionStatus> detectionStatus() {
    if (this.mutations.isEmpty()) {
      return Optional.empty();
    }
    return Optional.ofNullable(this.mutations.get(0).getStatus());
  }
```
If there are mutations, only the first one is used so `KILLED` status is not used since there is another mutation with another status.

Here is an example of mutations on the same line generated by several tests in several projects:

- SURVIVED                     | generated by test9 of project C
- NO_COVERAGE           | generated by test20 of project C
- SURVIVED                     | generated by test4 of project B
- TIMED_OUT                  | generated by test27 of project A
- KILLED                          | generated by test1 of project B
- KILLED                          | generated by test11 of project A

Currently,  `detectionStatus()` returns either `SURVIVED` or `NO_COVERAGE` (depends on the sorting result as both have same rank set to 0).

However, across the whole project there are tests that ensure that the mutation can't survive. So the `detectionStatus()` should return `KILLED`.

That's why I think the resolution of `detectionStatus()` should not take only the first mutation. As a quick fix it could take the last mutation of the list. However, the sorted list could be something like:

- SURVIVED                     | generated by test12
- NO_COVERAGE           | generated by test20
- SURVIVED                     | generated by test4
- MEMORY_ERROR        | generated by test31
- NOT_STARTED             | generated by test2
- TIMED_OUT                  | generated by test27
- NON_VIABLE                | generated by test1

Using the last element in the list will return `NON_VIABLE` but it is not really relevant to the developer that wants to improve its test suite. The useful information is `SURVIVED` and `NO_COVERAGE` because in this case the line is never covered with or without analysis error.

I can fix this but I need to know what is the expected behavior.

**Comment by yelkolk** [comment]
Hello, 

any news about this? We have come across it in some of my company's projects.

Thank you.

**Comment by hcoles** [comment]
@yelkolk Pitest's own maven plugin does not support mutating classes from different modules. It looks like this issue should have been raised against [pitmp-maven-plugin](https://github.com/STAMP-project/pitmp-maven-plugin) which the OP is/was using.
