### ISSUE TITLE
intermittent coverage holes

### ISSUE THREAD

**Issue by magwas** [hcoles/pitest#742]
In our project we see false negatives which go away when we rebuild the project.
See https://app.shippable.com/github/kode-konveyor/tidy-up/dashboard/history
#344 is the expected build without coverage problems.
#343 have one, and #341 have three mutation coverage holes reported.

What should we do to make our builds stable?

**Comment by hcoles** [comment]
The result should always be the same unless there is some non determinism in your build (such as use of Random, concurrent code, or execution flows that rely on some external factor), or there is a bug in pitest.

The 1.5.0 release contained a fix for how test coverage was gathered under junit 5. Coverage of code that ran before the first test in the suite was not being recorded. Upgrading may stabilise the build, but if the results are non deterministic there is still an underlying issue to investigate.

**Comment by hcoles** [comment]
@magwas Did upgrading to 1.5.0 solve the issue?

**Comment by magwas** [comment]
Yes, it seem so. However we had another issue.

Long  a;
if (a <=0) {
...
}
we tested it with a=0, a=-1 and a=1, and still got a zombie.
Changing it to a < 1 resolved the problem.
