### ISSUE TITLE
Pitest not filtering try-with-resources correctly in Java 11

### ISSUE THREAD

**Issue by johnsterken** [hcoles/pitest#766]
## Summary

Pitest is trying to mutate bytecode used for closing resources when using the try-with-resources in Java 11

Expected: No mutations on the generated parts of the bytecode, this behaviour works correctly in Java 8
Actual: Mutations happening on the generated parts in the bytecode used for closing the resources that are used in the try block

## Steps to reproduce

* [Check out the example project](https://github.com/johnsterken/pitest-java11-try-with-resources)
* Run `mvn clean test pitest:mutationCoverage`
* Look at the pitest report, it shows mutations on the try block

## Other info

Probably this is related to  #689 

### Tested with OpenJDK

**Java 11**
```
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-2ubuntu218.04)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-2ubuntu218.04, mixed mode, sharing)
```

**Java 8**
```
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-8u252-b09-1~18.04-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)

```

I also checked out the pitest repository locally. When I create a test in `TryWithResourcesFilterTest` with the Java 11 bytecode from my local JDK I don't see any mutation being filtered. When I run the same test on a Java 8 class file it does filter out mutations

[java8_pit_report.zip](https://github.com/hcoles/pitest/files/4626983/java8_pit_report.zip)
[java11_pit_report.zip](https://github.com/hcoles/pitest/files/4626990/java11_pit_report.zip)

**Comment by ketan2505** [comment]
I am using pitest results for quality checks. The same problem occured with me. I had to disable pitest from my project. I would like to see this working with Java 11 as well.

**Comment by TomerFi** [comment]
Same here.
Working with Java11, using try-with-resources, I always end up with a bunch of surviving mutants.
e.g. a mutant removing the close() statement inside the auto-generated finally block.

**Comment by hcoles** [comment]
Sorry for the delay fixing this folks, it is very annoying. Should have something out early next week.

**Comment by hcoles** [comment]
This has gone a little easier than I'd exepected, so I'll push a release out later today.

New filtering catches the issues in @johnsterken 's example, plus some sample real world projects. I expect there will be further issues with more complex examples, but current code seems to give 90% of the benefit.

**Comment by johnsterken** [comment]
Looking good! I just tried your 1.6.3 version in the project that triggered this issue. It's working like a charm. Thanks @hcoles!
