### ISSUE TITLE
mutationCoverage for a @SpringBootTest test class

### ISSUE THREAD

**Issue by vladflore** [hcoles/pitest#781]
Hi,

is it possible to run the **mutationCoverage goal** for a **@SpringBootTest** annotated class? I am currently trying to achieve that and I get the error below:

`Failed to execute goal org.pitest:pitest-maven:1.5.2:mutationCoverage (default) on project shopping-list-backend: Execution default of goal org.pitest:pitest-maven:1.5.2:mutationCoverage failed: No mutations found. This probably means there is an issue with either the supplied classpath or filters.`

The @SpringBootTest test class is the default one generated when created a new spring boot project.

Trying to run mutation coverage on other "normal" (junit) test classes, works as expected.

What am I missing here?

Thanks,
Vlad

**Comment by hcoles** [comment]
The error you are receiving means that pitest has been unable to generate any mutations, this suggests the issue is somewhere in your setup, rather than an issue with an annotated test.

If you can post a minimal project that reproduces the issue I can take a look.

**Comment by vladflore** [comment]
Hi Henry,

thanks for your interest.

Here is the project of which I was talking about earlier:
https://github.com/vladflore/shopping-list-app/blob/master/backend/pom.xml

Running a `mvn clean verify` fails because of the above mentioned error. I am not quite sure what is missing from my setup.

Vlad

**Comment by hcoles** [comment]
Ok, the configuration is fine. The issue is that there is no code/logic for pitest to mutate, just some spring magic and scaffolding.

Not finding any mutations is treated as an error as 99.9% of the time this happens because something has been incorrectly configured. You've hit the 0.1% case where it's legitimate.

If you add some code with logic the error will go away.

**Comment by vladflore** [comment]
Lucky me :)

Thanks for the help, much appreciated!

Just a thought, maybe it could be possible to change the error message or to let it pass with an appropriate warning or so, it might be more helpful.

Also not sure if the documentation is mentioning this 0.1% case.

Thanks again!
Vlad

**Comment by hcoles** [comment]
The error we actually want is a "no matching code found to mutate" error. The "no mutations found" one is close to that, but as we've just seen not the same thing. Would have to dig through the code, but I suspect "no matching code found to mutate" is not easy to detect,

**Comment by vladflore** [comment]
ok, cool! If it does not worth it / is too difficult to isolate the case, I am fine with how it is right now :)

Vlad

**Comment by nithishbattina** [comment]
<plugin>
                <groupId>org.pitest</groupId>
                <artifactId>pitest-maven</artifactId>
                <version>1.9.11</version>
                 <executions>
                     <execution>
                         <goals>
                             <goal>mutationCoverage</goal>
                         </goals>
                     </execution>
                 </executions>

                <dependencies>
                   
                    <dependency>
                        <groupId>org.pitest</groupId>
                        <artifactId>pitest-junit5-plugin</artifactId>
                        <version>1.2.1</version>
                    </dependency>
                </dependencies>


                <configuration>
                    <targetClasses>
                        <param>com.dbs.iprs.portfolio.services.*</param>
                    </targetClasses>
                    <targetTests>
                        <param>com.dbs.iprs.portfolio.services.*Test</param>
                    </targetTests>
                </configuration>
            </plugin>
            getting this
            pitest-maven:1.9.11:mutationCoverage (default-cli) @ iprs-portfolio-service ---
[INFO] Skipping project because:
[INFO]   - Project has no tests, it is empty.


In my java springboot project it is working good but in my kotlin springboot project i am getting this issue

**Comment by nithishbattina** [comment]
Hi  Henry Coles i have created an sample project where my mutations showing
--- pitest:1.15.3:mutationCoverage (default-cli) @ kotlin-project ---
[INFO] Skipping project because:
[INFO]   - Project has either no tests or no production code. i am
attaching project,can you please help as i have added more dependencies as
my original project consists
 kotlin-project.zip
<https://drive.google.com/file/d/1LW2mX-JraHWmxteue7NUs6xPh9waz3QK/view?usp=drive_web>
