### ISSUE TITLE
Feature request: ignore by line number

### ISSUE THREAD

**Issue by theangrydev** [hcoles/pitest#794]
We have `excludedMethods` and `excludedClasses`  but no `excludedLines` which would be really helpful to exclude specific lines of code. This comes up e.g. with "changed conditional boundary" mutations that survive e.g. when the x > 0 and x >= 0 behaviour are supposed to be the same. 

Being able to exclude these on a line by line basis might be cleaner than the current workaround of wrapping the offending line in a method and excluding the method.

Currently I am doing this: `<excludedMethod>excludedFromPitest*</excludedMethod>` and using a naming convention to exclude.

The problem with that is that I have to change my prod code (cosmetically at least) just to satisfy pitest.

**Comment by tdrury** [comment]
You can exclude a line from Sonar analysis via a `//NOSONAR` comment. How about something like `//NOPIT` on a line to exclude it? Or to exclude a specific mutator `//NOPIT-MATH_MUTATOR` ?

**Comment by StefanPenndorf** [comment]
Pitest does not parse any source code. Mutations will be applied to byte code, only. Thus the comment approach won't work, in my opinion.

What might work is an approach using annotations with byte code retention. As there could be many places that would need to be marked for exclusion, personally I would prefer the annotation approach over the POM/XML declaration approach.

If you're using SONAR and there is an equivalent mutant surviving for `x > 0` or `x >= 0` I'd rather use SONAR's built in "mark as false positive" feature documenting that your manual analysis has proved that this is an equivalent mutation.

**Comment by hcoles** [comment]
This is now possible using the arcmutate extensions

https://docs.arcmutate.com/docs/exclusions.html
