### ISSUE TITLE
Would PIT modify the line number when insert a mutant?

### ISSUE THREAD

**Issue by lllwwwbbb** [hcoles/pitest#795]
I use PIT to insert mutants into a program then execute tests to collect the *coverage* information, so I expect the line number of each statements stay the same with the origin program. Would PIT modify the line number when insert a mutant?

**Comment by hcoles** [comment]
No, PIT does not modify line numbers.

**Comment by lllwwwbbb** [comment]
@hcoles Thank you so much.
