### ISSUE TITLE
mutationCoverage not working with @Testcontainers - example attached

### ISSUE THREAD

**Issue by jaguado-arima** [hcoles/pitest#827]
Hi!
I have implemented my integration tests using **@Testcontainers**. They pass successfully but when running _mutationCoverage_ they don't.

When running _mutationCoverage_, a container is started, the context is loaded (setting up datasource properties) and tests are successfully run. Afterwards in the "Gathering coverage for test Description" phase another container is started but the datasource configuration is already loaded with the previous container info.... so I keep having an error with database connection: "HikariPool-2 - Connection is not available"

- The repository with the source code: https://github.com/jaguado-arima/pitTestcontainers
- The result of the mutationCoverage execution: https://github.com/jaguado-arima/pitTestcontainers/runs/1473293702?check_suite_focus=true

I don't manage to understand what is happening. 
Is it that Pit is not compatible with @Testcontainers? Am I doing something wrong?
Any ideas?

Thanks in advance!

**Comment by jaguado-arima** [comment]
Hi! I have made it work!
I have added @DirtiesContext to the test class (https://github.com/jaguado-arima/pitTestcontainers/blob/master/src/test/java/com/example/pitTestcontainers/pets/PetServiceWorkingWithPitestTest.java) this way the database properties are set every time a container is created.

Nevertheless when using the singleton container approach there is no need for "tricks". So as using singleton container would be best for many cases, I think that this is what I will use (https://github.com/jaguado-arima/pitTestcontainers/blob/master/src/test/java/com/example/pitTestcontainers/pets/PetService1SingletonContainerWorkingWithPitestTest.java)

Thanks!

**Comment by hcoles** [comment]
Hi @jaguado-arima, thanks for the update. Sorry I wasn't able to provide any help with the issue.

I'm glad it is working for you, but a word of caution. If you are using tests that hit a containerised database you are likely to hit further issues. As the database instance will persist between indivual test runs, the mutation results may not be accurate. If one mutation results in data in the database being put into an "impossible" state, this may result in tests failing for subsequent mutaitons. This is one of the reasons (along with performance) that mutation testing with integration tests is not usually reccomended.

**Comment by jaguado-arima** [comment]
Hi! Thank you very much for your reply.

But with the tests having @Transactional annotation all changes will be rolled back and that problem will not exist? (Am I wrong?)
About the performance... you are right! But I find it useful to use mutation, at least locally, when I am developing.

Thank you again! Have a nice week.

**Comment by hcoles** [comment]
Yes, if you have something in place that robustly rolls back data between tests you should be fine.

**Comment by jaguado-arima** [comment]
Thank you very much!

**Comment by StefanPenndorf** [comment]
I've already answered on the mailing list and used my findings to create https://github.com/spring-projects/spring-framework/issues/26196 which contains detailed results (for users only reading github).

**Comment by jaguado-arima** [comment]
Yeah! Thank you!:ok_hand:
