### ISSUE TITLE
NoClassDefFoundError with pitest 1.5.2 and jmockit 1.49

### ISSUE THREAD

**Issue by eriknellessen** [hcoles/pitest#838]
When running `mvn org.pitest:pitest-maven:mutationCoverage`, I get the following error message:

> 10:14:43 PIT >> INFO : MINION : 10:14:43 PIT >> SEVERE : Description [testClass=de.nellessen.example.ExampleCalculatorTest, name=[engine:junit-jupiter]/[class:de.nellessen.example.ExampleCalculatorTest]/[method:calculateExpectedValue()]]
> java.lang.NoClassDefFoundError: Could not initiali
> 10:14:43 PIT >> INFO : MINION : ze class de.nellessen.example.ExampleCalculatorTest$1
>         at de.nellessen.example.ExampleCalculatorTest.calculateExpectedValue(ExampleCalculatorTest.java:18)
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at java.base/jdk.
> 10:14:43 PIT >> INFO : MINION : internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 
> 10:14:43 PIT >> INFO : MINION : at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:532)
>         at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:115)
>         at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$in
> 10:14:43 PIT >> INFO : MINION : vokeTestMethod$6(TestMethodTestDescriptor.java:170)
>         at org.junit.jupiter.engine.execution.ThrowableCollector.execute(ThrowableCollector.java:40)
>         at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.jav
> 10:14:43 PIT >> INFO : MINION : a:166)
>         at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:113)
>         at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:58)
>         at org.junit.platform.engine.supp
> 10:14:43 PIT >> INFO : MINION : ort.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$3(HierarchicalTestExecutor.java:113)
>         at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
>         at org.junit.platform.eng
> 10:14:43 PIT >> INFO : MINION : ine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.executeRecursively(HierarchicalTestExecutor.java:108)
>         at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.execute(HierarchicalTestExecutor.java:79)
>         at org.
> 10:14:43 PIT >> INFO : MINION : junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$2(HierarchicalTestExecutor.java:121)
>         at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
>         at java.base/java.util.st
> 10:14:43 PIT >> INFO : MINION : ream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
>         at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
>         at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
>         at java.base/java.util.str
> 10:14:43 PIT >> INFO : MINION : eam.AbstractPipeline.copyInto(AbstractPipeline.java:484)
>         at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
>         at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
>         at java.base/ja
> 10:14:43 PIT >> INFO : MINION : va.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
>         at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
>         at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
>         at o
> 10:14:43 PIT >> INFO : MINION : rg.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$3(HierarchicalTestExecutor.java:121)
>         at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:6
> 10:14:43 PIT >> INFO : MINION : 6)
>         at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.executeRecursively(HierarchicalTestExecutor.java:108)
>         at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.execute(HierarchicalT
> 10:14:43 PIT >> INFO : MINION : estExecutor.java:79)
>         at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$2(HierarchicalTestExecutor.java:121)
>         at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:18
> 10:14:43 PIT >> INFO : MINION : 3)
>         at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
>         at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
>         at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801
> 10:14:43 PIT >> INFO : MINION : )
>         at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
>         at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
>         at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachO
> 10:14:43 PIT >> INFO : MINION : ps.java:150)
>         at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
>         at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
>         at java.base/java.util.stream.ReferencePipeline.forEach(Refe
> 10:14:43 PIT >> INFO : MINION : rencePipeline.java:497)
>         at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$3(HierarchicalTestExecutor.java:121)
>         at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSaf
> 10:14:43 PIT >> INFO : MINION : ely(SingleTestExecutor.java:66)
>         at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.executeRecursively(HierarchicalTestExecutor.java:108)
>         at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeE
> 10:14:43 PIT >> INFO : MINION : xecutor.execute(HierarchicalTestExecutor.java:79)
>         at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:55)
>         at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(Hierar
> 10:14:43 PIT >> INFO : MINION : chicalTestEngine.java:43)
>         at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:170)
>         at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:154)
>         at org.junit.platform.launcher.core.DefaultLauncher.exe
> 10:14:43 PIT >> INFO : MINION : cute(DefaultLauncher.java:90)
>         at org.pitest.junit5.JUnit5TestUnit.execute(JUnit5TestUnit.java:88)
>         at org.pitest.coverage.execute.CoverageDecorator.execute(CoverageDecorator.java:49)
>         at org.pitest.testapi.execute.containers.UnContainer.execute(UnContaine
> 10:14:43 PIT >> INFO : MINION : r.java:31)
>         at org.pitest.testapi.execute.Pitest.executeTests(Pitest.java:57)
>         at org.pitest.testapi.execute.Pitest.run(Pitest.java:48)
>         at org.pitest.coverage.execute.CoverageWorker.run(CoverageWorker.java:49)
>         at org.pitest.coverage.execute.CoverageMinio
> 10:14:43 PIT >> INFO : MINION : n.main(CoverageMinion.java:90)
> 
> 10:14:43 PIT >> SEVERE : Description [testClass=de.nellessen.example.ExampleCalculatorTest, name=[engine:junit-jupiter]/[class:de.nellessen.example.ExampleCalculatorTest]/[method:calculateExpectedValue()]] did not pass without mutation.

I created a project with an MWE reproducing the error [here](https://github.com/eriknellessen/jmockit-pitest-mwe).

When I comment out the `Expectations()` call in the code, everything runs fine.

**Comment by gmshake** [comment]
Repeat and it looks good with JDK 8 

```sh
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.251-b08, mixed mode)
```

**Comment by eriknellessen** [comment]
@gmshake Thanks, I could verify that. I ran the `mvn org.pitest:pitest-maven:mutationCoverage` step with Java 8 and it worked.

So am I supposed to start pitest using JDK 8? And will this work with projects that generally use JDK 11?

**Comment by gmshake** [comment]
I does not have JDK 11, and thus have no idea whether the issue is caused by JDK 11 or jmockit. Need more investment :)

**Comment by gmshake** [comment]
@eriknellessen Sorry for my mistake. I repeated with `mvn verify` and did not pass `org.pitest:pitest-maven:mutationCoverage` and made the wrong conclude.

I managed to repeat this issue with Oracle JDK 1.8.0_251 and OpenJDK 11.0.7 .

> I could verify that. I ran the mvn org.pitest:pitest-maven:mutationCoverage step with Java 8 and it worked.
So am I supposed to start pitest using JDK 8? And will this work with projects that generally use JDK 11?

Seems this issue shall be addressed if you insist on employing jmockit. I'm not familiar with jmockit, but in my projects junit-5 and mockito work simultaneously.

**Comment by gmshake** [comment]
@eriknellessen  Proposed fix, add jvmArgs config to keep align with that of `maven-surefire-plugin`.
```xml
<groupId>org.pitest</groupId>
<artifactId>pitest-maven</artifactId>
<version>1.5.2</version>
<configuration>
    <jvmArgs>
        <jvmArg>-javaagent:${settings.localRepository}/org/jmockit/jmockit/1.49/jmockit-1.49.jar</jvmArg>
    </jvmArgs>
</configuration>
```

Tested with Oracle JDK 1.8.0_251 and OpenJDK 11.0.7 .
See PR https://github.com/eriknellessen/jmockit-pitest-mwe/pull/1

**Comment by eriknellessen** [comment]
@gmshake Ok, this has solved the issue for me. Thank you!

Is this information already present in the documentation? If not, I think it should be added.

Since the issue is solved, I will close it.

**Comment by gmshake** [comment]
> @gmshake Ok, this has solved the issue for me. Thank you!
> 
> Is this information already present in the documentation? If not, I think it should be added.
> 
> Since the issue is solved, I will close it.

CC @hcoles
