### ISSUE TITLE
Pitest fails with the error Index: 64, Size: 13 

### ISSUE THREAD

**Issue by SoodehAtefi** [hcoles/pitest#854]
I have run Pitest on the Corenlp framework and use Evosuite generated tests as the projects' tests but the Pitest fail on the following error:
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:35 min
[INFO] Finished at: 2021-01-11T19:52:16-06:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.pitest:pitest-maven:1.5.2:mutationCoverage (default-cli) on project stanford-corenlp: Execution default-cli of goal org.pitest:pitest-maven:1.5.2:mutationCoverage failed: Index: 64, Size: 13 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

**Comment by StefanPenndorf** [comment]
Hi @Spourang 

unfortunately it's almost impossible to reproduce and fix this issue with the information provided. Could you provide a minmal example project reproducing the issue? Could you run maven with the `-e` switch and provide the full stacktrace / log output?

**Comment by hcoles** [comment]
Closing as insufficient information supplied.
