### ISSUE TITLE
Jacoco noclassdef found error

### ISSUE THREAD

**Issue by rishabhgpt** [hcoles/pitest#864]
Running pitest 1.6.3 maven plugin.

`mvn -DwithHistory org.pitest:pitest-maven:mutationCoverage`

Getting this error in logs while running pitest :

PIT >> INFO : MINION : java.lang.NoClassDefFoundError: org/jacoco/agent/rt/internal_6da5971/Offline

And at the end pitest reports all tests did not get green signal and bails out.
Locally tests run fine.

jdk : 8
jacoco version : 0.7.8
pitest version : 1.6.3
spring boot starter : 2.0.0.RELEASE

**Comment by rishabhgpt** [comment]
Also what does this error means ?

```
 MINION : ScriptEngineManager providers.next(): javax.script.ScriptEngineFactory: Provider org.codehaus.groovy.jsr223.GroovyScriptEngineFactory could not be instantiated
6:35:36 PM PIT >> INFO : MINION : 6:35
```

**Comment by StefanPenndorf** [comment]
Hi @rishabhgpt 

You need to include JaCoCo Agent as a dependency, see https://stackoverflow.com/questions/40067455/jacoco-caused-by-java-lang-classnotfoundexception-org-jacoco-agent-rt-inter

The `ScriptEngineManager` class doesn't belong to pitest and might be called by org.apache.maven.scm:maven-scm-provider-integrity. If this is a problem and you're not using Integrity SCM you might try to exclude this dependency and see if the message goes away. I don't think this will cause any trouble but I might be wrong.

How are you running your tests "locally"? Could you provide a minimal example project to reproduce the problem?
