### ISSUE TITLE
Conflict with spring-boot-dependencies 2.4.3

### ISSUE THREAD

**Issue by cjt0226** [hcoles/pitest#867]
Found Error during run "mvn pitest:mutationCoverage",The reason is that I introduced spring-boot-dependencies 2.4.3. It's works fine on 2.4.2.

[ERROR] 
[ERROR] Please copy and paste the information and the complete stacktrace below when reporting an issue
[ERROR] VM : OpenJDK 64-Bit Server VM
[ERROR] Vendor : AdoptOpenJDK
[ERROR] Version : 25.265-b01
[ERROR] Uptime : 2929
[ERROR] Input -> 
[ERROR]  1 : -Dclassworlds.conf=/Users/frank.chen/Library/apache-maven-3.6.0/bin/m2.conf
[ERROR]  2 : -Dmaven.home=/Users/frank.chen/Library/apache-maven-3.6.0
[ERROR]  3 : -Dlibrary.jansi.path=/Users/frank.chen/Library/apache-maven-3.6.0/lib/jansi-native
[ERROR]  4 : -Dmaven.multiModuleProjectDirectory=/Users/frank.chen/Documents/Project/homecreditcfc/cucumber-common-library
[ERROR] BootClassPathSupported : true

            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>2.4.3</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>

**Comment by cjt0226** [comment]
[ERROR] 
[ERROR] Please copy and paste the information and the complete stacktrace below when reporting an issue
[ERROR] VM : OpenJDK 64-Bit Server VM
[ERROR] Vendor : AdoptOpenJDK
[ERROR] Version : 25.265-b01
[ERROR] Uptime : 2929
[ERROR] Input -> 
[ERROR]  1 : -Dclassworlds.conf=/Users/frank.chen/Library/apache-maven-3.6.0/bin/m2.conf
[ERROR]  2 : -Dmaven.home=/Users/frank.chen/Library/apache-maven-3.6.0
[ERROR]  3 : -Dlibrary.jansi.path=/Users/frank.chen/Library/apache-maven-3.6.0/lib/jansi-native
[ERROR]  4 : -Dmaven.multiModuleProjectDirectory=/Users/frank.chen/Documents/Project/homecreditcfc/cucumber-common-library
[ERROR] BootClassPathSupported : true




            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>2.4.3</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>

**Comment by hcoles** [comment]
It is not clear what the error you are reporting here is, however the earlier edit of your issue included this

`zip file is empty (/Users/frank.chen/.m2/repository/io/projectreactor/reactor-core/3.4.3/reactor-core-3.4.3.jar`

Which suggests it may be an issue with your local cache of the reactor-core dependency. You could try wiping out your .m2 cache and see if that fixes the problem.

If it does not please create a minimal project that reproduces the issue (working with 2.4.2, failing with 2.4.3).

**Comment by cjt0226** [comment]
After delete reactor-core-3.4.3 in m2 repository, the issue was fixed. Thanks!
