### ISSUE TITLE
Add support for Java 16

### ISSUE THREAD

**Issue by krzyk** [hcoles/pitest#868]
Java 16 is due to be released next week so it would be goot for pitest to be ready.
Right now it fails with `Unsupported class file major version 60`

**Comment by hcoles** [comment]
Thanks. This is most likely already fixed in master where the ASM dependency has been bumped to 9.1. I'll see if I can get some actual testing done against 16, but will release either way this weekend.

**Comment by hcoles** [comment]
@krzyk Release 1.6.4 should sync to maven central in the next hour or so. The pitest test suite passes with 16-ea, but not tried it on any real code.

If it works for you, please report back in this issue.

**Comment by C-Otto** [comment]
Works for me (1.6.5, Gradle, Java 16, JUnit 5 with junit5PluginVersion = '0.14'). Thank you!

**Comment by prdoyle** [comment]
Do you have an ETA on pushing this to plugins.gradle.org? That version is still 1.6.0 so I can't use Java 16 with Gradle.

**Comment by szpak** [comment]
@prdoyle You don't need to wait. As mentioned in [README](https://github.com/szpak/gradle-pitest-plugin/#plugin-configuration), you can use (almost) any PIT version that is available. Just set `pitest.pitestVersion`:

```
pitest {
    ... //other configuration
    pitestVersion = '1.6.5'
}
```

**Comment by prdoyle** [comment]
Excellent, thanks for the tip!
