### ISSUE TITLE
Mutation tests showing wrong results when using AssertJ recursive comparison

### ISSUE THREAD

**Issue by acffagundes** [hcoles/pitest#872]
Hello,

I am checking if it is possible to use pitest with the application I work with. I setup everything and was checking the results and I have found some classes with an interesting result. I have a class with 95% coverage (140/148) and 4% mutation coverage (2/49). I got intrigued with the result and open the unit test so understand why the results were that bad. 
I didn't find anything wrong with the unit test and I created tests reproducing some of the mutations and the test failed, so the mutation should have been killed. 
In the unit test the fields are compared recursively using org.assertj.core.api.AbstractObjectAssert.isEqualToComparingFieldByFieldRecursively(Object) method.

`assertThat(resultOjb).isNotNull().isEqualToComparingFieldByFieldRecursively(expectedObj);`

If i replace the recursive comparison by a field by field comparison the mutation coverage increases.
```
assertThat(resultObj.field1()).isEqualTo(expectedObj.field1());
assertThat(resultObj.field2()).isEqualTo(expectedObj.field2());
....
```
I have the impression that pitest cannot handle the recursive comparison. I didn't find any related issue on GitHub or Google Groups. I would like to know if someone else had issues with recursive comparison and how to get correct mutation coverage for such cases.

Regards

Ana

**Comment by hcoles** [comment]
Could you create a minimal project that re-produces this issue? There is no obvious reason why the assertion would behave differently when run via pitest.

**Comment by acffagundes** [comment]
Henry,

I have created a sample project as you asked. 
https://github.com/acffagundes/mutation-test-sample

There is one package for recursive and non recursive comparison in the unit tests. 
![image](https://user-images.githubusercontent.com/17880047/110986078-83275900-836d-11eb-9edd-999f4888c28f.png)

Comparing both result you can see that there is a difference. When I open the recursive result the DTO classes have 0 mutation coverage.
![image](https://user-images.githubusercontent.com/17880047/110986179-a05c2780-836d-11eb-9ffe-80f619abf98b.png)

I will be grateful if you help me to understand why the mutation coverage doesn't work properly with the recursive comparison.

Thanks in advance

**Comment by hcoles** [comment]
Mutation coverage is working as expected and is revealing that the reflection based assertion is not able to detect the mutation.

The difference between the recursive and non recursive assertions that you've written is that the non recursive ones are also checking that the value the getters return is not null, it is this check that is killing the mutants.

If you just check that the dto getters return the same value then then pitest changes the getter to

```java
public String getSomething() {
  return null;
}
```

Then `a.getSomething() == b.getSomething()` will still be true.

If you remove the `isNotNull` checks from the non recursive test they will produce similar results to the recursive ones.

If you upgrade pitest to 1.6.4 it will use the new default mutators. These produce more stable mutations of the form

```java
public String getSomething() {
  return "";
}
```

which neither of your tests will detect.

**Comment by acffagundes** [comment]
I got your point, I have made several tests to understand better how the mutations work. 
What understand is that doesn't matter if use reflection or not, the only way to kill the that mutation is by asserting that is not null or empty. I wrote a custom recursive method using reflection and adding a check for null or empty and it does kill all the mutations. However in the real application there are objects that might expect some fields to be null.
So indeed pitest works exactly as you described and now I need to find a good balance in the configuration of the mutators to improve the analysis and maybe adjust some unit tests.
Thank you for your explanations.

**Comment by acffagundes** [comment]
I have made more tests and studied the behaviour of the mutations. The conclusion I have is that my unit tests have a good coverage despite mutation coverage being low. I have compared 3 cases:

**Case 1: Actual and expected are instances of the same object**
com.package1.PersonDto actual;
com.package1.PersonDto expected;
assertEquals(expected.getFirstName(), actual.getFirstName());  ==  -->  mutations survive

**Case 2: Actual and expected are instances of different objects **
com.package1.PersonDto actual;
com.package2.PersonDto expectedDiffObj;
assertEquals(expectedDiffObj.getFirstName(), actual.getFirstName());--> mutations killed

**Case 3: Expected is a constant**
com.package1.PersonDto actual;
static final String FIRST_NAME = "FIRST";
assertEquals(FIRST_NAME, actual.getFirstName()); --> mutations killed

By comparing and debugging the 3 cases above I realised that for case 1 the mutation is changing the byte code for both actual and expected and by changing the expected it makes the test not reliable. When comparing instances of the same object pitest was not effective in my tests.

**Comment by hcoles** [comment]
I'm not sure what you mean by "not effective", it is correctly highlighting that your tests would not fail if one of your getters returned null instead of the intended field. You may be happy for your test suite to pass when this type of bug is present, but this does not mean that mutation testing has not been effective.
