### ISSUE TITLE
EvoSuite tests failing on PIT code coverage

### ISSUE THREAD

**Issue by biabs1** [hcoles/pitest#880]
Hello,

I've been trying to run PIT with tests generated by EvoSuite. However, some tests fail while PIT is running code coverage. These tests pass when I run them with JUnit and EvoSuite runtime test dependency (evosuite-standalone-runtime-1.0.6.jar) on the command line.

I know that Evosuite tests do not always work with PIT. I already tried the following approaches to try to solve this problem:
- Set the separateClassLoader parameter to false, when generating tests with EvoSuite;
- Tried many different versions of PIT;
- Compared the environment variables in the two test execution approaches (they are the same);
- Looked for tests dependencies (didn't find any);

None of these that I tried solved the issue. So I've been just removing these failing tests. However, I'm curious to know whether the problem is with PIT or with EvoSuite. @hcoles @gofraser.

Steps to reproduce the issue:
1. Download and unzip [this setup file](https://drive.google.com/file/d/1Isa4RCiBX5z8tgrDCMs1bdeBcVtDmQqj/view?usp=sharing);
2. Go to the Math-2f folder;
3. Run ./s on terminal.

**Comment by oscarlvp** [comment]
@biabs1 take a look at https://github.com/STAMP-project/pitest-evosuite-plugin to be able to run EvoSuite generated tests with PIT. The versions are a bit old, but they should be updated in the near future.
