### ISSUE TITLE
Problem to setup pitest with groovy spock gradle

### ISSUE THREAD

**Issue by viniciusmartinsds** [hcoles/pitest#901]
Hello, i'm trying to set up the environment but i got this error message:

`Exception in thread "main" org.pitest.help.PitHelpError: No mutations found.`

i use this guide to configure: https://gradle-pitest-plugin.solidsoft.info/ but didn't work.

is there any chance to configure pitest with groovy? thanks.

**Comment by szpak** [comment]
Is it an open source project which you could share a link to?

If not, please paste your pitest configuration in your project, together with the Gradle project `group` property value - it has to match a place where your production code and tests are located. In addition, what test framework do you use?

Btw, I have to update the page you mentioned. In the meantime I propose to use https://github.com/szpak/gradle-pitest-plugin where version 1.6.0 is covered.

**Comment by viniciusmartinsds** [comment]
Hello, it's a private project.
A group property is like 'com.org.org', i set the source too, 'sourceSets.main.groovy.srcDirs = ['src/main/groovy']'
spock is used as a test framework.

I use the version 1.6.0 now, but still got the error message: Exception in thread "main" org.pitest.help.PitHelpError

i think it's because i change the sourceSets, and the pitest is not finding the compiled code.

my pitest config: 

```
pitest {
    targetClasses = ['com.x.x.x.x.*']  //by default "${project.group}.*"
    pitestVersion = '1.6.6' //not needed when a default PIT version should be used
    threads = 4
    outputFormats = ['HTML']
    timestampedReports = false
}
```

**Comment by szpak** [comment]
> sourceSets.main.groovy.srcDirs = ['src/main/groovy']

Is your production code entirely written in Groovy? Or there is also some code in Java? PIT doesn't support mutating production Groovy code (however, using Spock to test Java production code is fine).

**Comment by viniciusmartinsds** [comment]
All is in Groovy, but, we generate the source to Java. Is there any way to point the pit to look to generate source code?

**Comment by szpak** [comment]
There is a [`mainSourceSet`](https://github.com/szpak/gradle-pitest-plugin/blob/c54467b6698ad17e3884fcb8ef97bf2322c05e4e/src/main/groovy/info/solidsoft/gradle/pitest/PitestPluginExtension.groovy#L102) property in the plugin configuration. You can try to add your generated source set there. I haven't tried it, so after that run the `pitest` task with `--info` and see in the PIT command line that your generated sources directory is properly passed.

**Comment by viniciusmartinsds** [comment]
@szpak how can i change the source in mainSourceSet?

**Comment by szpak** [comment]
I haven't tried, but to give it a quick check you could write:
```
sourceSets.main.java.srcDirs += 'build/generated/source/???/main'
```
somewhere in you `build.gradle`.

Please complete the path to match the place Gradle generates files in your project configuration.
