### ISSUE TITLE
Mutations for Operators Not Even Present in Code

### ISSUE THREAD

**Issue by apoorva-sriv** [hcoles/pitest#902]
There is no "not equal to" operator (`!=`) on line 7 of the code, so why does PIT have mutations like "not equal to less than" (12 to 16)? This is with `ALL` mutators. The code (including the test) is [here](https://github.com/apoorva-sriv/pitest-example).

![Capture](https://user-images.githubusercontent.com/22404638/120023618-0d21ae00-bfbc-11eb-8969-e80a59719e86.PNG)

**Comment by rnveach** [comment]
https://github.com/hcoles/pitest/search?q=%22not+equal+to+less+than%22
The message is coming from the ROR1 mutator.

According to https://pitest.org/quickstart/mutators/ , it swaps `==` with `<`.

The message is confusing that it doesn't mention how it is doing the substitution compared to the others.

**Comment by apoorva-sriv** [comment]
This is the output of `javap -c Example` (in the `target` folder, containing `Example.class`):
```
Warning: Binary file Example contains org.example.Example
Compiled from "Example.java"
public class org.example.Example {
  int num;

  public org.example.Example();
    Code:
       0: aload_0
       1: invokespecial #1                  // Method java/lang/Object."<init>":()V
       4: aload_0
       5: iconst_5
       6: putfield      #7                  // Field num:I
       9: return

  public void throwException();
    Code:
       0: iconst_5
       1: aload_0
       2: getfield      #7                  // Field num:I
       5: **if_icmpne**     16
       8: new           #13                 // class java/lang/UnsupportedOperationException
      11: dup
      12: invokespecial #15                 // Method java/lang/UnsupportedOperationException."<init>":()V
      15: athrow
      16: return
}
```

The [optimized](https://stackoverflow.com/questions/11478326/java-how-does-the-operator-work-when-comparing-int/11478453#11478453) bytecode instruction `if_icmpne` is why the "not equal to" message arises.
