### ISSUE TITLE
OpenPojo can create test that fails under PiTest, but not Junit

### ISSUE THREAD

**Issue by cyrusjk** [hcoles/pitest#914]
If in an OpenPojo test you add a SetterMustExistRule, the class may pass under regular Junit, but when the same test is run under PiTest, the instrumented class creates an error like:

 ```java.lang.AssertionError: [PojoFieldImpl [field=private static transient boolean[] com.company.package.model.ModelPojo.$$pitCoverageProbes, fieldGetter=null, fieldSetter=null]] is missing a setter```
 
 OpenPojo does not have a simple mechanism for excluding fields by name or other characteristics. This issue was not present in earlier versions of PiTest (tested 1.5.2, 1.6.7) so I do not know specifically when this became an issue.
 
 Run via Gradle, Junit4 and Junit5, Java 8, Macos

**Comment by hcoles** [comment]
This sounds like a duplicate of #873, which should be fixed by this change in OpenPojo https://github.com/OpenPojo/openpojo/issues/139

Does upgrading OpenPojo resolve the issue?

**Comment by cyrusjk** [comment]
I can confirm that upgrading to the latest version of OpenPojo DOES resolve the issue. Using PiTest 1.6.7 and OpenPojo 0.9.1 does not cause the issue described above. I will close this issue.

Thank you for the analysis and prompt response.
