### ISSUE TITLE
Increase timeouts in gradle pitest plugin

### ISSUE THREAD

**Issue by kamesh95** [hcoles/pitest#915]
I see that in maven pitest plugin there is a property timeoutConstant where we can specify the additional timeout we would like to keep. I am not able to find such property in gradle pitest plugin. Can you please help me on this? I am getting a lot of timeouts on my project and I want to see if it really is caused by infinite loops or due to low resources. I reduced the threads to 1 but that also did not help.

![image](https://user-images.githubusercontent.com/16370987/125576223-d20a669c-9e26-4769-9bbe-7d521f2ad355.png)

**Comment by echebbi** [comment]
As your issue seems related to the Gradle plug-in for Pitest I would advise you to ask on the corresponding repository: https://github.com/szpak/gradle-pitest-plugin

**Comment by szpak** [comment]
https://github.com/szpak/gradle-pitest-plugin is indeed a better place to report that kind of problems, however, GPP supports that property. It is just named [`timeoutConstInMillis`](https://github.com/szpak/gradle-pitest-plugin/blob/c54467b6698ad17e3884fcb8ef97bf2322c05e4e/src/main/groovy/info/solidsoft/gradle/pitest/PitestPluginExtension.groovy#L88) as I prefer to have a unit explicitly mentioned in the property name, to avoid confusion.

**Comment by kamesh95** [comment]
Thanks @szpak I was just looking for that. Will try it out.
