### ISSUE TITLE
No way to get all mutator IDs

### ISSUE THREAD

**Issue by JKutscha** [hcoles/pitest#916]
I am currently working on the Plug-in PITclipse and we would like to make each mutator selectable for a run, but there is no way of getting the key of the mutators.

The `Mutators` map in the class `Mutator.java` is private and you are only able to get the values of the map and not the keys, which are used for the CLI.

A method which would return all keys of `Mutators` would be great.

**Comment by hcoles** [comment]
@JKutscha Your PR has been merged in with a slight name change to the method 'allMutatorIds'

**Comment by JKutscha** [comment]
Thank you very much.
