### ISSUE TITLE
Mutation switching - is it present or planned for PITest?

### ISSUE THREAD

**Issue by krzema12** [hcoles/pitest#927]
Hi,

I've been using PITest for several months now, and every time I needed to very carefully choose a subset of classes under test. Otherwise, the test runtime would be not acceptable in daily iterative work.

Last time I wanted to introduce mutation testing in my TypeScript project and I stumbled upon Stryker which boasts with [mutation switching](https://stryker-mutator.io/blog/announcing-stryker-4-mutation-switching/#-mutation-switching) approach. Indeed the performance gain is superb. It's good enough so that we included it in our CI running for each pull request (only +1-2 minutes to each PR).

Did you consider adopting such approach?

**Comment by hcoles** [comment]
In the literature "mutation switching" is known as "mutant schemata". I discussed the pros and cons of this vs other approaches a few years ago when talking about the trade offs when designing a mutation tool.

https://pitest.org/java_mutation_testing_systems/

For compiled languages schemata have performance advantages at the generation stage vs multiple compilation runs, but no advantage over pitest's bytecode manipulation approach.

It might have a small advantage at the insertion phase vs pitest's hot swapping, but probably not.

So, while it might have made stryker much faster compared to earlier versions of itself, it would probably make little difference to pitest's performance.

If you're interested in running pitest against PRs you might want to go through the long read here

https://blog.pitest.org/dont-let-your-code-dry/

And take a look at the tooling here

https://pitest.groupcdg.com/

**Comment by krzema12** [comment]
Thanks @hcoles for your comprehensive answer, all clear!
