### ISSUE TITLE
[Question] Pitest compatibility with integration tests

### ISSUE THREAD

**Issue by kamesh95** [hcoles/pitest#931]
I am using pitest on one of the java repositories where a large part of the tests are integration tests, and able to integrate Pitest to execute the mutation testing, But I want to know how effective/valid the generated mutation score is when most of the parts of code are covered via integration tests only. 

Is it right to use Pitest in such scenarios, or is their an option to let pitest know that it is running on integration tests so that the mutation score can be considered valid? Thanks.

**Comment by hcoles** [comment]
"Integration Test" is not a well defined term.

If you have tests that executes the code under test in a different JVM from the tests themselves (eg hitting a running webserver), then pitest will not work at all.

If you have tests that execute the code in the same JVM, but rely on some external resource (eg a database) then you will hit two issues

1. It will be very slow
2. Mutations may be falsely killed if one mutant adds bad state to the DB that can be read by the ones that follow

If you have tests that exercise code from lots of different "units" but that tests are fast, self contained and do not rely on external services then there should be no issue.

Code and tests can be excluded from analysis using the excludedClasses and excludedTestClasses parameters.

**Comment by kamesh95** [comment]
Thanks for the quick response @hcoles This does make sense, will close this.
