### ISSUE TITLE
Unable to view generated code in target - generated-sources folder exists but it has no java files

### ISSUE THREAD

**Issue by nagkumar** [hcoles/pitest#935]
Unable to see the generated sources of the mutants created..folder exists, but with no mutant source code

![image](https://user-images.githubusercontent.com/332234/134609255-86306498-70a8-4617-896c-168a856a95fb.png)

**Comment by hcoles** [comment]
Pitest is a bytecode mutator and does not generate source files.

The generated-sources folder created by maven and has not relation to pitest.
