### ISSUE TITLE
a++ and a-- should the tests be killed

### ISSUE THREAD

**Issue by nagkumar** [hcoles/pitest#936]
when -mutators MATH, I do see a++ and a--, when the tests don't fail, the report says mutations are not killed for this change.

Do a++ and a-- not an equivalent mutant, as the value of 'a' only changes after operation gets the value 'a'?

Is this a bug in the framework to consider it as a killable mutant?

**Comment by hcoles** [comment]
Pitest mutates bytecode, not source code. That said, can you provide an example of some code where you have a surviving mutant, and the test that is failing to kill it?

**Comment by feckertson** [comment]
It sounds like the code contains `a++` somewhere. If someone accidentally chanted that code to be `a--` instead, a defect would be introduced. I believe pitest is saying that there is no unit test to catch such an accident. Have you tried actually making that code change and running the unit tests?

**Comment by nagkumar** [comment]
No, my code does not have a++ anywhere..

![image](https://user-images.githubusercontent.com/332234/134669625-090e1d4a-63c1-44b3-8931-b0038f26f876.png)

Code is 

![image](https://user-images.githubusercontent.com/332234/134669680-193070c5-b9c6-4517-b2d3-ee23ea50fda0.png)

Full code at https://github.com/nagkumar/mutate-test-kata

**Comment by feckertson** [comment]
Perhaps it is a Unary Operator Insertion then. The mutation is to change `setSalary(aNewSalary)` into `setSalary(aNewSalary++)`.

**Comment by hcoles** [comment]
The mutations you are seeing are generated by the UOI mutator, not the math mutator. They are active because you have set the mutators to "ALL".

Do not do this. It activates experimental mutators and mutators (such as UOI) that are present for use in research only. They are not suitable for general development, and will be moved into a seperate repo soon, now that pitest supports pluggable mutators.

In this case the mutations are indeed equivalent. In other scenarios the mutant might not be equivalent.

**Comment by nagkumar** [comment]
> Perhaps it is a Unary Operator Insertion then. The mutation is to change `setSalary(aNewSalary)` into `setSalary(aNewSalary++)`.

**Comment by nagkumar** [comment]
As this is  equivalent mutants, should reporting needs a fix?

**Comment by hcoles** [comment]
It is a mutator that you should not enable, partly becuase it is likely to create equivalent mutants.

Although pitest filters out some equivalent mutants, it is not possible to do it in every case, and not practical to do it for all mutations. We only attempt it for mutators in the DEFAULT and STRONGER sets.
