### ISSUE TITLE
Link on pitest.org is not valid anymore

### ISSUE THREAD

**Issue by khmarbaise** [hcoles/pitest#937]
The link on the starting page http://pitest.org/quickstart/maven/ about jcenter is not valid anymore.

**Comment by szpak** [comment]
Good spot @khmarbaise . Would you like to crate a PR with the fix?

https://github.com/hcoles/pitest-site/blob/gh-pages/quickstart/maven.markdown

**Comment by khmarbaise** [comment]
Done https://github.com/hcoles/pitest-site/pull/120

**Comment by szpak** [comment]
Thanks @khmarbaise !
