### ISSUE TITLE
pitest 1.7.0 gradle '7.0'  does not show test coverage correct for java 11

### ISSUE THREAD

**Issue by galstyanzara** [hcoles/pitest#941]
Hello. here are my configurations.

```
plugins {
	id 'java'
	id 'info.solidsoft.pitest' version '1.7.0'
}
pitest {
	junit5PluginVersion = '0.15'
	targetClasses = ['com.example.*']
	targetTests = ['com.example.*']
	exportLineCoverage = true
	timestampedReports = true
	outputFormats = ["HTML"]
}
java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(11)
	}
}
```

When I change `JavaLanguageVersion.of(11)` to ` JavaLanguageVersion.of(8)` it is working and showing the right Coverage Report.

But with `JavaLanguageVersion.of(11)` everything is always not covered and always 0%.

**Comment by szpak** [comment]
It's a known limitation in the Gradle plugin - https://github.com/szpak/gradle-pitest-plugin/issues/301

**Comment by szpak** [comment]
Btw, just to be sure, remove/comment the toolchain section and run the `pitest` task with Java 11 set with `JAVA_HOME`.
