### ISSUE TITLE
Maven pitest plugin not able to detect test classes with Kotlin if the test directory is src/test/kotlin

### ISSUE THREAD

**Issue by galegofer** [hcoles/pitest#948]
I have a Kotlin project with Maven in which my tests are located at src/test/kotlin, but when I am configuring the plugin and adding the package, the plugin says that they are no tests. 

I suspect that the plugin is searching the tests at src/test/java, maybe it would be helpful to add an option to the plugin to change that, or is there any workaround possible?.

**Comment by hcoles** [comment]
Closing as no repsonse from OP.
