### ISSUE TITLE
excludedMethods seems to not work

### ISSUE THREAD

**Issue by guillomep** [hcoles/pitest#950]
Hello, I have a problem with using excludedMethods in pitest 1.7.2 with maven.

I have the following test class

```java
class TestClass {
    @Test
    void test1() { ... }
    
    @Test
    void testToExclude() { ... }
}
```

And my pom.xml is the following

```xml
 <plugin>
        <groupId>org.pitest</groupId>
        <artifactId>pitest-maven</artifactId>
        <dependencies>
          <dependency>
            <groupId>org.pitest</groupId>
            <artifactId>pitest-junit5-plugin</artifactId>
            <version>0.15</version>
          </dependency>
        </dependencies>
        <configuration>
          <targetClasses>
            <param>com.example.*</param>
          </targetClasses>
          <targetTests>
            <param>com.example.*</param>
          </targetTests>
          <excludedMethods>
            <excludedMethod>testToExclude</excludedMethod>
          </excludedMethods>
          <avoidCallsTo>
            <avoidCallsTo>org.apache.logging</avoidCallsTo>
            <avoidCallsTo>org.slf4j</avoidCallsTo>
            <avoidCallsTo>io.micrometer</avoidCallsTo>
          </avoidCallsTo>
          <timeoutConstant>60000</timeoutConstant>
          <threads>1</threads>
          <outputFormats>xml,html</outputFormats>
          <exportLineCoverage>true</exportLineCoverage>
          <timestampedReports>false</timestampedReports>
        </configuration>
      </plugin>
```

The method `testToExclude` is still executed resulting in an error that's my test is not green.
I am sure that I missed something but I don't know what.

**Comment by guillomep** [comment]
That make so sense. So there is a missing `excludedTestMethods` feature

**Comment by nicolasSoyeur** [comment]
Per my understanding :
`excludedTestClasses` is to exclude test class during the execution of the mutation test. Is it not about : don't put mutation in this test class.

Below is what you can find in the documentation :
List of globs to match against test class names. Matching tests will not be run (note if a suite includes an excluded class, then it will “leak” back in)

What do you want ? to avoid the execution of some specific tests during your mutation test run ?

**Comment by hcoles** [comment]
Pitest won't add an excludedTestMethods feature, there are awkward corner cases where this would sometimes not work as expected.

Instead you can use the test exclusion methods already built into the test frameworks, such as JUnit 4 Categories and JUnit 5 tags.

**Comment by guillomep** [comment]
Okay good to know I will look at JUnit5 tags
