### ISSUE TITLE
Pitest running for over 3 hours & stucked with no outcome, had to cancel

### ISSUE THREAD

**Issue by umeshnebhani733** [hcoles/pitest#953]
Hi, 

I am trying to integrate pitest as an importat step of code quality, we have integrated it over a year ago & it was working well.

Since few weeks its not working as we expect, it kept running over 3 hours sometimes even 6 hours even though we enabled history & it use to take minutes.

We would like to debug what is causing this problem. ( Most likely one of the test which its trying to execute ) But there is no way to debug what cause it.

We already enabled "verbose = true" but didnt help.  Went through documentation couldnt find any other way. Can someone help?   here is how my config looks like

``
pitest {
  testPlugin = 'junit5'
  threads = 5
  coverageThreshold = 70 
  mutationThreshold = 70
  historyInputLocation = 'pitestHistory/pitestHistory'
  historyOutputLocation = 'pitestHistory/pitestHistory'
  useClasspathFile = true     //useful with bigger projects on Windows
  timestampedReports = false
  withHistory = true
  mutators = ["DEFAULTS"]
  outputFormats = ['HTML']
  timeoutFactor = 4.0 // Setting to a higher value as it's getting timed out on CI
  verbose = true
}

**Comment by umeshnebhani733** [comment]
Update : We found an issue, it was due to the fact that we are running our tests parallel with  "@Execution(CONCURRENT)"

So we are still running it in parallel when we execute them, but we disabled this while running pitest as follows: 

jvmArgs= ["-Djunit.jupiter.execution.parallel.enabled=false"]

**Comment by hcoles** [comment]
Thanks for reporting back.
