### ISSUE TITLE
Exclude test classes with annotation

### ISSUE THREAD

**Issue by esovan** [hcoles/pitest#959]
A specific annotation for excluding a test class or method from pitest would be much better. The  `javax.annotation.Generated` suggested in #347 is used for generated code and therefore is also excluded in other tools like jacoco, checkstyle and others.

 The format suggested by @AFulgens would make a lot of sense:
> I am pro-annotation, so a generic solution with class/method annotations, with an optional parameter as to _which_ mutators should be excluded would be really awesome. Something like `@MutationFilter` for exclude every mutator and `@MutationFilter(exclude={"VOID_METHOD_CALLS", "NON_VOID_METHOD_CALLS"})` for fine-tuning.

.. and if annotated class or function by default is excluded for all mutations, that would be perfect I think.

_Originally posted by @esovan in https://github.com/hcoles/pitest/issues/159#issuecomment-967151752_

**Comment by hcoles** [comment]
As discussed in #347 `javax.annotation.Generated` has source retention, so is not visible in the bytecode. Pitest could only ignore it if it processed source code instead/as well as bytecode.

Jacoco cannot igore `javax.annotation.Generated` for the same reason.

**Comment by esovan** [comment]
I dont think that is right, or maybe i misunderstand you. 
I have tested by putting `@javax.annotation.processing.Generated("foo")` on my test class. When I do so, the coverage in jacoco goes below 100%. So jacoco must have found a way to exclude it.

**Comment by esovan** [comment]
I think a pitest specific annotation would make sense in order to make sure big performance tests are not used for mutation coverage.

**Comment by esovan** [comment]
I might have mixed my tests up, because I can't reproduce my result now. So you are probably right after all.

**Comment by esovan** [comment]
> As discussed in #347 `javax.annotation.Generated` has source retention, so is not visible in the bytecode. Pitest could only ignore it if it processed source code instead/as well as bytecode.
> 
> Jacoco cannot igore `javax.annotation.Generated` for the same reason.

I just re-read your comment and it makes sense. I had misinterpreted it. Closing this even though annotations would be very nice.

**Comment by hcoles** [comment]
Annotations can be used to exclude code from analysis, so long as they have class retention (or higher).

Pitest will ignore anything annotated with an something named

* Generated
* DoNotMutate
* CoverageIgnore

**Comment by esovan** [comment]
Does it work on test classes? 
My case is that we have a really slow and expensive integration test class. We want it to run only once due to pipeline integration limitations. So if we could make sure no mutations tests are using it that would solve our problem. 
Its not possible for us to configure the pitest configuration, hence we would like to be able to solve it with annotations.
I hope it works and will try it out tomorrow.

**Comment by hcoles** [comment]
No, the annotation support is for code to mutate only.

For tests, you can either uses pitest's excluded test classes parameter (which accepts globs), or use junit 4 categories/junit 5 test tags.

**Comment by nagkumar** [comment]
> Annotations can be used to exclude code from analysis, so long as they have class retention (or higher).
> 
> Pitest will ignore anything annotated with something named
> 
> * Generated
> * DoNotMutate
> * CoverageIgnore

Where are these annotations defined especially DoNotMutate and CoverageIgnore, if you could give the full class name including the package that would help.

**Comment by scholzj** [comment]
Note: Be careful, the pitest-annotations package seems to have a proprietary license.
