### ISSUE TITLE
maven pitest reports warning when importing into Sonarqube

### ISSUE THREAD

**Issue by mgonzcast** [hcoles/pitest#961]
Not sure if the issue is from the mutation plugin in Sonarqube or the reports created in Maven:

https://github.com/devcon5io/mutation-analysis-plugin/issues/55

but I get a bunch or warnings reporting:

WARN: Found unknown mutation operator: org.pitest.mutationtest.engine.gregor.mutators.returns.NullReturnValsMutator

or

WARN: Found unknown mutation operator: WARN: Found unknown mutation operator: org.pitest.mutationtest.engine.gregor.mutators.returns.EmptyObjectReturnValsMutator

Am I missing anything?

**Comment by hcoles** [comment]
That warning is not generated by pitest. I suggest you raise an issue against whichever sonar plugin you are using.

**Comment by mgonzcast** [comment]
thanks @hcoles for the quick answer. I was wondering if maybe the mutation operators used by default with maven were not recognized by the mutation analysis plugin from Sonarqube. That´s why I asked here
