### ISSUE TITLE
Not issue but rather a question, what is test strength in the report?

### ISSUE THREAD

**Issue by tanyagorn** [hcoles/pitest#966]
I just couldn't find it in any document for Pitest. I've cloned the source code to look exactly what it is and found that it was calculated base on this formula;

Math.round((100f / getTotalMutationsWithCoverage())
            * getTotalDetectedMutations());

However, I still could not find a word to describe what it exactly is... anyone can help clarify?

**Comment by hcoles** [comment]
Test strength is a measure of how good the tests you have are at verifying the code they *cover*.

So, if you have a million lines of code, and a test suite that covers 10 of those lines, and kills all the mutants there, your test strength will be 100%.

If you have 10 lines of code, and a test suite that covers all of them, but kills none of the mutants, your test strength will be 0%.
