### ISSUE TITLE
Returning an Optional.empty() inside try-with-resources causes mutant to survive

### ISSUE THREAD

**Issue by nikosstais** [hcoles/pitest#968]
I have a mutant that cannot be killed with message:
`replaced return value with Optional.empty for com/blah::createFile → SURVIVED`

```
try (final var os = new ByteArrayOutputStream()){

... some code to write on os

  if (case I do not need the file anyway){
     return Optional.empty(); <-- here tries to replace the return value with Optional.empty() 
  }

  return Optional.of(os.toByteArray());
}
```

I am using version 1.7.3

Based on quick start guide https://pitest.org/quickstart/mutators/ :
_Pitest will filter out equivalent mutations to methods that are already hard coded to return the empty value._

It seems that above statement is not respected in my case

**Comment by hcoles** [comment]
Hi @nikosstais, thanks for the report (and sorry for the slow response).

I've taken a look at this, and it is going to be an awkward issue to resolve. The filtering of `return Optional.empty()` mutants works by looking for bytecode the pushs empty onto the stack, immeditately followed by a return.

Unfortunately, try-with-resources is causing the compiler to store the ref in a local variable before returning.

Filtering this out at the bytecode level would require an analysis that tracked what was stored, but didn't trigger for more complex code where the mutant shouldn't be filtered.

It's certainly possible, but not something that is going to be fixed quickly.

**Comment by hcoles** [comment]
Ok, couldn't help picking at this. There should be something in the next release which picks up at leasst some cases of this.

**Comment by hcoles** [comment]
Release 1.9.4 extends the analysis to work with java 8 and catch more complex cases.
