### ISSUE TITLE
JUnit Test Flaky When Run in PIT

### ISSUE THREAD

**Issue by Arraying** [hcoles/pitest#969]
All the (JUnit5) tests in this project pass when running them through our IDE or the Gradle task.

But I cannot run mutation tests when I run the PIT Gradle task due to this exception:
```
Exception in thread "main" org.pitest.help.PitHelpError: 1 tests did not pass without mutation when calculating line coverage. Mutation testing requires a green suite.
See http://pitest.org for more details.
	at org.pitest.coverage.execute.DefaultCoverageGenerator.verifyBuildSuitableForMutationTesting(DefaultCoverageGenerator.java:114)
	at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:96)
	at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:51)
	at org.pitest.mutationtest.tooling.MutationCoverage.runReport(MutationCoverage.java:115)
	at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:121)
	at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:51)
	at org.pitest.mutationtest.commandline.MutationCoverageReport.runReport(MutationCoverageReport.java:87)
	at org.pitest.mutationtest.commandline.MutationCoverageReport.main(MutationCoverageReport.java:45)
```

The test that fails looks like this:
```java
class PermissionValidatorTest {
    private static final String auth = "";
    private static final User emp = new User(UUID.randomUUID(), "user", null, Role.EMPLOYEE);
    private static final User adm = new User(UUID.randomUUID(), "admi", null, Role.ADMINISTRATOR);

    private static final Booking booking = new Booking(emp.getUsername(), 3L, null, null);
    
    // -snip- other test classes

    @Test
    void adminPermission() throws InvalidBookingException {
        handler = new PermissionValidator(adm, null, null, auth);
        assertThrows(InvalidBookingException.class, () -> handler.handle(booking));

        booking.setDesc("Some description");
        assertTrue(handler.handle(booking));
    }
}
```
`adminPermission` is the only method that modifies the description. If I then add an assertion before `assertThrows` to ensure that the description is `null` and the assertion fails:
```
expected: <null> but was: <Some description>
```

I can resolve this problem by constructing `booking` as such:
```java
    private Booking booking = null;

    @BeforeEach
    void setUp() {
        booking = new Booking(emp.getUsername(), 3L, null, null);
    }
```

It seems like static is a/the problem, but I cannot fathom how a field that only gets set inside the test could possibly get set before it is formally set. I can assure you it is only ever set once:
![img](https://i.imgur.com/x0ryWxw.png)

Do you perform some sort of static analysis on the code which might have evaluated this? Perhaps some bytecode is getting re-arranged in the wrong way. [This issue](https://github.com/hcoles/pitest/issues/540) and [this issue](https://github.com/hcoles/pitest/issues/332) seem to be having similar problems, whereby the former seems more relevant to our scenario. Similarly I feel like [this post](https://stackoverflow.com/questions/30789480/junit-tests-pass-but-pit-says-the-suite-isnt-green) here does not apply since for us this is the only one of ~330 tests that fails, instead of all.

We are using the Gradle plugin version `1.5.2` and tool version `1.5.1`. However, I have also tried this on plugin version `1.7.0` (latest I found [here](https://plugins.gradle.org/plugin/info.solidsoft.pitest)) and tool version `1.7.3` and the same issue persists. Similarly, we are using JUnit Jupiter `5.5.2`, but even upgrading to `5.8.2` did not resolve the problem. We are on Java 11.

**Comment by hcoles** [comment]
Mutable static fields in JUnit tests are allows a rich source of test order dependencies and should be avoided. The default JUnit model is to create an instance of the test for each test case, and this pattern shouldn't be broken unless you have an excellent reason to do so. Breaking it results in difficult to debug issues such as this one.

So, this most likely is a test order dependency, in which case it is not specific to pitest. JUnit will always run the tests in the same (but unpredictable) order. Adding a new test case may change the order in the future and trigger the same failure.

To fix it there is no need to use a BeforeAll, just removing the static modifier and constructing inline should be sufficient.

If you are convinced that this is not a test order dependency, and is related to something pitest is doing, please create a minimal project that reproduces the issue and I'll take a look.

**Comment by Arraying** [comment]
> Mutable static fields in JUnit tests are allows a rich source of test order dependencies and should be avoided. The default JUnit model is to create an instance of the test for each test case, and this pattern shouldn't be broken unless you have an excellent reason to do so. Breaking it results in difficult to debug issues such as this one.
> 
> So, this most likely is a test order dependency, in which case it is not specific to pitest. JUnit will always run the tests in the same (but unpredictable) order. Adding a new test case may change the order in the future and trigger the same failure.
> 
> To fix it there is no need to use a BeforeAll, just removing the static modifier and constructing inline should be sufficient.
> 
> If you are convinced that this is not a test order dependency, and is related to something pitest is doing, please create a minimal project that reproduces the issue and I'll take a look.

I've created a minimum working example [here](https://github.com/Arraying/PITMVP). It's private for now (+ I have sent the invitation). Right now, it's failing if you run the `pitest` Gradle task, but the `test` task works.

**Comment by hcoles** [comment]
Taken a quick look. It is indeed a test order dependency - but with a twist.

Because JUnit 5 tests are dynamic (generators can create more tests at runtime) the pitest JUnit 5 plugin has to execute them to discover which tests they create, before running them for real.

So the test gets run twice. It passes the first time, then fails the 2nd as the static variable has been updated.

I need to take a look at the JUnit 5 plugin to see if this situation can be improved. Gradle is either managing not to run the code during discovery, or is using a jvm cleaned of static state. If the former is possible, pitest should do that.

Even if this were fixed, your test would still be unusable for mutation testing. Pitest has to run tests multiple times in the same jvm. A test that fails the 2nd time you run it (ie is not repeatable) it cannot be used as it will give false results.
