### ISSUE TITLE
Running pitest using Maven java.lang.ClassNotFoundException: org.pitest.coverage.execute.CoverageMinion

### ISSUE THREAD

**Issue by dudu12091** [hcoles/pitest#987]
![image](https://user-images.githubusercontent.com/40813915/153672515-753fe0f9-54e9-4476-aaa8-16043f12f538.png)

Cannot find the class org.pitest.coverage.execute.CoverageMinion
![image](https://user-images.githubusercontent.com/40813915/153672560-691365af-5e6d-4b6d-b252-db39dc88c935.png)

**Comment by hcoles** [comment]
If you can post a complete, minimal project that reproduces the issue I can take a look.

**Comment by dudu12091** [comment]
Thanks, Henry!  But it still has the same error after I added in the compiler plugin.

**Comment by dudu12091** [comment]
> In addition to the missing pom configuration I suspect you have an outdated installation of maven and/or java.

And my maven version is 3.8.4, java version is 1.8.0_144. Should I try to run it under another java version?

**Comment by dudu12091** [comment]
![image](https://user-images.githubusercontent.com/40813915/153714646-3cb910fb-456b-4dc9-aed0-17951fd8bf05.png)

I checked the info in the log. I guess the classpath is wrong. Maybe it should be .org.pitest:pitest-1.7.4. Is there anyway to change the configuration of classpath?

**Comment by hcoles** [comment]
The project is fine (one the compiler plugin config is added), but there is something strange about the system you are running it on. Best guess is that you have added jars to the system classpath.

I'd also have expected the project to error for you without the compiler config if you are running maven 3.8.4. Is that definitely the version being picked up?

What is the full output of running

```
mvn --version
java -version
```

Can you also post the command you use and the complete log you see when running pitest.

**Comment by dudu12091** [comment]
```mvn --version```
Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)
Maven home: E:\apache-maven-3.8.4
Java version: 1.8.0_181, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk1.8.0_181\jre
Default locale: zh_CN, platform encoding: GBK
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

```java -version```
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

```mvn org.pitest:pitest-maven:mutationCoverage```
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------< com.ibo.pit:pit_test >------------------------
[INFO] Building pit_test 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- pitest-maven:1.7.4:mutationCoverage (default-cli) @ pit_test ---
[WARNING] The artifact xml-apis:xml-apis:jar:2.0.2 has been relocated to xml-apis:xml-apis:jar:1.0.b2
[INFO] Found plugin : Default csv report plugin
[INFO] Found plugin : Default xml report plugin
[INFO] Found plugin : Default html report plugin
[INFO] Found plugin : Static initializer code detector plugin
[INFO] Found plugin : Excluded annotations plugin
[INFO] Found plugin : Try with resources filter
[INFO] Found plugin : Inlined finally block filter plugin
[INFO] Found plugin : Implicit null check filter
[INFO] Found plugin : Method reference null check filter
[INFO] Found plugin : For each loop filter
[INFO] Found plugin : Enum constructor filter
[INFO] Found plugin : Record junk mutation filter
[INFO] Found plugin : Logging calls filter
[INFO] Found plugin : Infinite for loop filter
[INFO] Found plugin : Long running iterator loop filter
[INFO] Found plugin : For loop counter filter
[INFO] Found plugin : Kotlin junk mutations filter
[INFO] Found plugin : Max mutations per class limit
[INFO] Found plugin : Equals shortcut equivalent mutant filter
[INFO] Found plugin : Trivial return vals equivalence filter
[INFO] Found plugin : Mutant export plugin
[INFO] Found shared classpath plugin : Default mutation engine
[INFO] Found shared classpath plugin : JUnit plugin
[INFO] Found shared classpath plugin : TestNG plugin
[INFO] Available mutators : EXPERIMENTAL_ARGUMENT_PROPAGATION,FALSE_RETURNS,TRUE_RETURNS,CONDITIONALS_BOUNDARY,CONSTRUCTOR_CALLS,EMPTY_RETURNS,INCREMENTS,INLINE_CONSTS,INVERT_NEGS,MATH
,NEGATE_CONDITIONALS,NON_VOID_METHOD_CALLS,NULL_RETURNS,PRIMITIVE_RETURNS,REMOVE_CONDITIONALS_EQUAL_IF,REMOVE_CONDITIONALS_EQUAL_ELSE,REMOVE_CONDITIONALS_ORDER_IF,REMOVE_CONDITIONALS_O
RDER_ELSE,RETURN_VALS,VOID_METHOD_CALLS,EXPERIMENTAL_BIG_DECIMAL,EXPERIMENTAL_BIG_INTEGER,EXPERIMENTAL_MEMBER_VARIABLE,EXPERIMENTAL_NAKED_RECEIVER,REMOVE_INCREMENTS,EXPERIMENTAL_RETURN
_VALUES_MUTATOR,EXPERIMENTAL_SWITCH,EXPERIMENTAL_BIG_DECIMAL,EXPERIMENTAL_BIG_INTEGER,ABS,AOD1,AOD2,AOR1,AOR2,AOR3,AOR4,CRCR1,CRCR2,CRCR3,CRCR4,CRCR5,CRCR6,OBBN1,OBBN2,OBBN3,ROR1,ROR2,ROR3,ROR4,ROR5,UOI1,UOI2,UOI3,UOI4
[INFO] Adding org.pitest:pitest to SUT classpath
[INFO] Mutating from F:\learn\UCL\COMP\COMP0103 Validation and Verification\Coursework1\pit_test\target\classes
14:25:22 PIT >> INFO : ---------------------------------------------------------------------------
14:25:22 PIT >> INFO : Enabled (+) and disabled (-) features.
14:25:22 PIT >> INFO : -----------------------------------------
14:25:23 PIT >> INFO : +FANN           Filters mutations in classes and methods with matching annotations of class or runtime retention
14:25:23 PIT >> INFO :   [annotation]    Annotation to avoid (full package name not required)
14:25:23 PIT >> INFO : +FENUM          Filters mutations in enum constructors
14:25:23 PIT >> INFO : +FFBLOCK        Filters mutations in code duplicated by finally block inlining
14:25:23 PIT >> INFO : +FFEACH         Filters mutations in compiler generated code that implements for each loops
14:25:23 PIT >> INFO : +FFLOOP         Filters any mutations to increments in for loops as they may cause timeouts
14:25:23 PIT >> INFO : +FINFINC        Filters mutations to increments that may cause infinite loops
14:25:23 PIT >> INFO : +FINFIT         Filters mutations that may cause infinite loops by removing calls to iterator.next
14:25:23 PIT >> INFO : +FINULL         Filters mutations in compiler generated code that checks for null by calling getClass
14:25:23 PIT >> INFO : +FKOTLIN        Filters out junk mutations in bytecode created by compiler for kotlin language features
14:25:23 PIT >> INFO : +FLOGCALL       Filters mutations in code that makes calls to logging frameworks
14:25:23 PIT >> INFO : +FMRNULL        Filters mutations in compiler generated code that inserts Objects.requireNonNull for method references
14:25:23 PIT >> INFO : +FRECORD        Filters mutations in compiler generated record code
14:25:23 PIT >> INFO : +FRETEQUIV      Filters return vals mutants with bytecode equivalent to the unmutated class
14:25:23 PIT >> INFO : +FSEQUIVEQUALS  Filters equivalent mutations that affect only performance in short cutting equals methods
14:25:23 PIT >> INFO : +FSTATI         Filters mutations in static initializers and code called only from them
14:25:23 PIT >> INFO : +FTRYWR         Filters mutations in code generated for try with resources statements
14:25:23 PIT >> INFO : -CLASSLIMIT     Limits the maximum number of mutations per class
14:25:23 PIT >> INFO :   [limit]         Integer value for maximum mutations to create per class
14:25:23 PIT >> INFO : -EXPORT         Exports mutants bytecode and other details to disk
14:25:23 PIT >> INFO : ---------------------------------------------------------------------------
14:25:24 PIT >> FINE : Running report with ReportOptions [targetClasses=[com.ibo.pit.*], excludedMethods=[], excludedClasses=[], excludedTestClasses=[], codePaths=[F:\learn\UCL\COMP\CO
MP0103 Validation and Verification\Coursework1\pit_test\target\classes], reportDir=F:\learn\UCL\COMP\COMP0103 Validation and Verification\Coursework1\pit_test\target\pit-reports, histo
ryInputLocation=null, historyOutputLocation=null, sourceDirs=[F:\learn\UCL\COMP\COMP0103 Validation and Verification\Coursework1\pit_test\src\main\java, F:\learn\UCL\COMP\COMP0103 Vali
dation and Verification\Coursework1\pit_test\src\test\java], classPathElements=[F:\learn\UCL\COMP\COMP0103 Validation and Verification\Coursework1\pit_test\target\test-classes, F:\lear
n\UCL\COMP\COMP0103 Validation and Verification\Coursework1\pit_test\target\classes, E:\apache-maven-3.8.4\repository\junit\junit\4.13.2\junit-4.13.2.jar, E:\apache-maven-3.8.4\reposit
ory\org\hamcrest\hamcrest-core\1.3\hamcrest-core-1.3.jar, E:\apache-maven-3.8.4\repository\org\pitest\pitest\1.7.4\pitest-1.7.4.jar], mutators=[], features=[], dependencyAnalysisMaxDis
tance=-1, jvmArgs=[-Djava.awt.headless=true], numberOfThreads=1, timeoutFactor=1.25, timeoutConstant=3000, targetTests=[^com\.ibo\.test\..*$], loggingClasses=[], verbosity=VERBOSE, fai
lWhenNoMutations=true, outputs=[HTML], groupConfig=TestGroupConfig [excludedGroups=[], includedGroups=[]], fullMutationMatrix=false, mutationUnitSize=0, shouldCreateTimestampedReports=
true, detectInlinedCode=true, exportLineCoverage=false, mutationThreshold=0, testStrengthThreshold=0, coverageThreshold=0, mutationEngine=gregor, javaExecutable=null, includeLaunchClasspath=true, properties={}, maxSurvivors=0, excludedRunners=[], includedTestMethods=[], testPlugin=, useClasspathJar=false, skipFailingTests=false]
14:25:24 PIT >> FINE : System class path is E:\apache-maven-3.8.4\boot\plexus-classworlds-2.6.0.jar
14:25:24 PIT >> FINE : Maximum available memory is 3600 mb
14:25:24 PIT >> FINE : Incremental analysis set 21 mutations to a status of NOT_STARTED
14:25:24 PIT >> INFO : Incremental analysis reduced number of mutations by 0
14:25:24 PIT >> INFO : Created  1 mutation test units in pre scan
14:25:24 PIT >> FINE : MINION : Installing PIT agent
14:25:24 PIT >> INFO : MINION : 错误: 找不到或无法加载主类 org.pitest.coverage.execute.CoverageMinion

Thank you very much!!!

**Comment by hcoles** [comment]
Not sure what the issue is here. It's definitely something to do with you environment. Do you have access to a different machine to try it on?

Also, can you try moving the project to a directory on a local drive with no spaces or non ascii characters in the path. Pitest has no current known issues with this, but it did have path related bugs in the past.

**Comment by hcoles** [comment]
closing as no response since 13 Feb
