### ISSUE TITLE
Class-level mutation operators

### ISSUE THREAD

**Issue by muzammil786** [hcoles/pitest#989]
Is there a plan to extend the operators to support inheritance and polymorphism? The full list of operators in this category was proposed by Ma and Offut and implemented in muJava. See Table 1 in this paper: https://cs.gmu.edu/~offutt/mujava/mutopsClass.pdf

**Comment by hcoles** [comment]
No. This would would not fit with inserting mutants through bytecode manipulation or targetting based on coverage.
